'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync('js/engine.js','utf8')+'\nthis.api={Game,TYPES,KEY,AIR};',ctx);const {Game,TYPES,KEY,AIR}=ctx.api;
function field(mode='turns'){const g=new Game('river','normal',17,mode);g.terrain.fill('plain');g.units=[];g.structures=[];g.mines=[];g.aiEnabled=false;g.add('blue','hq',0,13);g.add('red','hq',35,0);g.add('blue','infantry',0,12);g.add('red','infantry',35,1);g.rng=()=>.6;return g;}
function advance(g,s){for(let t=0;t<s-1e-8;t+=1/30)g.update(Math.min(1/30,s-t));}
function settle(g){let n=0;while(g.busy&&n++<5000)g.update(1/30);assert.ok(n<5000);}
function near(a,b){assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);}
let checks=0;function check(name,fn){fn();checks++;console.log('OK '+name);}
check('Duas classes: atributos, compatibilidade e alcances por alvo',()=>{for(const mode of ['turns','rts']){const g=field(mode),v=g.add('blue','antiAirVehicle',5,5),s=g.add('blue','missileInfantry',5,7),air=g.add('red','helicopter',11,5),land=g.add('red','tank',6,7),base=g.add('red','post',5,8);g.updateVision();assert.equal(v.hp,90);assert.equal(s.hp,80);assert.equal(g.weapon(v,land),null);assert.equal(g.range(v,air),6);assert.equal(g.range(s,air),3);assert.equal(g.range(s,land),1);assert.equal(g.canFire(s,land),true);assert.equal(g.canFire(s,base),true);land.x=7;assert.equal(g.canFire(s,land),false);assert.ok(g.canFire(v,air));assert.equal(g.order(v,'attack',{targetId:land.id}),false);assert.equal(TYPES.antiAirVehicle.vehicle,true);assert.ok(!TYPES.missileInfantry.vehicle);assert.equal(g.cost(v,6,5),1);g.terrain[KEY(6,5)]='forest';assert.equal(g.cost(v,6,5),2);g.terrain[KEY(6,5)]='river';assert.equal(g.cost(v,6,5),Infinity);}});
check('Produção, custo e treino das duas classes em ambos os modos',()=>{for(const mode of ['turns','rts'])for(const type of ['antiAirVehicle','missileInfantry']){const g=field(mode);g.credits.blue=500;assert.ok(g.enqueue('blue',type));assert.equal(g.credits.blue,500-TYPES[type].cost);const duration=type==='antiAirVehicle'?3:2;assert.equal(g.trainDuration(type),duration*(mode==='rts'?10:1));g.production('blue',g.trainDuration(type)-.1);assert.equal(g.units.some(u=>u.type===type),false);g.production('blue',.1);assert.ok(g.units.some(u=>u.type===type));}});
check('Precisões: altitude, flares por último, limite 99%, gun sem bônus',()=>{for(const type of ['antiAirVehicle','missileInfantry','helicopterAir'])for(const high of [false,true]){const g=field(),a=g.add('blue',type,5,5),b=g.add('red','helicopter',6,5);b.altitude=high?'high':'low';g.updateVision();const base=Math.min(.99,TYPES[type].accuracy+(type==='helicopterAir'?.05:0)+(high?.1:0));near(g.accuracy(a,b),base);g.shoot(a,b);const p=g.projectiles[0];near(p.accuracy,base/2);assert.equal(p.flareProtected,true);assert.equal(b.flares,2);}const g=field(),a=g.add('blue','helicopterGround',5,5),b=g.add('red','tank',6,5);a.altitude='high';near(g.accuracy(a,b,'agm'),.95);near(g.accuracy(a,b,'gun'),.85);a.level=3;b.level=2;a.suppressed=1;g.add('blue','commander',4,5);near(g.accuracy(a,b,'agm'),.9);});
check('Flares: um consumo por míssil, recarga própria, reposição não limpa recarga',()=>{for(const mode of ['turns','rts']){const g=field(mode),a=g.add('blue','antiAirVehicle',5,5),b=g.add('red','helicopter',6,5);g.updateVision();g.shoot(a,b);assert.equal(b.flares,2);g.shoot(a,b);assert.equal(b.flares,2);assert.equal(g.projectiles[1].flareProtected,false);b.flares=3;if(mode==='turns'){advance(g,20);assert.equal(g.flareReady(b),false);g.beginTurn('blue');assert.equal(g.flareReady(b),false);g.beginTurn('red');}else{a.cooldown=100;b.cooldown=100;advance(g,7.9);assert.equal(g.flareReady(b),false);advance(g,.1);}assert.equal(g.flareReady(b),true);b.flares=0;g.shoot(a,b);assert.equal(g.projectiles.at(-1).flareProtected,false);}});
check('Desvio por flare: sorteio controlado, sem dano, trajetórias congeladas em delta zero',()=>{const g=field(),a=g.add('blue','antiAirVehicle',5,5),b=g.add('red','helicopter',9,5);g.updateVision();g.rng=()=>.6;g.shoot(a,b);const p=g.projectiles[0];assert.equal(p.hit,false);assert.equal(p.deflected,true);assert.equal(p.duration,4/6);advance(g,.2);const state=JSON.stringify([p,b.flares,b.flareCooldown,b.flareUsed]);g.update(0);assert.equal(JSON.stringify([p,b.flares,b.flareCooldown,b.flareUsed]),state);assert.ok(p.trail.length>0);assert.ok(p.x>p.sx);advance(g,1);assert.equal(b.hp,120);assert.ok(g.events.some(e=>e.kind==='blast'&&e.decoy));});
check('Impacto tardio, alvo móvel, alvo morto não troca de alvo; soldado sem bônus antitanque',()=>{const g=field(),s=g.add('blue','missileInfantry',5,5),t=g.add('red','tank',6,5);g.rng=()=>.2;g.updateVision();g.shoot(s,t);advance(g,.2);assert.equal(t.hp,170);advance(g,.3);assert.equal(t.hp,140);const v=g.add('blue','antiAirVehicle',10,10),h=g.add('red','helicopter',14,10),other=g.add('red','helicopter',14,11);h.flares=0;g.shoot(v,h);const p=g.projectiles.at(-1);h.x=15;advance(g,.1);assert.equal(p.tx,15);g.hurt(h,999,null);advance(g,1);assert.equal(other.hp,120);});
check('Altitude: uma ação por turnos; RTS termina segmento e espera 2s sem tiro; cancelar mantém altitude',()=>{const g=field(),h=g.add('blue','helicopter',5,5);assert.ok(g.order(h,'altitude',{altitude:'high'}));assert.equal(h.altitude,'low');assert.equal(h.actionLeft,false);settle(g);assert.equal(h.altitude,'high');assert.equal(g.order(h,'altitude',{altitude:'low'}),false);const r=field('rts'),a=r.add('blue','helicopterAir',5,5);r.order(a,'move',{x:10,y:5});advance(r,.1);assert.ok(a.segment);const endpoint=a.segment.to.x;r.order(a,'altitude',{altitude:'high'});advance(r,.4);assert.equal(a.x,endpoint);assert.equal(a.altitude,'low');advance(r,1.9);assert.equal(a.altitude,'low');r.order(a,'stop');advance(r,1);assert.equal(a.altitude,'low');assert.ok(r.order(a,'altitude',{altitude:'high'}));r.update(0);assert.equal(a.work,0);advance(r,1.9);assert.equal(a.altitude,'low');advance(r,.1);assert.equal(a.altitude,'high');});
check('Manutenção por turnos, somente base aliada viva e baixa altitude; engenheiro não repara voo',()=>{const g=field(),base=g.add('blue','post',5,5),h=g.add('blue','helicopter',6,5),e=g.add('blue','engineer',6,6);h.hp=60;h.flares=1;h.flareUsed=true;assert.equal(g.order(e,'repair',{targetId:h.id}),false);assert.ok(g.order(h,'service',{targetId:base.id}));settle(g);assert.equal(h.hp,84);assert.equal(h.flares,2);assert.equal(h.flareUsed,true);h.actionLeft=true;h.altitude='high';assert.equal(g.order(h,'service',{targetId:base.id}),false);h.altitude='low';base.owner='neutral';assert.equal(g.order(h,'service',{targetId:base.id}),false);base.owner='red';assert.equal(g.order(h,'service',{targetId:base.id}),false);base.owner='blue';base.hp=0;assert.equal(g.order(h,'service',{targetId:base.id}),false);});
check('Manutenção RTS contínua, recarga preservada e interrupção por dano/nova ordem/perda da base',()=>{for(const interruption of ['damage','order','base','destroy']){const g=field('rts'),base=g.add('blue','post',5,5),h=g.add('blue','helicopterAir',6,5);h.hp=30;h.flares=1;h.flareCooldown=8;g.updateVision();assert.ok(g.order(h,'service',{targetId:base.id}));advance(g,3);near(h.hp,102);assert.equal(h.flares,2);near(h.flareCooldown,5);if(interruption==='damage')g.hurt(h,10,null);if(interruption==='order')g.order(h,'stop');if(interruption==='base')base.owner='red';if(interruption==='destroy')g.hurt(base,999,null);const hp=h.hp;advance(g,.1);near(h.hp,hp);assert.equal(h.order.type,'stop');}const g=field('rts'),b=g.add('blue','post',5,5),h=g.add('blue','helicopter',6,5);h.hp=20;h.flares=0;g.order(h,'service',{targetId:b.id});advance(g,9);assert.equal(h.hp,120);assert.equal(h.flares,3);assert.equal(h.pending,false);});
check('IA compra AA só contra voo visível e procura manutenção/altitude',()=>{for(const mode of ['turns','rts']){const g=field(mode);g.turn='red';g.aiEnabled=true;g.credits.red=500;g.add('red','infantry',34,2);g.add('red','infantry',33,2);g.add('blue','helicopter',32,2);g.updateVision();g.aiBuy();assert.equal(g.hq('red').queue[0].type,'antiAirVehicle');g.hq('red').queue=[];g.credits.red=100;g.aiBuy();assert.equal(g.hq('red').queue[0].type,'missileInfantry');const base=g.add('red','post',12,10),h=g.add('red','helicopterGround',13,10);h.hp=50;g.aiAct(h);assert.equal(h.order.type,'service');}const g=field('rts');g.turn='red';const h=g.add('red','helicopterGround',10,10);g.add('blue','tank',12,10);g.updateVision();g.aiAct(h);assert.equal(h.order.type,'altitude');assert.equal(h.job.altitude,'high');});
check('RTS: IA interrompe ataque ferida e altitude alta recua quando surge AA visível',()=>{const g=field('rts'),h=g.add('red','helicopterGround',10,10),t=g.add('blue','tank',12,10),base=g.add('red','post',9,10);g.aiEnabled=true;g.updateVision();g.order(h,'attack',{targetId:t.id});h.hp=45;h.cooldown=100;t.cooldown=100;advance(g,.1);assert.equal(h.order.type,'service');const r=field('rts'),a=r.add('red','helicopterAir',10,10),b=r.add('blue','helicopter',12,10);a.altitude='high';r.aiEnabled=true;r.order(a,'attack',{targetId:b.id});const aa=r.add('blue','antiAirVehicle',11,11);aa.cooldown=100;b.cooldown=100;r.updateVision();advance(r,.1);assert.equal(a.order.type,'altitude');assert.equal(a.job.altitude,'low');});
check('Múltiplas aeronaves: IA busca os dois tipos sem duplicar o lançador barato enquanto falta veículo',()=>{const g=field('rts');g.aiEnabled=true;g.add('red','infantry',34,2);g.add('blue','helicopter',32,2);g.add('blue','helicopterAir',32,3);g.add('red','missileInfantry',33,3);g.updateVision();g.credits.red=100;g.aiBuy();assert.equal(g.hq('red').queue.length,0);g.credits.red=160;g.aiBuy();assert.equal(g.hq('red').queue[0].type,'antiAirVehicle');g.hq('red').queue=[];g.units=g.units.filter(u=>u.type!=='missileInfantry');g.add('red','antiAirVehicle',34,3);g.credits.red=90;g.aiBuy();assert.equal(g.hq('red').queue[0].type,'missileInfantry');});
check('Movimento, cadência, recompensa, produção bloqueada e fragilidade das novas classes',()=>{for(const type of ['antiAirVehicle','missileInfantry']){const g=field('rts'),u=g.add('blue',type,5,5);g.order(u,'move',{x:8,y:5});advance(g,.2);near(u.x,5+TYPES[type].speed*.2);g.order(u,'stop');advance(g,1);const enemy=g.add('red','helicopter',u.x+1,5);enemy.flares=0;enemy.cooldown=100;enemy.hp=enemy.maxHp=1000;g.updateVision();advance(g,.1);const n=g.shotsFired;advance(g,TYPES[type].cooldown-.2);assert.equal(g.shotsFired,n);advance(g,.3);assert.equal(g.shotsFired,n+1);g.hurt(enemy,9999,u);const v=g.add('red',type,20,20),a=g.add('blue','tank',19,20);g.rng=()=>.2;g.shoot(a,v);advance(g,.2);assert.equal(v.hp,TYPES[type].hp-60);const before=g.credits.blue;g.hurt(v,9999,u);assert.equal(g.credits.blue,before+TYPES[type].reward);g.credits.blue=500;g.enqueue('blue',type);for(const p of g.spawnCells('blue',type))if(!g.occupied(p.x,p.y))g.add('blue','tank',p.x,p.y);g.production('blue',g.trainDuration(type));assert.equal(g.hq('blue').queue.length,1);const b=g.units.find(u=>u.type==='tank'&&g.spawnCells('blue',type).some(p=>u.x===p.x&&u.y===p.y));g.units=g.units.filter(u=>u!==b);g.production('blue',.1);assert.equal(g.hq('blue').queue.length,0);}});
check('Probabilidades reproduzíveis: sorteios uniformes controlados e sequência aleatória fixa',()=>{const results=[];for(const mode of ['turns','rts'])for(const type of ['antiAirVehicle','missileInfantry','helicopterAir'])for(const altitude of ['low','high'])for(const flares of [0,3]){const g=field(mode),a=g.add('blue',type,5,5),b=g.add('red','helicopter',6,5);b.altitude=altitude;const base=g.accuracy(a,b),expected=base*(flares?.5:1);let hits=0,deflected=0;for(let i=0;i<2000;i++){b.flares=flares;b.flareUsed=false;b.flareCooldown=0;let draws=0;g.rng=()=>draws++?(1):((i+.5)/2000);g.shoot(a,b);const p=g.projectiles.pop();hits+=Number(p.hit);deflected+=Number(p.deflected);assert.equal(draws,2);assert.equal(p.targetAltitude,altitude);near(p.accuracy,expected);g.events=[];}near(hits/2000,expected);near(deflected/2000,flares?base-expected:0);results.push({mode,type,targetAltitude:altitude,flare:!!flares,shots:2000,hits,deflected,accuracy:expected});}
 fs.mkdirSync('docs/air-defense',{recursive:true});fs.writeFileSync('docs/air-defense/probabilities.json',JSON.stringify(results,null,2)+'\n');
 const snap=seed=>{const g=field();g.rng=ctx.seeded(seed);const a=g.add('blue','antiAirVehicle',5,5),b=g.add('red','helicopter',6,5);const out=[];for(let i=0;i<50;i++){b.flareUsed=false;b.flares=3;g.shoot(a,b);const p=g.projectiles.pop();out.push([p.hit,p.deflected,p.critical]);}return JSON.stringify(out);};assert.equal(snap(19),snap(19));assert.notEqual(snap(19),snap(20));});
console.log(checks+' verificações de defesa aérea concluídas.');
