'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..'),out=path.join(root,'test-output','air-defense');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(root,'public','index.html')).href);
 await page.waitForFunction(()=>antiAirAtlas.naturalWidth===256&&highCloud.naturalWidth===128&&heliAtlas.naturalWidth>0);await page.evaluate(()=>terrainReady);
 const art=async()=>page.evaluate(()=>['blue','red'].flatMap(owner=>['antiAirVehicle','missileInfantry'].map(type=>{const c=document.createElement('canvas');c.width=c.height=96;const p=c.getContext('2d');unitIcon(p,type,48,48,TEAM[owner]);const normal=c.toDataURL();p.clearRect(0,0,96,96);unitIcon(p,type,48,48,TEAM[owner],1,Math.PI/2);return{normal,rotated:c.toDataURL()};})));
 const originals=await art();assert.equal(new Set(originals.map(a=>a.normal)).size,4);originals.forEach(a=>assert.notEqual(a.normal,a.rotated));
 for(const name of ['vehicle-ally','vehicle-enemy','soldier-ally','soldier-enemy','clouds']){const src='data:image/png;base64,'+fs.readFileSync(path.join(root,'assets','Antiaereas',name+'.png')).toString('base64');const p=await page.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();const c=document.createElement('canvas');c.width=c.height=128;const p=c.getContext('2d');p.drawImage(i,0,0);const d=p.getImageData(0,0,128,128).data;return{w:i.width,h:i.height,clear:d.filter((v,k)=>k%4===3&&v===0).length,corners:[d[3],d[511],d[65027],d.at(-1)]};},src);assert.equal(p.w,128);assert.equal(p.h,128);assert.ok(p.clear>5000);assert.deepEqual(p.corners,[0,0,0,0]);}
 console.log('OK quatro sprites distintos, rotação e cinco PNGs 128x128 com alfa real.');
 const fixture=async(mode='rts',map='river')=>page.evaluate(({mode,map})=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation(map,'normal',91,mode);game.aiEnabled=false;paused=true;game.units=[];game.structures=[];game.projectiles=[];game.add('blue','hq',1,20);game.add('red','hq',34,1);game.add('blue','infantry',1,19);game.add('red','infantry',34,2);const h=game.add('blue','helicopterGround',9,19),aa=game.add('blue','antiAirVehicle',6,18),s=game.add('blue','missileInfantry',7,20),h2=game.add('blue','helicopterAir',10,21),enemy=game.add('red','helicopterAir',11,18),ground=game.add('red','tank',12,19),base=game.add('blue','post',8,19);for(const u of game.units){u.cooldown=100;u.reload=0;}game.updateVision();renderer.rebuild();cam.zoom=1;centerCamera(8,19);setSelection([h.id]);return{h:h.id,h2:h2.id,aa:aa.id,s:s.id,enemy:enemy.id,ground:ground.id,base:base.id};},{mode,map});
 for(const mode of ['turns','rts'])for(const device of ['desktop','mobile']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});const flightIds=await fixture(mode);
  assert.match(await page.locator('#unitInfo').textContent(),/Visão: 6 casas/);assert.match(await page.locator('#unitInfo').textContent(),/Míssil ar-terra 5 casas/);
  await page.locator('#altitudeHigh').click();await page.evaluate(()=>{for(let i=0;i<15;i++)game.update(1/30);updateUI();});assert.match(await page.locator('#unitInfo').textContent(),/Visão: 6 casas/);
  await page.evaluate(()=>{for(let i=0;i<18;i++)game.update(1/30);updateUI();renderer.draw(0);});assert.match(await page.locator('#unitInfo').textContent(),/Visão: 15 casas/);assert.match(await page.locator('#unitInfo').textContent(),/Míssil ar-terra 10 casas/);assert.match(await page.locator('#unitInfo').textContent(),/Metralhadora 3 casas/);assert.match(await page.locator('#unitInfo').textContent(),/cobertura terrestre: 1 casa/i);
  if(await page.locator('#infoToggle').getAttribute('aria-expanded')!=='true')await page.locator('#infoToggle').click();await page.locator('#details').scrollIntoViewIfNeeded();assert.equal(await page.locator('#unitInfo').isVisible(),true);
  const layout=await page.evaluate(()=>{const r=$('details').getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>innerWidth,left:r.left,right:r.right};});assert.equal(layout.overflow,false);assert.ok(layout.left>=0&&layout.right<=await page.evaluate(()=>innerWidth));await page.screenshot({path:path.join(out,`flight-${mode}-${device}.png`)});
  await page.evaluate(ids=>{game.get(ids.h).actionLeft=true;updateUI();},flightIds);await page.locator('#altitudeLow').click();await page.evaluate(()=>{for(let i=0;i<15;i++)game.update(1/30);updateUI();});assert.match(await page.locator('#unitInfo').textContent(),/Visão: 15 casas/);await page.evaluate(()=>{for(let i=0;i<18;i++)game.update(1/30);updateUI();});assert.match(await page.locator('#unitInfo').textContent(),/Visão: 6 casas/);assert.match(await page.locator('#unitInfo').textContent(),/Míssil ar-terra 5 casas/);
  await page.evaluate(ids=>{game.get(ids.h2).altitude='high';setSelection([ids.h2]);},flightIds);assert.match(await page.locator('#unitInfo').textContent(),/Míssil ar-ar 11 casas/);
 }
 await page.setViewportSize({width:1440,height:1000});console.log('OK visão e alcance efetivos durante subida/descida, painel desktop/celular nos dois modos offline.');
 let ids=await fixture();assert.equal(await page.locator('[data-recruit]').count(),16);assert.equal(await page.locator('#flightControls').isVisible(),true);assert.match(await page.locator('#unitInfo').textContent(),/Flares: 3\/3 · prontos/);
 await page.evaluate(ids=>setSelection([ids.h,ids.h2]),ids);await page.locator('#altitudeHigh').click();assert.equal(await page.evaluate(ids=>game.get(ids.h).job.type,ids),'altitude');assert.equal(await page.evaluate(ids=>game.get(ids.h2).job.type,ids),'altitude');await page.waitForTimeout(150);assert.equal(await page.evaluate(ids=>game.get(ids.h).work,ids),0);assert.match(await page.locator('#hint').textContent(),/Ordem preparada/);
 await page.locator('#pause').click();await page.waitForFunction(ids=>game.get(ids.h).altitude==='high'&&game.get(ids.h2).altitude==='high',ids);await page.locator('#pause').click();assert.match(await page.locator('#unitInfo').textContent(),/ALTA/);await page.locator('#stop').click();
 console.log('OK altitude em grupo durante pausa, transição de 1 s e indicação ALTA.');
 ids=await fixture();await page.evaluate(ids=>{const h=game.get(ids.h);h.hp=40;h.flares=0;setSelection([h.id]);},ids);await page.locator('#service').click();await page.evaluate(ids=>issueAt(game.get(ids.base)),ids);assert.equal(await page.evaluate(ids=>game.get(ids.h).order.type,ids),'service');await page.locator('#pause').click();await page.waitForFunction(ids=>game.get(ids.h).hp>50,ids);await page.locator('#pause').click();const hp=await page.evaluate(ids=>game.get(ids.h).hp,ids);await page.waitForTimeout(200);assert.equal(await page.evaluate(ids=>game.get(ids.h).hp,ids),hp);await page.locator('#stop').click();assert.equal(await page.evaluate(ids=>game.get(ids.h).order.type,ids),'stop');
 console.log('OK botão Manutenção, instalação adjacente, pausa e cancelamento.');
 ids=await fixture();await page.evaluate(ids=>{const a=game.get(ids.aa),h=game.get(ids.enemy);h.altitude='high';game.rng=()=>.6;game.shoot(a,h);game.update(.1);renderer.consume();renderer.draw(.1);updateUI();},ids);
 const frozen=()=>page.evaluate(()=>JSON.stringify({time:game.time,units:game.units,projectiles:game.projectiles,particles:renderer.particles,texts:renderer.texts}));const before=await frozen();await page.waitForTimeout(250);assert.equal(await frozen(),before);assert.equal(await page.evaluate(()=>game.projectiles[0].deflected),true);assert.ok(await page.evaluate(()=>renderer.particles.some(p=>p.smoke)&&renderer.particles.some(p=>p.flare)));const direction=await page.evaluate(()=>{const p=game.projectiles[0],v=p.trail.at(-1);return Math.abs(p.heading-Math.atan2(p.y-v.y,p.x-v.x));});assert.ok(direction<1e-9);
 await page.locator('#pause').click();await page.waitForFunction(()=>game.projectiles.length===0);await page.locator('#pause').click();assert.equal(await page.evaluate(ids=>{const u=game.get(ids.enemy);return u.hp/u.maxHp;},ids),1);
 console.log('OK direção, chamariz sem dano e congelamento real de projéteis, flares e fumaça.');
 // Compare no mesmo instante ambiental: nuvens/reflexos podem avançar sem qualquer disparo.
 ids=await fixture();const hidden=await page.evaluate(()=>{const time=game.time;game.time+=.1;renderer.draw(0);const before=renderer.canvas.toDataURL();game.time=time;const a=game.add('red','antiAirVehicle',30,3),b=game.add('blue','helicopter',31,3);game.updateVision();game.shoot(a,b);const p=game.projectiles.at(-1);p.owner='red';game.units=game.units.filter(u=>u!==b);game.updateVision();game.update(.1);renderer.consume();renderer.draw(0);return{same:renderer.canvas.toDataURL()===before,smoke:renderer.particles.some(p=>p.smoke)};});assert.ok(hidden.same);assert.equal(hidden.smoke,false);console.log('OK míssil e fumaça ocultos não revelam o inimigo no mesmo instante ambiental.');
 // Capturas com exemplos montados no motor real; terreno de cada cenário preservado.
 for(const map of ['river','desert','mountain','random'])for(const device of ['desktop','mobile']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});ids=await fixture('rts',map);
  await page.evaluate(ids=>{const h=game.get(ids.h),e=game.get(ids.enemy);h.altitude=e.altitude='high';game.rng=()=>.6;game.shoot(game.get(ids.aa),e);game.shoot(game.get(ids.s),e);game.shoot(game.get(ids.h2),e);game.shoot(h,game.get(ids.ground));game.update(.1);game.update(.1);renderer.consume();renderer.draw(.2);setSelection([h.id]);},ids);
  await page.locator('#flightControls').scrollIntoViewIfNeeded();await page.waitForTimeout(60);const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,map:renderer.canvas.clientHeight,controls:document.querySelector('#flightControls').getBoundingClientRect().right<=innerWidth}));assert.equal(layout.overflow,false);assert.ok(layout.map>80&&layout.controls);
  await page.screenshot({path:path.join(out,map+'-'+device+'-paused.png')});
  for(const type of ['antiAirVehicle','missileInfantry']){await page.evaluate(type=>setSelection([game.units.find(u=>u.owner==='blue'&&u.type===type).id]),type);assert.equal(await page.locator('#flightControls').isHidden(),true);assert.equal(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=108;unitIcon(c.getContext('2d'),selectedUnits()[0].type,54,59,TEAM.blue,1.55);return c.toDataURL()===document.querySelector('#portrait').toDataURL();}),true);}
 }
 console.log('OK novos sprites e voo alto nos quatro mapas, desktop/celular; capturas salvas.');
 await page.setViewportSize({width:1440,height:1000});ids=await fixture('turns');await page.locator('#altitudeHigh').click();await page.locator('#pause').click();await page.waitForFunction(ids=>game.get(ids.h).altitude==='high',ids);assert.equal(await page.evaluate(ids=>game.get(ids.h).actionLeft,ids),false);await page.locator('#pause').click();console.log('OK modo por turnos: altitude custa ação e pausa preservada.');
 await page.evaluate(()=>{antiAirAtlas.src='data:image/png;base64,AA==';highCloud.src='data:image/png;base64,AA==';});await page.waitForFunction(()=>antiAirAtlas.complete&&!antiAirAtlas.naturalWidth&&highCloud.complete&&!highCloud.naturalWidth);const fallback=await art();assert.equal(new Set(fallback.map(a=>a.normal)).size,4);fallback.forEach((a,i)=>assert.notEqual(a.normal,originals[i].normal));assert.ok(await page.evaluate(()=>recruitButtons.every(b=>{const c=document.createElement('canvas');c.width=c.height=60;unitIcon(c.getContext('2d'),b.dataset.recruit,30,33,TEAM.blue);return c.toDataURL()===b.querySelector('canvas').toDataURL();})));await page.evaluate(()=>renderer.draw(0));
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('OK alternativas de atlas/nuvens, recrutamento consistente, file:// sem rede ou erro JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
