'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..'),out=path.join(root,'test-output','atmosphere');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.context().setOffline(true);
 await page.goto(pathToFileURL(path.join(root,'public','index.html')).href);await page.waitForFunction(()=>ambientClouds.every(i=>i.naturalWidth===384));await page.evaluate(()=>terrainReady);
 assert.equal(await page.evaluate(()=>settings.graphics),'balanced');await page.locator('#titleSettings').click();assert.equal(await page.locator('#setGraphics option').count(),3);
 for(const value of ['performance','balanced','cinematic']){await page.locator('#setGraphics').selectOption(value);assert.equal(await page.evaluate(()=>settings.graphics),value);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(SETTINGS_KEY)).graphics),value);}
 await page.reload();await page.waitForFunction(()=>ambientClouds.every(i=>i.naturalWidth===384));assert.equal(await page.evaluate(()=>settings.graphics),'cinematic');
 const alpha=await page.evaluate(()=>ambientClouds.map(i=>{const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const p=c.getContext('2d');p.drawImage(i,0,0);const d=p.getImageData(0,0,c.width,c.height).data;return{clear:d.filter((v,k)=>k%4===3&&v===0).length,soft:d.filter((v,k)=>k%4===3&&v>0&&v<255).length};}));alpha.forEach(a=>{assert.ok(a.clear>10000);assert.ok(a.soft>100);});console.log('OK perfis, padrão Equilibrado, persistência e três nuvens com transparência real.');
 const fixture=async(mode='rts',map='river')=>page.evaluate(({mode,map})=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation(map,'normal',91,mode);game.aiEnabled=false;paused=true;game.units=[];game.structures=[];game.projectiles=[];game.add('blue','hq',1,23);game.add('red','hq',34,1);game.add('blue','infantry',2,23);game.add('red','infantry',34,2);const units=['helicopter','helicopterGround','helicopterAir'].map((type,i)=>game.add('blue',type,8+i,19));const enemy=game.add('red','helicopterAir',12,17),aa=game.add('blue','antiAirVehicle',10,17);for(const u of game.units){u.cooldown=100;u.reload=0;}game.updateVision();renderer.rebuild();cam.zoom=1;centerCamera(9,19);setSelection(units.map(u=>u.id));return{units:units.map(u=>u.id),enemy:enemy.id,aa:aa.id};},{mode,map});
 const advance=async seconds=>page.evaluate(seconds=>{for(let t=0;t<seconds-1e-8;t+=STEP){const dt=Math.min(STEP,seconds-t);game.update(dt);renderer.consume();renderer.draw(dt);}updateUI();},seconds);
 let ids=await fixture();await page.locator('#altitudeHigh').click();await advance(.5);const mid=await page.evaluate(ids=>ids.units.map(id=>{const u=game.get(id),p=flightPose(u);return{alt:u.altitude,lift:(u.y-p.y)*CELL,scale:p.scale,label:orderName(u)};}),ids);mid.forEach(p=>{assert.equal(p.alt,'low');assert.ok(Math.abs(p.lift-9)<1e-7);assert.ok(Math.abs(p.scale-1.06)<1e-7);assert.match(p.label,/SUBINDO.*0.5/);});
 const snapshot=()=>page.evaluate(()=>JSON.stringify({time:game.time,units:game.units,projectiles:game.projectiles,ambient:renderer.ambientParticles,particles:renderer.particles}));await page.waitForTimeout(100);const frozen=await snapshot(),pixels=await page.evaluate(()=>{renderer.draw(0);return renderer.canvas.toDataURL();});await page.waitForTimeout(280);assert.ok(await snapshot()===frozen,'Pausa congela o estado');assert.ok(await page.evaluate(()=>renderer.canvas.toDataURL())===pixels,'Pausa congela os pixels');
 await page.screenshot({path:path.join(out,'subindo-pausado.png')});await advance(.5);assert.ok(await page.evaluate(ids=>ids.units.every(id=>game.get(id).altitude==='high'),ids));await page.screenshot({path:path.join(out,'alta.png')});
 // Clique tanto acima do corpo elevado como na casa: mouse real, mesma projeção da renderização.
 const clickAt=async(id,elevated)=>{const p=await page.evaluate(({id,elevated})=>{const u=game.get(id),v=flightPose(u),r=renderer.canvas.getBoundingClientRect();return{x:r.left+((u.x+.5)*CELL-cam.x)*cam.zoom,y:r.top+(((elevated?v.y-.35:u.y)+.5)*CELL-cam.y)*cam.zoom};},{id,elevated});await page.mouse.click(p.x,p.y);assert.equal(await page.evaluate(()=>[...selection][0]),id);};
 await clickAt(ids.units[0],true);await clickAt(ids.units[0],false);
 await page.evaluate(ids=>{game.get(ids.enemy).altitude='high';setSelection([ids.units[2]]);game.updateVision();},ids);const target=await page.evaluate(ids=>{const p=flightPose(game.get(ids.enemy));return{x:p.x,y:p.y-.35};},ids);await page.evaluate(p=>issueAt(p),target);assert.equal(await page.evaluate(ids=>game.get(ids.units[2]).order.targetId,ids),ids.enemy);
 await page.evaluate(ids=>{game.command(ids.units,'stop');setSelection(ids.units);},ids);await page.locator('#altitudeLow').click();await advance(.5);assert.match(await page.evaluate(ids=>orderName(game.get(ids.units[0])),ids),/DESCENDO/);await page.screenshot({path:path.join(out,'descendo-pausado.png')});await advance(.5);assert.ok(await page.evaluate(ids=>ids.units.every(id=>game.get(id).altitude==='low'),ids));console.log('OK elevação 18 px, escala 12%, pausa no meio, seleção e mira elevadas/casa, subida e descida em grupo.');
 // Menus preservam a pausa e o perfil aplica sem recriar o Game.
 const old=await page.evaluate(()=>JSON.stringify(game));await page.locator('#menuButton').click();await page.locator('#titleSettings').click();await page.locator('#setGraphics').selectOption('performance');await page.locator('#settingsBack').click();await page.locator('#titleResume').click();assert.equal(await page.evaluate(()=>paused),true);assert.ok(await page.evaluate(()=>JSON.stringify(game))===old,'Troca de perfil preserva o motor');await page.evaluate(()=>renderer.draw(0));assert.equal(await page.evaluate(()=>renderer.ambientParticles.length),0);
 // Efeito fora da visão não revela terreno. Limites de partículas mesmo após longo uso.
 ids=await fixture('rts','desert');await page.evaluate(()=>{settings.graphics='cinematic';game.terrain.fill('plain');renderer.paintGround();for(const u of game.units.filter(u=>u.owner==='blue'))if(!AIR(u))game.order(u,'move',{x:u.x+6,y:u.y});});await advance(4);assert.ok(await page.evaluate(()=>renderer.ambientParticles.length>0&&renderer.ambientParticles.length<=GRAPHICS.cinematic.particles));
 const conceal=await page.evaluate(()=>{game.visible.blue.fill(false);game.explored.blue.fill(false);renderer.draw(0);const a=renderer.canvas.toDataURL();settings.graphics='performance';renderer.draw(0);return a===renderer.canvas.toDataURL();});assert.ok(conceal);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>reducedMotion);ids=await fixture();await page.evaluate(()=>settings.graphics='cinematic');await advance(.3);assert.equal(await page.evaluate(()=>renderer.ambientParticles.length),0);const still=await page.evaluate(()=>{renderer.draw(0);const a=renderer.canvas.toDataURL();game.time+=2;renderer.draw(0);return a===renderer.canvas.toDataURL();});assert.ok(still);await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>!reducedMotion);console.log('OK perfis ao vivo sem reiniciar, pausa nos menus, névoa, partículas limitadas e movimento reduzido.');
 // Efeito de aeronave na borda da visão usa a casa lógica, sem perder fumaça ao elevar o desenho.
 const edge=await page.evaluate(()=>{game.units=[];game.structures=[];game.projectiles=[];game.terrain.fill('plain');game.add('blue','hq',0,27);game.add('red','hq',35,27);game.add('blue','infantry',5,6);const h=game.add('red','helicopter',5,2);h.y=1.6;h.altitude='high';game.updateVision();setSelection([]);renderer.rebuild();centerCamera(5,3);game.event('smoke',h,{air:true});renderer.consume();renderer.draw(0);const withSmoke=renderer.canvas.toDataURL();renderer.particles=[];renderer.draw(0);const withoutSmoke=renderer.canvas.toDataURL();const t=game.add('blue','lightTank',6,2);t.y=1.6;h.weaponMode='gun';game.shoot(h,t);game.update(STEP);const p=game.projectiles[0],rotations=[],rotate=renderer.ctx.rotate;renderer.ctx.rotate=function(a){rotations.push(a);rotate.call(this,a);};try{renderer.draw(0);}finally{renderer.ctx.rotate=rotate;}return{logical:game.effectVisible(h.x,h.y,true),projected:game.effectVisible(h.x,flightPose(h).y,true),smoke:withSmoke!==withoutSmoke,heading:rotations.at(-1),expected:Math.atan2(18,56),weapon:p.weapon};});assert.equal(edge.logical,true);assert.equal(edge.projected,false);assert.equal(edge.smoke,true);assert.equal(edge.weapon,'gun');assert.ok(Math.abs(edge.heading-edge.expected)<1e-7);console.log('OK fumaça de aeronave na borda da névoa e direção elevada dos traçantes.');
 // Perfis não alteram mapas, produção, combate, IA ou RNG, nos dois modos.
 const comparisons=await page.evaluate(()=>{const results=[];for(const map of Object.keys(MAPS))for(const mode of ['turns','rts']){const states=[];for(const graphics of Object.keys(GRAPHICS)){
  settings.graphics=graphics;game=new Game(map,'normal',117,mode);const h=game.add('blue','helicopterAir',10,19),e=game.add('red','helicopter',12,19);e.flares=0;game.updateVision();game.order(h,'altitude',{altitude:'high'});game.credits.blue=500;game.enqueue('blue','tank');renderer.rebuild();
  for(let i=0;i<180;i++){game.update(STEP);if(i===35)game.order(h,'attack',{targetId:e.id});if(i===90&&mode==='turns')game.endTurn();renderer.consume();renderer.draw(STEP);}
  states.push(JSON.stringify({terrain:game.terrain,units:game.units,structures:game.structures,projectiles:game.projectiles,time:game.time,turn:game.turn,round:game.round,plan:game.plan,aiDecisions:game.aiDecisions,credits:game.credits,shots:game.shotsFired,next:game.rng()}));
 }results.push({map,mode,equal:states.every(s=>s===states[0])});}return results;});assert.ok(comparisons.every(r=>r.equal));fs.writeFileSync(path.join(out,'profile-comparison.json'),JSON.stringify(comparisons,null,2)+'\n');console.log('OK estados e próximo sorteio idênticos entre os três perfis, quatro mapas e ambos os modos.');
 for(const device of ['desktop','mobile'])for(const map of ['river','desert','mountain','random'])for(const graphics of ['performance','balanced','cinematic']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});ids=await fixture('rts',map);await page.evaluate(({ids,graphics})=>{settings.graphics=graphics;game.get(ids.units[1]).altitude='high';game.order(game.get(ids.units[2]),'altitude',{altitude:'high'});setSelection([ids.units[1]]);}, {ids,graphics});await advance(.5);
  const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,map:renderer.canvas.clientHeight,controls:document.querySelector('#flightControls').getBoundingClientRect().right<=innerWidth}));assert.equal(layout.overflow,false);assert.ok(layout.map>80&&layout.controls);await page.screenshot({path:path.join(out,`${map}-${device}-${graphics}.png`)});
 }
 console.log('OK capturas dos três perfis nos quatro mapas, computador e celular.');
 await page.setViewportSize({width:1440,height:1000});ids=await fixture('turns');await page.locator('#altitudeHigh').click();await advance(3.1);assert.ok(await page.evaluate(ids=>ids.units.every(id=>game.get(id).altitude==='high'&&!game.get(id).actionLeft),ids));console.log('OK grupo por turnos: animação antes de concluir cada ordem e custo de uma ação.');
 // Gravação do Canvas real por MediaRecorder nativo, sem dependências ou ffmpeg.
 ids=await fixture();await page.waitForTimeout(100);await page.evaluate(ids=>{settings.graphics='balanced';setSelection([ids.units[1]]);renderer.draw(0);window.recorded=[];window.recorder=new MediaRecorder(renderer.canvas.captureStream(30),{mimeType:'video/webm;codecs=vp9'});recorder.ondataavailable=e=>recorded.push(e.data);recorder.start();game.command([ids.units[1]],'altitude',{altitude:'high'});paused=false;},ids);
 await page.waitForFunction(ids=>game.get(ids.units[1]).altitude==='high',ids);await page.waitForTimeout(400);await page.evaluate(ids=>game.command([ids.units[1]],'altitude',{altitude:'low'}),ids);await page.waitForFunction(ids=>game.get(ids.units[1]).altitude==='low',ids);await page.waitForTimeout(300);
 const video=await page.evaluate(()=>new Promise(resolve=>{recorder.onstop=()=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(recorded,{type:'video/webm'}));};recorder.stop();paused=true;}));const bytes=Buffer.from(video,'base64');assert.ok(bytes.length>10000);assert.equal(bytes.subarray(0,4).toString('hex'),'1a45dfa3');fs.writeFileSync(path.join(out,'altitude.webm'),bytes);
 const decoded=await page.evaluate(video=>new Promise((resolve,reject)=>{const v=document.createElement('video');v.onloadeddata=()=>{v.currentTime=.3;};v.onseeked=()=>{const c=document.createElement('canvas');c.width=120;c.height=80;const q=c.getContext('2d');q.drawImage(v,0,0,120,80);const d=q.getImageData(0,0,120,80).data,colors=new Set();for(let i=0;i<d.length;i+=4)colors.add(d[i]+','+d[i+1]+','+d[i+2]);resolve({width:v.videoWidth,height:v.videoHeight,ready:v.readyState,colors:colors.size});};v.onerror=()=>reject(Error('WebM não decodifica'));v.src='data:video/webm;base64,'+video;}),video);assert.ok(decoded.width>100&&decoded.height>100&&decoded.ready>=2&&decoded.colors>20,JSON.stringify(decoded));
 await page.evaluate(()=>{for(const image of ambientClouds)image.src='data:image/png;base64,AA==';highCloud.src='data:image/png;base64,AA==';});await page.waitForFunction(()=>ambientClouds.every(i=>i.complete&&!i.naturalWidth)&&highCloud.complete&&!highCloud.naturalWidth);await page.evaluate(()=>{settings.graphics='cinematic';game.units.find(AIR).altitude='high';renderer.draw(0);});await page.screenshot({path:path.join(out,'fallback-nuvens.png')});assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('OK gravação WebM, alternativas sem imagens e file:// sem rede ou erros JS.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
