'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/js/engine.js'),'utf8')+'\nObject.assign(this,{Game,TYPES,COLS,ROWS,KEY,DIST,AIR,PLANE:typeof PLANE==="undefined"?undefined:PLANE,WEAPONS});',ctx);
const {Game,TYPES,COLS,ROWS,KEY,DIST,AIR,PLANE}=ctx;
const cases=[];const test=(name,fn)=>cases.push([name,fn]);
function field(mode='rts'){const g=new Game('river','normal',123,mode,{posts:2});g.terrain.fill('plain');g.units=[];g.structures=[];g.projectiles=[];g.mines=[];g.actions=[];g.animation=null;g.aiEnabled=false;g.add('blue','hq',1,94);g.add('red','hq',126,1);g.add('blue','infantry',2,94);g.add('red','infantry',125,1);g.rng=()=>.01;g.updateVision();return g;}
function advance(g,seconds){for(let t=0;t<seconds-1e-8;t+=1/30)g.update(1/30);}
function settle(g){let n=0;while(g.busy&&n++<20000&&!g.winner)g.update(1/30);assert.ok(n<20000,'a ação deve terminar');}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,a+' != '+b);
test('mapa e economia das operações extensas',()=>{const g=new Game();assert.equal(COLS,128);assert.equal(ROWS,96);assert.equal(g.options.posts,24);assert.equal(g.credits.blue,1200);assert.equal(g.income('blue'),45);g.add('blue','post',4,91);assert.equal(g.income('blue'),69);});
test('seis modelos, cargas e preços isolados',()=>{assert.equal(Object.values(TYPES).filter(t=>t.plane).length,6);assert.equal(TYPES.fighterBlue.cost,530);assert.equal(TYPES.multiroleRed.cost,840);assert.ok(TYPES.bomberBlue.speed<TYPES.bomberRed.speed);for(const mode of ['turns','rts']){const g=field(mode),a=g.add('blue','fighterBlue',10,85),b=g.add('red','fighterRed',24,85);assert.equal(a.ammo.jetAam,4);assert.equal(a.ammo.antiRadiation,2);assert.equal(a.flares,6);assert.equal(a.altitude,'high');assert.equal(g.sight(a),12);assert.equal(g.weaponRange(a,'jetAam'),14);assert.equal(g.range(g.add('blue','helicopterGround',15,80),g.add('red','tank',16,80)),5);assert.ok(PLANE(a));assert.ok(AIR(a));}});
test('pista multicélula, catálogo e fila independente',()=>{const g=field(),a=g.add('blue','airportDirt',8,84);assert.equal(g.structureAt(13,85),a);assert.equal(g.structureAt(14,85),undefined);assert.equal(g.findPath(g.add('blue','tank',7,84),{x:9,y:84}),null);assert.equal(g.queueLimit(a),3);g.credits.blue=10000;assert.equal(g.enqueue('blue','fighterBlue'),false);assert.equal(g.enqueue('blue','infantry',a),false);assert.equal(g.enqueue('blue','fighterRed',a),false);for(let i=0;i<3;i++)assert.ok(g.enqueue('blue','fighterBlue',a));const money=g.credits.blue;assert.equal(g.enqueue('blue','fighterBlue',a),false);assert.equal(g.credits.blue,money);g.production('blue',30);const p=g.units.find(PLANE);assert.equal(p.flightState,'grounded');assert.equal(AIR(p),false);assert.equal(p.airportId,a.id);assert.equal(a.queue.length,2);});
test('produção pronta espera vaga, sem cobrança extra',()=>{const g=field(),a=g.add('blue','airportDirt',8,84);g.credits.blue=10000;for(let i=0;i<4;i++){const u=g.add('blue','fighterBlue',8+i,84);u.flightState='grounded';u.airportId=a.id;}assert.ok(g.enqueue('blue','fighterBlue',a));const money=g.credits.blue;g.production('blue',100);assert.equal(a.queue.length,1);assert.equal(g.credits.blue,money);const p=g.units.find(PLANE);g.order(p,'takeoff');advance(g,1);g.production('blue',1);assert.equal(a.queue.length,0);});
test('voo contínuo, pausa e cancelamento sem munição',()=>{const g=field(),p=g.add('blue','fighterBlue',20,75);const start={x:p.x,y:p.y};advance(g,.5);assert.ok(DIST(p,start)>0);const before=JSON.stringify(p);g.update(0);assert.equal(JSON.stringify(p),before);const e=g.add('red','helicopter',24,75);g.updateVision();assert.ok(g.order(p,'attack',{targetId:e.id,salvo:2,weapon:'jetAam'}));g.order(p,'stop');const ammo=p.ammo.jetAam;advance(g,2);assert.equal(p.ammo.jetAam,ammo);assert.ok(DIST(p,start)>0);assert.equal(p.flightState,'patrol');});
test('uma investida, seleção de salva e cobrança só ao disparar',()=>{for(const mode of ['turns','rts']){const g=field(mode),p=g.add('blue','fighterBlue',20,75),e=g.add('red','helicopter',27,75);e.hp=e.maxHp=1000;e.flares=0;p.facing=Math.PI/2;g.add('blue','reconDrone',27,76);g.updateVision();assert.ok(g.order(p,'attack',{targetId:e.id,salvo:2,weapon:'jetAam'}));if(mode==='rts')advance(g,8);else settle(g);assert.equal(p.ammo.jetAam,2);const shots=p.ammo.jetAam;advance(g,2);assert.equal(p.ammo.jetAam,shots);if(mode==='turns'){assert.equal(p.actionLeft,false);const pos=JSON.stringify([p.x,p.y]);advance(g,3);assert.equal(JSON.stringify([p.x,p.y]),pos);}}});
test('segundo disparo não consome munição se o alvo morrer',()=>{const g=field(),p=g.add('blue','fighterBlue',20,75),e=g.add('red','helicopter',22,75);e.hp=1;e.flares=0;p.facing=Math.PI/2;g.updateVision();assert.ok(g.order(p,'attack',{targetId:e.id,salvo:2}));advance(g,5);assert.equal(p.ammo.jetAam,3);});
test('radar do caça detecta helicóptero baixo, sem detectar furtivo',()=>{const g=field(),p=g.add('blue','fighterBlue',30,70),h=g.add('red','helicopter',47,70),s=g.add('red','stealthDrone',47,71);h.altitude='low';g.updateVision();assert.equal(g.radarContact('blue',h),true);assert.equal(g.radarContact('blue',s),false);assert.equal(g.isVisible('blue',s),false);p.flightState='grounded';g.updateVision();assert.equal(g.radarContact('blue',h),false);});
test('antirradiação segue emissão e mantém última posição ao desligar',()=>{const g=field(),p=g.add('blue','fighterBlue',30,70),a=g.add('red','antiAirVehicle',40,70);a.smokeCharges=0;p.weaponMode='antiRadiation';g.updateVision();assert.ok(g.canFire(p,a));g.shoot(p,a);const shot=g.projectiles.at(-1);assert.equal(shot.weapon,'antiRadiation');assert.ok(shot.duration<DIST(p,a)/6);g.setRadar(a,false);g.update(.05);const tx=shot.tx;a.x=43;g.update(.05);assert.equal(shot.tx,tx);assert.equal(shot.radiationLost,true);});
test('interceptação e fumaça usam orçamento defensivo',()=>{const g=field('turns'),p=g.add('blue','fighterBlue',30,70),a=g.add('red','antiAirVehicle',34,70);a.smokeCharges=0;a.reactionReady=true;p.weaponMode='antiRadiation';g.shoot(p,a);g.defendAir();assert.equal(a.reactionReady,false);assert.equal(g.projectiles.length,0);const h=g.add('blue','helicopter',35,70);const before=g.shotsFired;g.defendAir();assert.equal(g.shotsFired,before);g.beginTurn('blue');assert.equal(a.reactionReady,true);a.smokeCharges=2;g.shoot(p,a);assert.equal(a.smokeCharges,1);const smokeShot=g.projectiles.at(-1);g.impact(smokeShot);assert.equal(smokeShot.deflected,true);assert.equal(h.hp,h.maxHp);});
test('contramedidas e veterania sem esquiva duplicada',()=>{const g=field(),p=g.add('blue','fighterBlue',30,70),a=g.add('red','antiAirVehicle',34,70);near(g.planeEvasion(p),.2);p.level=3;near(g.planeEvasion(p),.3);g.shoot(a,p);near(g.projectiles.at(-1).accuracy,g.projectiles.at(-1).accuracyBase*.7*.5);assert.equal(p.flares,5);});
test('construção cooperativa cobra uma vez e pausa com um trabalhador',()=>{const g=field(),a=g.add('blue','engineer',7,85),b=g.add('blue','engineer',7,86);assert.equal(g.buildAirport([a.id],{x:8,y:85}),false);assert.ok(g.buildAirport([a.id,b.id],{x:8,y:85}));assert.equal(g.credits.blue,800);const site=g.structures.find(s=>s.type==='airportSite');advance(g,10);const progress=site.work;g.order(b,'stop');advance(g,4);near(site.work,progress);assert.ok(g.assignAirportWorkers(site,[a.id,b.id]));advance(g,25);assert.equal(site.type,'airportDirt');assert.ok(g.get(a.id)&&g.get(b.id));assert.equal(g.credits.blue>=800,true);});
test('obra em turnos só avança uma etapa por turno',()=>{const g=field('turns'),a=g.add('blue','engineer',7,85),b=g.add('blue','engineer',7,86);assert.ok(g.buildAirport([a.id,b.id],{x:8,y:85}));const site=g.structures.find(s=>s.type==='airportSite');assert.equal(site.work,1);g.assignAirportWorkers(site,[a.id,b.id]);g.progressAirports('blue',1);assert.equal(site.work,1);g.beginTurn('red');g.beginTurn('blue');assert.equal(site.work,2);g.beginTurn('red');g.beginTurn('blue');assert.equal(site.type,'airportDirt');});
test('captura perde fila e destrói pousados, preservando aeronaves em voo',()=>{const g=field('turns'),a=g.add('red','airportDirt',8,84),p=g.add('red','fighterRed',9,84),f=g.add('red','fighterRed',15,84),inf=g.add('blue','infantry',7,84);p.flightState='grounded';p.airportId=a.id;a.queue.push({type:'fighterRed',progress:0});g.updateVision();assert.ok(g.order(inf,'capture',{targetId:a.id}));settle(g);assert.equal(a.owner,'blue');assert.equal(a.queue.length,0);assert.equal(g.get(p.id),undefined);assert.equal(g.get(f.id),f);});
test('manutenção paga somente armas faltantes e respeita doutrina',()=>{const g=field(),a=g.add('blue','airportAsphalt',8,84),p=g.add('blue','multiroleBlue',9,84);p.flightState='grounded';p.airportId=a.id;p.hp=20;p.flares=0;p.ammo.jetAgm=0;const before=g.credits.blue;assert.ok(g.servicePlane(p));assert.equal(g.credits.blue,before-100);advance(g,10);assert.equal(p.hp,p.maxHp);assert.equal(p.flares,6);assert.equal(p.ammo.jetAgm,4);assert.equal(p.flightState,'grounded');assert.equal(g.credits.blue,before-100+45);});
test('bombardeiro externo compra, sai e reutiliza casco e experiência',()=>{const g=field();assert.ok(g.prepareBomber('blue',{bombCommon:4,bombFragment:4,bombIncendiary:4}));assert.equal(g.credits.blue,24);advance(g,60);assert.equal(g.bomberReserve.status,'ready');const p=g.bomberReserve.plane;p.xp=2;p.level=2;g.explored.blue.fill(true);assert.ok(g.launchBomber('blue',{x:12,y:86},{x:20,y:86}));advance(g,60);assert.equal(g.bomberReserve.status,'available');assert.equal(g.units.includes(p),false);assert.equal(g.get(p.id),p);const money=g.credits.blue;assert.ok(g.prepareBomber('blue',{bombCommon:4,bombFragment:4,bombIncendiary:4}));assert.equal(g.credits.blue,money-176);assert.equal(g.bomberReserve.plane.xp,2);});
test('bombas causam área, fogo amigo e incêndio sem acumular',()=>{const g=field(),p=g.add('blue','bomberBlue',20,75),a=g.add('red','infantry',22,75),b=g.add('blue','infantry',23,75),h=g.add('red','helicopter',22,75);const hp=h.hp;g.bombImpact({weapon:'bombCommon',tx:22,ty:75,power:80,hit:true,attackerId:p.id,owner:'blue'});assert.equal(a.hp,20);assert.equal(b.hp,60);assert.equal(h.hp,hp);g.bombImpact({weapon:'bombIncendiary',tx:23,ty:75,power:20,hit:true,attackerId:p.id,owner:'blue'});g.bombImpact({weapon:'bombIncendiary',tx:23,ty:75,power:20,hit:true,attackerId:p.id,owner:'blue'});assert.equal(g.fires.filter(f=>f.x===23&&f.y===75).length,1);});
test('bombas posteriores à saída conservam abates e XP',()=>{const g=field();g.credits.blue=10000;g.prepareBomber('blue',{bombCommon:12,bombFragment:0,bombIncendiary:0});const p=g.bomberReserve.plane;g.bomberReserve.status='available';const e=g.add('red','infantry',22,75);e.hp=1;g.bombImpact({weapon:'bombCommon',tx:22,ty:75,power:80,hit:true,attackerId:p.id,owner:'blue'});assert.equal(p.xp,1);assert.equal(g.stats.blue.kills.infantry,1);});
test('IA constrói aeroporto e respeita limite aéreo',()=>{const g=field();g.aiEnabled=true;g.credits.red=5000;g.aiBuy();assert.ok(g.producers('red').some(s=>s.queue.some(q=>q.type==='engineer')));for(let n=0;n<2;n++){g.production('red',50);g.aiBuy();}const eng=g.units.filter(u=>u.owner==='red'&&u.type==='engineer');assert.ok(eng.length>=2);assert.ok(g.aiAirportPlan());advance(g,100);assert.ok(g.airports('red').length);for(let n=0;n<30;n++){g.aiBuy();g.production('red',100);}assert.ok(g.units.filter(u=>u.owner==='red'&&PLANE(u)).length<=3);});

test('pista cheia libera planejamento e retoma pouso em outro turno',()=>{const g=field('turns'),a=g.add('blue','airportDirt',8,84);for(let i=0;i<4;i++){const p=g.add('blue','fighterBlue',8+i,84);p.flightState='grounded';p.airportId=a.id;}const p=g.add('blue','fighterBlue',18,84);assert.ok(g.order(p,'return'));settle(g);assert.equal(p.pending,false);assert.equal(p.flightJob.type,'return');assert.ok(g.endTurn());});
test('último míssil inicia retorno dentro da ação em turnos',()=>{const g=field('turns'),a=g.add('blue','airportAsphalt',8,84),p=g.add('blue','fighterBlue',18,84),e=g.add('red','helicopter',22,84);p.ammo={jetAam:1,antiRadiation:0};p.facing=Math.PI/2;e.hp=1000;e.flares=0;g.updateVision();assert.ok(g.order(p,'attack',{targetId:e.id,salvo:2}));settle(g);assert.equal(AIR(p),false);assert.equal(p.airportId,a.id);assert.equal(p.flightState,'service');assert.equal(p.actionLeft,false);});
test('cancelamento externo por turnos termina saída sem gastar bombas',()=>{const g=field('turns');g.credits.blue=10000;g.explored.blue.fill(true);g.prepareBomber('blue');g.progressBomber(6);assert.ok(g.launchBomber('blue',{x:12,y:86},{x:20,y:86}));advance(g,.5);const p=g.bomberReserve.plane,cargo=JSON.stringify(p.ammo);assert.ok(g.order(p,'stop'));settle(g);assert.equal(g.bomberReserve.status,'available');assert.equal(JSON.stringify(p.ammo),cargo);assert.equal(g.units.includes(p),false);});
test('radar reproduzível independe de chamadas de visão e perde cobertura',()=>{const a=field(),b=field();for(const g of [a,b]){g.add('red','antiAirVehicle',125,10);g.add('blue','bomberBlue',40,50);g.units.find(u=>u.type==='bomberBlue').flightState='patrol';}for(let i=0;i<12;i++){for(let n=0;n<30;n++)a.updateVision();a.time+=4;b.time+=4;a.advanceRadar(4);b.advanceRadar(4);a.updateVision();b.updateVision();assert.equal(a.radarContact('red',a.units.find(u=>u.type==='bomberBlue')),b.radarContact('red',b.units.find(u=>u.type==='bomberBlue')));}a.setRadar(a.units.find(u=>u.type==='antiAirVehicle'),false);assert.equal(a.radarContact('red',a.units.find(u=>u.type==='bomberBlue')),false);});
test('aviões pousados não esquivam, não usam flares e são alvos terrestres',()=>{const g=field(),a=g.add('blue','airportDirt',8,84),p=g.add('blue','fighterBlue',9,84),m=g.add('red','multiroleRed',15,84);p.flightState='grounded';p.airportId=a.id;m.weaponMode='jetAgm';g.updateVision();assert.ok(g.weapon(m,p));g.shoot(m,p);const shot=g.projectiles.at(-1);near(shot.accuracy,shot.accuracyBase);assert.equal(p.flares,6);assert.equal(g.sight(p),0);});
test('patrulha respeita bordas e deslocamento real sem teletransporte',()=>{const g=field(),p=g.add('blue','fighterBlue',0,0);for(let n=0;n<600;n++){const x=p.x,y=p.y;g.stepPlane(p,1/30);assert.ok(p.x>=0&&p.x<=COLS-1&&p.y>=0&&p.y<=ROWS-1);assert.ok(Math.hypot(p.x-x,p.y-y)<.5);}assert.ok(p.x!==0||p.y!==0);});
test('patrulha sem ação avança somente ao encerrar turno próprio',()=>{const g=field('turns'),p=g.add('blue','fighterBlue',20,75);const pos=JSON.stringify([p.x,p.y]),center=JSON.stringify([p.patrol.x,p.patrol.y]);advance(g,4);assert.equal(JSON.stringify([p.x,p.y]),pos);assert.ok(g.endTurn());settle(g);assert.ok(!g.busy);assert.equal(g.turn,'red');advance(g,1);assert.equal(p.actionLeft,true);assert.ok(Math.abs(p.x-20)<.4&&Math.abs(p.y-75)<.4);assert.equal(JSON.stringify([p.patrol.x,p.patrol.y]),center);});
test('destruição de aeroporto perde aviões, fila e obra sem reembolso',()=>{const g=field(),a=g.add('blue','airportDirt',8,84),p=g.add('blue','fighterBlue',9,84),enemy=g.add('red','tank',20,84);p.flightState='grounded';p.airportId=a.id;g.enqueue('blue','fighterBlue',a);const money=g.credits.blue;g.hurt(a,999,enemy);assert.equal(g.get(p.id),undefined);assert.equal(g.get(a.id),undefined);assert.equal(g.credits.blue,money);});
test('sem saldo manutenção repara sem munição, mantendo XP e vida modificada',()=>{const g=field(),a=g.add('blue','airportDirt',8,84),p=g.add('blue','multiroleBlue',9,84);p.flightState='grounded';p.airportId=a.id;p.maxHp=220;p.level=3;p.xp=7;p.hp=20;p.ammo.jetAgm=0;p.flares=0;g.credits.blue=0;assert.ok(g.servicePlane(p));g.progressPlaneService('blue',20);assert.equal(p.hp,220);assert.equal(p.ammo.jetAgm,0);assert.equal(p.xp,7);assert.equal(g.credits.blue,0);});
test('nova missão descarta sobras apenas com ação explícita e cobra casco após morte',()=>{const g=field();g.credits.blue=10000;g.prepareBomber('blue');const p=g.bomberReserve.plane;g.bomberReserve.status='available';const money=g.credits.blue;assert.equal(g.prepareBomber('blue',{bombCommon:12}),false);assert.equal(g.credits.blue,money);assert.ok(g.prepareBomber('blue',{bombCommon:12},{discard:true}));assert.equal(g.credits.blue,money-96);p.hp=0;g.bomberReserve.status='destroyed';assert.ok(g.prepareBomber('blue',{bombCommon:12}));assert.equal(g.credits.blue,money-96-1144);assert.notEqual(g.bomberReserve.plane.id,p.id);});

test('transferência próxima alcança destino sem bloquear turnos',()=>{const g=field('turns'),p=g.add('blue','fighterBlue',20,75);p.facing=0;assert.ok(g.order(p,'patrol',{x:20,y:75}));advance(g,20);assert.equal(g.busy,false);assert.equal(p.flightState,'patrol');});
test('bombardeiro externo mantém missão única até sair',()=>{const g=field();g.credits.blue=10000;g.explored.blue.fill(true);assert.ok(g.prepareBomber('blue'));g.progressBomber(60);assert.ok(g.launchBomber('blue',{x:12,y:85},{x:20,y:85}));const p=g.bomberReserve.plane;advance(g,1);const job=p.flightJob,ammo=JSON.stringify(p.ammo);assert.equal(g.order(p,'bombRun',{start:{x:25,y:85},end:{x:33,y:85}}),false);assert.equal(p.flightJob,job);assert.equal(JSON.stringify(p.ammo),ammo);});
test('IA busca todo o canto permitido para construir pista',()=>{for(const mode of ['turns','rts']){const g=field(mode);g.turn='red';g.terrain.fill('forest');for(let y=2;y<4;y++)for(let x=112;x<118;x++)g.terrain[KEY(x,y)]='plain';g.add('red','engineer',118,2);g.add('red','engineer',118,3);g.credits.red=10000;assert.ok(g.aiAirportPlan());assert.ok(g.structures.some(s=>s.type==='airportSite'));if(mode==='rts')advance(g,31);else for(let i=0;i<3;i++){g.round++;g.beginTurn('red');}assert.equal(g.airports('red').length,1);}});
test('busca de alcance mantém menor custo e limite de movimento',()=>{const g=field(),u=g.add('blue','tank',10,10),target={x:20,y:20};assert.equal(g.pathCost(u,g.pathToRange(u,target,2)),18);for(let y=10;y<=18;y++)g.terrain[KEY(10,y)]='road';for(let x=10;x<=20;x++)g.terrain[KEY(x,18)]='road';assert.equal(g.pathCost(u,g.pathToRange(u,target,2,0,9)),9);assert.equal(g.pathToRange(u,target,2,0,8.9),null);});
let ran=0;for(const [name,fn]of cases){if(process.argv[2]&&!name.includes(process.argv[2]))continue;fn();ran++;console.log('OK '+name);}console.log(ran+' verificações de aviação concluídas.');
