// Chrome real, file:// e rede desligada. Comandos de aviação, sprites, campanha e tela pequena.
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright-core');
const root=path.join(__dirname,'..'),art=path.join(__dirname,'artifacts');
(async()=>{fs.mkdirSync(art,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(root,'public','index.html')).href);
await page.waitForFunction(()=>Object.values(planeImages).every(i=>i.complete&&i.naturalWidth));
const sprites=await page.evaluate(()=>Object.entries(planeImages).map(([type,im])=>{const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.drawImage(im,0,0);const d=x.getImageData(0,0,256,256).data;let count=0;for(let i=3;i<d.length;i+=4)if(d[i]>0)count++;return{type,count,corner:d[3],url:c.toDataURL()};}));
assert.equal(new Set(sprites.map(s=>s.url)).size,6);for(const s of sprites){assert.ok(s.count>3000);assert.equal(s.corner,0);}
await page.evaluate(()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation('river','normal',123,'rts',{posts:2});paused=true;game.aiEnabled=false;game.terrain.fill('plain');game.credits.blue=10000;const a=game.add('blue','airportDirt',8,84),p=game.add('blue','fighterBlue',9,84);p.flightState='grounded';p.airportId=a.id;game.updateVision();setSelection([a.id]);centerCamera(10,84);updateUI();});
assert.equal(await page.locator('.recruit:visible').count(),2);assert.match(await page.locator('#queueCount').textContent(),/0 \/ 3/);assert.match(await page.locator('#queue').textContent(),/1 \/ 4/);
await page.locator('[data-recruit="fighterBlue"]').click();assert.match(await page.locator('#queueCount').textContent(),/1 \/ 3/);
await page.evaluate(()=>setSelection([game.units.find(PLANE).id]));assert.equal(await page.locator('#flightControls').isVisible(),false);assert.equal(await page.locator('#planeControls').isVisible(),true);
await page.locator('#planeSalvo').selectOption('2');await page.locator('#planeTakeoff').click();assert.equal(await page.evaluate(()=>game.units.find(PLANE).flightJob.type),'transfer');
const before=await page.evaluate(()=>JSON.stringify([game.units.find(PLANE).x,game.units.find(PLANE).y]));await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>JSON.stringify([game.units.find(PLANE).x,game.units.find(PLANE).y])),before);
await page.evaluate(()=>{for(let n=0;n<180;n++)game.update(1/30);game.updateVision();updateUI();});
await page.locator('#infoToggle').click();assert.match(await page.locator('#unitInfo').textContent(),/esquiva 20%/);
await page.evaluate(()=>{const p=game.units.find(PLANE);p.x=30;p.y=70;p.facing=Math.PI/2;game.setPatrol(p);const a=game.add('red','antiAirVehicle',38,70);game.terrain[KEY(38,70)]='forest';a.smokeCharges=0;game.updateVision();p.weaponMode='antiRadiation';setSelection([p.id]);$('planeWeapon').value='antiRadiation';mode='attack';issueAt({x:38,y:70});});
assert.equal(await page.evaluate(()=>game.units.find(PLANE).flightJob.type),'strike','emissão sem visão terrestre pode ser selecionada');assert.equal(await page.evaluate(()=>game.isVisible('blue',game.units.find(u=>u.owner==='red'&&u.type==='antiAirVehicle'))),false);
await page.evaluate(()=>{game.order(game.units.find(PLANE),'stop');setSelection([game.hq('blue').id]);game.explored.blue.fill(true);updateUI();});
await page.locator('#bomberPanel summary').click();await page.locator('#bombCommon').fill('6');await page.locator('#bombFragment').fill('3');await page.locator('#bombIncendiary').fill('3');await page.locator('#prepareBomber').click();
assert.equal(await page.evaluate(()=>game.bomberReserve.status),'preparing');await page.evaluate(()=>{game.progressBomber(60);updateUI();});await page.locator('#launchBomber').click();
await page.locator('#lineX1').fill('13');await page.locator('#lineY1').fill('10');await page.locator('#lineX2').fill('21');await page.locator('#lineY2').fill('10');await page.locator('#confirmBombLine').click();assert.equal(await page.evaluate(()=>game.bomberReserve.status),'flying');
await page.evaluate(()=>{setSelection([game.bomberReserve.plane.id]);centerCamera(game.bomberReserve.plane.x,game.bomberReserve.plane.y);updateUI();});
await page.screenshot({path:path.join(art,'aviation-bomber-desktop.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{setSelection([game.units.find(u=>u.type==='fighterBlue').id]);updateUI();});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(art,'aviation-plane-mobile.png')});
await page.setViewportSize({width:375,height:667});await page.evaluate(()=>{setSelection([game.hq('blue').id]);updateUI();});const small=await page.locator('#commandBar').boundingBox();assert.ok(small.y>=0&&small.y+small.height<=667);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(art,'aviation-qg-mobile.png')});await page.setViewportSize({width:1440,height:1000});const transform=await page.evaluate(()=>{const c=$('minimap'),r=c.getBoundingClientRect(),t=miniTransform(c),point={x:110,y:90};return pointerPosition({clientX:r.left+(t.ox+(point.x+.5)*t.s)/c.width*r.width,clientY:r.top+(t.oy+(point.y+.5)*t.s)/c.height*r.height},c);});assert.ok(Math.abs(transform.x-110)<1e-6&&Math.abs(transform.y-90)<1e-6);
assert.equal(await page.evaluate(()=>('ground' in renderer)),false,'sem bitmap do mapa inteiro');
const measurement=await page.evaluate(()=>{const sample=(fn,n)=>{const out=[];for(let i=0;i<n;i++){const t=performance.now();fn();out.push(performance.now()-t);}out.sort((a,b)=>a-b);return{median:out[Math.floor(n/2)],max:out.at(-1),samples:n};};const generation=sample(()=>new Game('river','normal',44,'rts'),3);game=new Game('river','normal',44,'rts',{posts:2});game.aiEnabled=false;game.terrain.fill('plain');game.units=[];game.structures=[];game.mines=[];game.add('blue','hq',1,94);game.add('red','hq',126,1);for(let i=0;i<64;i++)game.add(i<32?'blue':'red','tank',5+i%16*3,10+Math.floor(i/16)*10);for(let i=0;i<8;i++)game.add(i<4?'blue':'red',i<4?'fighterBlue':'fighterRed',20+i*8,60);game.updateVision();renderer.rebuild();centerCamera(30,30);const path=sample(()=>game.findPath(game.units[0],{x:120,y:85}),5),update=sample(()=>game.update(1/30),30),draw=sample(()=>renderer.draw(0),20),aiUpdate=sample(()=>{game.aiEnabled=true;game.aiClock=0;game.update(1/30);},5);return{generation,path,update,draw,aiUpdate,units:game.units.length,viewport:[innerWidth,innerHeight],browser:navigator.userAgent};});
fs.writeFileSync(path.join(art,'aviation-performance.json'),JSON.stringify(measurement,null,2)+'\n');console.log('Medições reais (ms): '+JSON.stringify(measurement));
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('OK seis sprites, aeroporto, comandos, salva, emissões, bombardeiro, mobile, minimapa e file:// offline.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
