'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(__dirname,'..','public','index.html')).href);await page.evaluate(()=>terrainReady);
 for(const mode of ['turns','rts']){
 await page.evaluate(mode=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation('river','normal',17,mode);paused=true;game.aiEnabled=false;game.terrain.fill('plain');game.units=[];game.structures=[];game.memory.blue.clear();game.mines=[];game.add('blue','hq',1,94);game.add('red','hq',126,1);game.add('blue','infantry',2,94);game.add('red','infantry',125,1);const p=game.add('blue','post',40,40);game.credits.blue=10000;game.updateVision();settings.graphics='performance';cam.zoom=.35;centerCamera(64,48);renderer.rebuild();setSelection([p.id]);},mode);await page.evaluate(()=>renderer.groundReady);
 await page.locator('[data-recruit="infantry"]').click();await page.evaluate(()=>{game.production('blue',game.trainDuration('infantry')*.8);updateUI();});await page.locator('[data-recruit="tank"]').click();await page.locator('[data-recruit="infantry"]').click();assert.match(await page.locator('#queueStatus').textContent(),/Infantaria \u00d72/);assert.match(await page.locator('#queue').textContent(),/Tanque.*\u00d71/);assert.equal(await page.locator('#queueCount').textContent(),'3 / 5');await page.locator('[data-recruit="infantry"]').click();await page.locator('[data-recruit="infantry"]').click();assert.equal(await page.locator('#queueCount').textContent(),'5 / 5');assert.ok(await page.locator('[data-recruit="infantry"]').isDisabled());
 const exit=await page.evaluate(()=>{const p=selectedProducer();for(const cell of game.spawnCells('blue','infantry',p))game.add('blue','tank',cell.x,cell.y);const money=game.credits.blue;game.production('blue',game.trainDuration('infantry'));updateUI();return{money,after:game.credits.blue,count:p.queue.length,progress:p.queue.find(q=>q.type==='tank').progress};});assert.equal(exit.money,exit.after);assert.equal(exit.count,5);assert.equal(exit.progress,0);assert.match(await page.locator('#queueStatus').textContent(),/Infantaria \u00d74.*Sa\u00edda bloqueada/);
 const vision=await page.evaluate(()=>{game.units=[];game.structures=[];game.memory.blue.clear();game.add('blue','hq',1,94);game.add('red','hq',126,1);game.add('blue','post',60,60);game.add('blue','recon',40,40);game.add('blue','antiAirVehicle',30,30);const h=game.add('red','helicopter',100,80);h.altitude='high';game.terrain[KEY(44,40)]='forest';game.updateVision();setSelection([]);renderer.draw(0);renderer.drawMini();const masks=renderer.visionMask,ground=renderer.terrainView,chunks=renderer.groundChunks,mini=renderer.miniTerrain;const sample=(name,x,y)=>Array.from(masks[name].getContext('2d').getImageData(x,y,1,1).data);const checks={dark:sample('field',100,80),mini:sample('mini',100,80),lit:sample('field',68,60),outside:sample('field',69,60),cover:sample('field',44,40),radar:game.radarContact('blue',h),sky:game.sky.blue[KEY(44,40)]};const before=masks.field.toDataURL();game.add('blue','infantry',100,80);game.updateVision();renderer.draw(0);renderer.drawMini();checks.changed=before!==masks.field.toDataURL();checks.litAfter=sample('field',100,80)[3]===0;checks.caches=ground===renderer.terrainView&&chunks===renderer.groundChunks&&mini===renderer.miniTerrain;checks.size=[masks.field.width,masks.field.height];let uploads=0;const contexts=[masks.field.getContext('2d'),masks.mini.getContext('2d')],originals=contexts.map(c=>c.putImageData);contexts.forEach((c,i)=>c.putImageData=function(...args){uploads++;return originals[i].apply(this,args);});const x=cam.x;try{for(let i=0;i<4;i++){cam.x+=1;renderer.draw(0);renderer.drawMini();}checks.staticMask=uploads===0;}finally{cam.x=x;contexts.forEach((c,i)=>c.putImageData=originals[i]);}return checks;});assert.equal(vision.dark[3],175);assert.ok(vision.dark.slice(0,3).every((v,i)=>Math.abs(v-[16,37,45][i])<=1));assert.equal(vision.mini[3],153);assert.ok(vision.mini.slice(0,3).every((v,i)=>Math.abs(v-[17,35,47][i])<=1));assert.equal(vision.lit[3],0);assert.equal(vision.outside[3],175);assert.equal(vision.cover[3],175);assert.ok(vision.radar&&vision.sky&&vision.changed&&vision.litAfter&&vision.caches&&vision.staticMask);assert.deepEqual(vision.size,[128,96]);console.log('OK '+mode+': batch panel, blocked exits, fog/radar/cover and stable terrain caches');
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{setSelection([game.hq('blue').id]);cam.zoom=.35;centerCamera(40,40);renderer.draw(0);updateUI();});assert.equal(await page.locator('#queueCount').textContent(),'0 / 5');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('OK mobile and offline');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
