// Controles reais no Google Chrome, com rede desligada.
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.context().setOffline(true);
 await page.goto(pathToFileURL(path.join(__dirname,'..','index.html')).href);assert.equal(await page.title(),'War Grid — Fronteiras por Turnos');assert.equal(await page.locator('#setup').evaluate(e=>e.open),true);
 await page.locator('#seed').fill('17');await page.getByRole('button',{name:'Iniciar operação'}).click();assert.equal(await page.locator('#speed').textContent(),'1×');assert.equal(await page.locator('#status').textContent(),'Seu turno');
 const snapshot=()=>page.evaluate(()=>JSON.stringify({army:game.units.map(u=>[u.x,u.y,u.hp]),credits:game.credits,decisions:game.aiDecisions,round:game.round}));const initial=await snapshot();await page.waitForTimeout(900);assert.equal(await snapshot(),initial);
 async function point(x,y){const r=await page.locator('#battlefield').boundingBox();return{x:r.x+(x+.5)*r.width/18,y:r.y+(y+.5)*r.height/14};}
 async function click(x,y,button='left'){const p=await point(x,y);await page.mouse.click(p.x,p.y,{button});}
 async function settled(){await page.waitForFunction(()=>!game.busy&&game.turn==='blue',null,{timeout:20000});}
 async function fixture(type='infantry') {return page.evaluate(type=>{newOperation('desert','normal',19);game.aiEnabled=false;game.terrain.fill('plain');game.units=[];game.structures=[];game.mines=[];game.add('blue','hq',0,13);game.add('red','hq',17,0);game.add('red','infantry',17,1);const unit=game.add('blue',type,4,7);game.rng=()=>.2;game.updateVision();renderer.rebuild();setSelection([unit.id]);return unit.id;},type);}
 const a=await point(.4,9.4),b=await point(4.5,12.5);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>selection.size),7);await page.keyboard.press('Control+1');assert.equal(await page.evaluate(()=>groups[0].length),7);await click(9,12);await page.keyboard.press('1');assert.equal(await page.evaluate(()=>selection.size),7);
 await fixture();assert.match(await page.locator('#unitInfo').textContent(),/Movimento 3 \/ 3/);await click(5,7,'right');await settled();assert.equal(await page.evaluate(()=>selectedUnits()[0].moveLeft),2);await page.keyboard.press('s');assert.equal(await page.evaluate(()=>selectedUnits()[0].actionLeft),false);assert.equal(await page.locator('#move').isDisabled(),true);
 await page.locator('[data-recruit="infantry"]').click();assert.match(await page.locator('#queueStatus').textContent(),/1 turno/);await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>game.hq('blue').queue[0].progress),0);await page.locator('#endTurn').click();await settled();await page.waitForFunction(()=>document.querySelector('#clock').textContent==='Rodada 2');assert.equal(await page.evaluate(()=>game.hq('blue').queue.length),0);assert.equal(await page.evaluate(()=>selectedUnits()[0].moveLeft),3);assert.equal(await page.locator('#income').textContent(),'+15');
 await page.keyboard.press('Enter');await settled();assert.equal(await page.evaluate(()=>game.round),3);console.log('OK planejamento, seleção, grupos, movimento, aguardar, Enter e treinamento por turno');
 await fixture('antitank');await page.evaluate(()=>{game.add('red','tank',6,7);game.updateVision();});await page.keyboard.press('a');assert.equal(await page.evaluate(()=>mode),'attack');assert.equal(await page.locator('#attackMove').getAttribute('aria-pressed'),'true');await click(6,7);await settled();assert.equal(await page.evaluate(()=>game.units.find(u=>u.type==='tank').hp),80);assert.equal(await page.locator('#attackMove').isDisabled(),true);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>game.shotsFired),1);
 await fixture('machinegun');await page.evaluate(()=>{game.add('red','infantry',5,7);game.updateVision();});await click(5,7,'right');await settled();assert.equal(await page.evaluate(()=>game.shotsFired),3);console.log('OK ataque manual, antitanque e rajada por uma ação');
 await fixture('artillery');await page.evaluate(()=>{game.add('red','tank',6,7);game.updateVision();});await page.locator('#pause').click();await click(6,7,'right');assert.equal(await page.locator('#endTurn').isDisabled(),true);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>game.shotsFired),0);await page.keyboard.press('p');await page.waitForFunction(()=>game.projectiles.length>0);await page.keyboard.press('p');const projectile=await page.evaluate(()=>game.projectiles[0].elapsed);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>game.projectiles[0].elapsed),projectile);await page.keyboard.press('p');await settled();assert.equal(await page.locator('#move').isDisabled(),true);assert.equal(await page.evaluate(()=>game.units.find(u=>u.type==='tank').hp),100);
 await page.locator('#help').click();assert.equal(await page.locator('#manual').evaluate(e=>e.open),true);await page.locator('#closeHelp').click();console.log('OK artilharia, pausa de animação, bloqueio de ações e manual');
 await fixture();await page.evaluate(()=>{game.add('neutral','post',5,7);game.updateVision();});await click(5,7,'right');await settled();assert.equal(await page.evaluate(()=>game.structureAt(5,7).owner),'blue');
 await fixture('engineer');await page.evaluate(()=>{game.add('blue','tank',5,7).hp=90;game.updateVision();});await page.keyboard.press('r');await click(5,7);await settled();assert.equal(await page.evaluate(()=>game.units.find(u=>u.type==='tank').hp),114);
 await fixture();await page.locator('#build').click();await settled();assert.equal(await page.evaluate(()=>game.structureAt(4,7).type),'post');console.log('OK captura, reparo e construção por ação');
 await page.evaluate(()=>{newOperation('river','normal',21);speed=2;});const redBefore=await page.evaluate(()=>game.units.filter(u=>u.owner==='red').map(u=>[u.x,u.y]));await page.locator('#endTurn').click();assert.equal(await page.locator('#endTurn').isDisabled(),true);await page.keyboard.press('p');const frozen=await snapshot();await page.waitForTimeout(250);assert.equal(await snapshot(),frozen);await page.keyboard.press('p');await settled();assert.notDeepEqual(await page.evaluate(()=>game.units.filter(u=>u.owner==='red').map(u=>[u.x,u.y])),redBefore);assert.equal(await page.evaluate(()=>game.round),2);await page.waitForFunction(()=>document.querySelector('#status').textContent==='Seu turno');
 await page.locator('#endTurn').click();await page.locator('#newGame').click();await page.getByRole('button',{name:'Iniciar operação'}).click();assert.equal(await page.evaluate(()=>game.round),1);assert.equal(await page.evaluate(()=>game.turn),'blue');assert.equal(await page.evaluate(()=>game.busy),false);console.log('OK turno da IA, pausa, retorno do controle e reinício durante execução');
 for(const viewport of [{width:1440,height:1000},{width:1280,height:800},{width:768,height:1024},{width:390,height:844},{width:375,height:667}]){await page.setViewportSize(viewport);await page.waitForTimeout(100);const layout=await page.evaluate(()=>{const c=document.querySelector('#battlefield').getBoundingClientRect(),d=document.querySelector('.dock').getBoundingClientRect(),e=document.querySelector('#endTurn').getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>innerWidth,canvasBottom:c.bottom,dockTop:d.top,buttonRight:e.right,width:innerWidth,buttonTop:e.top};});assert.equal(layout.overflow,false,JSON.stringify(viewport));assert.ok(layout.canvasBottom<=layout.dockTop+1,JSON.stringify({viewport,layout}));assert.ok(layout.buttonRight<=layout.width&&layout.buttonTop>=0);}
 console.log('OK cinco layouts, incluindo celular baixo; comandos e mapa acessíveis');
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{setSelection(game.units.filter(u=>u.owner==='blue'&&u.type==='infantry').map(u=>u.id));});if(process.env.QA_SCREENSHOT)await page.screenshot({path:process.env.QA_SCREENSHOT,type:'jpeg',quality:70,fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('OK sem erros JavaScript ou acesso à rede; jogo offline');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
