'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c=vm.createContext({console});vm.runInContext(fs.readFileSync('public/js/engine.js','utf8')+'\nthis.api={Game,TYPES,COLS,ROWS,KEY,AIR,PLANE};',c);const {Game,TYPES,COLS,ROWS,KEY,AIR,PLANE}=c.api;
function field(mode='rts'){const g=new Game('river','normal',17,mode);g.terrain.fill('plain');g.units=[];g.structures=[];g.mines=[];g.aiEnabled=false;g.add('blue','hq',1,94);g.add('red','hq',126,1);g.credits.blue=g.credits.red=5000;return g;}
let checks=0;function check(name,fn){try{fn();checks++;console.log('OK '+name);}catch(e){console.error(name,e);process.exitCode=1;}}
check('default army has 1145 paid points, free HQ/commander and independent battle credits',()=>{for(const mode of ['turns','rts']){const g=new Game('river','normal',17,mode);assert.equal(g.units.filter(u=>u.owner==='blue').length,12);assert.equal(g.units.filter(u=>u.owner==='blue'&&u.type==='engineer').length,2);assert.equal(g.units.filter(u=>u.owner==='blue'&&u.type==='commander').length,1);assert.equal(g.credits.blue,1200);assert.equal(Object.entries(g.initialArmies.blue).reduce((n,[t,q])=>n+TYPES[t].cost*q,0),1145);}});
check('custom armies: planes patrol high/full, empty and maximum armies spawn safely',()=>{for(const mode of ['turns','rts']){const g=new Game('river','normal',71,mode,{}, {blue:'offensive'}, {blue:{fighterBlue:1,infantry:2,engineer:2},red:{}});const p=g.units.find(u=>u.type==='fighterBlue');assert.ok(p&&AIR(p));assert.equal(p.flightState,'patrol');assert.equal(p.altitude,'high');assert.equal(p.hp,135);assert.equal(JSON.stringify(p.ammo),JSON.stringify(TYPES.fighterBlue.ammo));assert.equal(g.units.filter(u=>u.owner==='red').length,1);assert.equal(g.credits.blue,1200);for(const army of [{},{infantry:24}]){const h=new Game('river','normal',71,mode,{}, {},{blue:army,red:army});for(const owner of ['blue','red']){const units=h.units.filter(u=>u.owner===owner);assert.equal(units.length,(army.infantry||0)+1);const cells=units.map(u=>u.x+','+u.y+','+AIR(u));assert.equal(new Set(cells).size,cells.length);assert.ok(units.every(u=>!h.structureAt(u.x,u.y)));}}}});
check('invalid imported armies use defaults; enemy army and map are seed reproducible',()=>{for(const army of [{infantry:25},{fighterRed:1},{infantry:-1},{infantry:1.5},{bomberBlue:1},{commander:1},[]]){const g=new Game('river','normal',71,'rts',{}, {},{blue:army});assert.equal(g.units.filter(u=>u.owner==='blue').length,12);}const a=new Game('river','normal',71,'rts',{}, {},{blue:{}}),b=new Game('river','hard',71,'rts',{}, {},{blue:{infantry:24}});assert.equal(JSON.stringify(a.terrain),JSON.stringify(b.terrain));assert.equal(JSON.stringify(a.mines),JSON.stringify(b.mines));assert.equal(JSON.stringify(a.initialArmies.red),JSON.stringify(b.initialArmies.red));const cost=Object.entries(a.initialArmies.red).reduce((n,[t,q])=>n+TYPES[t].cost*q,0);assert.ok(cost<=1200&&cost>1150);assert.equal(a.initialArmies.red.engineer,2);});
check('airport geometry accepts all land, reserves both ends and rejects conflicts',()=>{const g=field(),cell={x:50,y:50};for(const terrain of ['plain','field','road','bridge','forest','hedge','hill','mountain']){g.terrain.fill(terrain);const info=g.airportBuildInfo(cell);assert.ok(info.valid,terrain);assert.equal(info.duration,['forest','hedge','hill','mountain'].includes(terrain)?60:30);assert.equal(info.approaches.length,8);}g.terrain.fill('plain');for(const p of [{x:1,y:50},{x:121,y:50},{x:50,y:95}])assert.equal(g.airportBuildSite(p),false);g.terrain[KEY(48,50)]='river';assert.equal(g.airportBuildSite(cell),false);g.terrain.fill('plain');const post=g.add('neutral','post',57,50);assert.equal(g.airportBuildSite(cell),false);g.structures=g.structures.filter(s=>s!==post);g.mines.push({x:48,y:50});assert.equal(g.airportBuildSite(cell),false);g.mines=[];const u=g.add('blue','infantry',48,50);assert.ok(g.airportBuildSite(cell));u.x=50;assert.equal(g.airportBuildSite(cell),false);});
check('30/60-second and 3/6-turn works only level eight end cells on completion',()=>{for(const mode of ['turns','rts'])for(const rough of [false,true]){const g=field(mode),p={x:50,y:50};if(rough)for(let y=50;y<52;y++)for(let x=48;x<58;x++)g.terrain[KEY(x,y)]='forest';const a=g.add('blue','engineer',49,50),b=g.add('blue','engineer',50,49);assert.ok(g.buildAirport([a.id,b.id],p));const site=g.structureAt(50,50),duration=rough?60:30;assert.equal(site.buildDuration,duration);assert.equal(g.credits.blue,4600);if(mode==='rts'){g.progressAirports('blue',duration-.1);assert.equal(site.type,'airportSite');b.order={type:'stop'};const progress=site.work;g.progressAirports('blue',100);assert.equal(site.work,progress);g.assignAirportWorkers(site,[a.id,b.id]);g.progressAirports('blue',.1);}else{for(let n=1;n<duration/10;n++){g.round++;a.actionLeft=b.actionLeft=true;g.progressAirports('blue',1);}}assert.equal(site.type,'airportDirt');for(const cell of g.airportApproaches(site))assert.equal(g.terrain[KEY(cell.x,cell.y)],'plain');assert.equal(g.terrain[KEY(50,50)],rough?'forest':'plain');g.hurt(site,999,null);assert.equal(g.terrain[KEY(48,50)],'plain');const h=field(mode);h.terrain.fill('forest');const x=h.add('blue','engineer',49,50),y=h.add('blue','engineer',50,49);assert.ok(h.buildAirport([x.id,y.id],p));h.hurt(h.structureAt(50,50),999,null);assert.equal(h.terrain[KEY(48,50)],'forest');}});
check('AI searches the whole map incrementally with at most four route candidates',()=>{const g=field();g.add('red','engineer',49,50);g.add('red','engineer',50,49);g.terrain.fill('river');for(let y=50;y<52;y++)for(let x=48;x<58;x++)g.terrain[KEY(x,y)]='plain';g.terrain[KEY(50,49)]='plain';let found=false;for(let i=0;i<90&&!found;i++){g.aiAirportPlan();found=g.structures.some(s=>s.type==='airportSite'&&s.x===50&&s.y===50);}assert.ok(found);const h=field();h.add('red','engineer',20,20);h.add('red','engineer',21,20);let checked=0;h.buildAirport=()=>{checked++;return false;};h.aiAirportPlan();assert.ok(checked>0&&checked<=4);});
check('legacy canteiro uses 30 seconds; no airport keeps planes in flight',()=>{const g=field(),a=g.add('blue','airportSite',50,50),x=g.add('blue','engineer',49,50),y=g.add('blue','engineer',50,49);a.work=0;g.assignAirportWorkers(a,[x.id,y.id]);g.progressAirports('blue',30);assert.equal(a.type,'airportDirt');const h=new Game('river','normal',71,'rts',{}, {},{blue:{fighterBlue:1},red:{}});h.structures=h.structures.filter(s=>s.type==='hq');h.aiEnabled=false;const p=h.units.find(PLANE);assert.equal(h.order(p,'return'),false);for(let n=0;n<60;n++)h.update(1/30);assert.ok(AIR(p));const base=h.add('blue','airportDirt',20,75);assert.ok(h.order(p,'return'));assert.equal(p.flightJob.airportId,base.id);});
check('RTS decision cycle tests at most four airport route candidates',()=>{const g=field();g.aiEnabled=true;g.aiClock=0;g.add('red','engineer',20,20);g.add('red','engineer',21,20);g.aiBuy=()=>{};let tested=0;g.buildAirport=()=>{tested++;return false;};g.updateRTS(.01);assert.ok(tested>0&&tested<=4,'route candidates in one decision cycle: '+tested);});
check('turn-based AI resumes construction with distant replacement engineers',()=>{const g=field('turns');g.add('blue','infantry',1,93);g.turn='red';g.add('red','airportSite',50,50).work=1;const a=g.add('red','engineer',20,20),b=g.add('red','engineer',21,20);assert.equal(g.assignAirportWorkers(g.structures.find(s=>s.type==='airportSite'),[a.id,b.id]),false);assert.ok(!a.pending&&!b.pending);assert.ok(g.aiAirportPlan());assert.equal(g.actions.length,2,'both workers must receive actual movement actions');assert.ok(a.pending&&b.pending);for(let n=0;n<300&&g.busy;n++)g.update(1/30);assert.ok(!a.pending&&!b.pending);a.x=49;a.y=50;b.x=50;b.y=49;a.actionLeft=b.actionLeft=true;assert.ok(g.aiAirportPlan());assert.ok(a.airportSiteId&&b.airportSiteId);g.round++;g.progressAirports('red',1);assert.equal(g.structures.find(s=>s.type==='airportSite').work,2);});
check('suggested infantry can leave HQ immediately without moving other troops',()=>{for(const mode of ['turns','rts']){const g=new Game('river','normal',17,mode);g.aiEnabled=false;const own=g.units.filter(u=>u.owner==='blue');assert.equal(new Set(own.map(u=>u.x+','+u.y)).size,own.length,'initial icons should not hide other troops');const ids=g.units.filter(u=>u.owner==='blue'&&u.type==='infantry').map(u=>u.id);assert.ok(g.command(ids,'move',{x:4,y:92})>0);}});
console.log(checks+' deployment checks passed');
