// Motor real de js/engine.js, sem navegador: turnos, RTS, tanques e gerador. node tests/engine.test.cjs
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync(path.join(__dirname,'..','js','engine.js'),'utf8')+'\nthis.Game=Game;this.TYPES=TYPES;this.COLS=COLS;this.ROWS=ROWS;this.KEY=KEY;',ctx);const {Game,TYPES,COLS,ROWS,KEY}=ctx;
// --- engine ---
{
function field(){const g=new Game('river','normal',17);g.terrain.fill('plain');g.units=[];g.structures=[];g.mines=[];g.aiEnabled=false;g.add('blue','hq',0,13);g.add('red','hq',17,0);g.add('blue','infantry',0,12);g.add('red','infantry',17,1);g.rng=()=>.2;g.updateVision();return g;}
function advance(g,seconds){for(let t=0;t<seconds-1e-8;t+=1/30)g.update(1/30);}
function settle(g){let ticks=0;while((g.busy||g.turn==='red')&&!g.winner&&ticks++<20000)g.update(1/30);assert.ok(ticks<20000,'Ordem/turno deve terminar');}
function cycle(g){assert.equal(g.endTurn(),true);settle(g);assert.equal(g.turn,'blue');}
function snapshot(g){return JSON.stringify({units:g.units.map(u=>[u.id,u.x,u.y,u.hp,u.moveLeft,u.actionLeft]),credits:g.credits,queues:g.structures.map(s=>s.queue),round:g.round,decisions:g.aiDecisions,shots:g.shotsFired});}
let checks=0;function check(name,fn){fn();checks++;console.log('OK '+name);}
check('Planejamento sem limite: IA, combate, recursos e produção imóveis',()=>{const g=field(),u=g.add('blue','infantry',5,5);g.add('red','tank',6,5);g.updateVision();g.aiEnabled=true;g.enqueue('blue','infantry');const before=snapshot(g);advance(g,120);assert.equal(snapshot(g),before);});
check('A* contorna água, usa pontes e respeita montanhas',()=>{const g=field(),u=g.add('blue','tank',3,5);for(let y=0;y<ROWS;y++)g.terrain[y*COLS+4]='river';assert.equal(g.findPath(u,{x:5,y:5}),null);g.terrain[7*COLS+4]='bridge';const route=g.findPath(u,{x:5,y:5});assert.ok(route.some(p=>p.x===4&&p.y===7));assert.ok(route.every(p=>g.terrain[p.y*COLS+p.x]!=='river'));g.terrain[5*COLS+5]='mountain';assert.equal(g.findPath(u,{x:5,y:5}),null);assert.ok(g.findPath({...u,type:'infantry'},{x:5,y:5}));});
check('Movimento suave limitado, fracionável e sem gastar ação',()=>{const g=field(),u=g.add('blue','infantry',3,5);assert.ok(g.order(u,'move',{x:4,y:5}));advance(g,.1);assert.ok(u.x>3&&u.x<4);assert.equal(g.endTurn(),false);settle(g);assert.equal(u.moveLeft,2);assert.equal(u.actionLeft,true);assert.ok(g.order(u,'move',{x:10,y:5}));settle(g);assert.equal(u.x,6);assert.equal(u.moveLeft,0);assert.equal(g.order(u,'move',{x:7,y:5}),false);});
check('Estrada custa meio ponto; veículo gasta dois em floresta',()=>{const g=field(),u=g.add('blue','tank',3,5);for(let x=4;x<=10;x++)g.terrain[5*COLS+x]='road';g.order(u,'move',{x:10,y:5});settle(g);assert.equal(u.x,10);assert.equal(u.moveLeft,.5);g.terrain[6*COLS+10]='forest';assert.equal(g.order(u,'move',{x:10,y:6}),false);const v=g.add('blue','tank',8,7);g.terrain[8*COLS+8]='forest';g.order(v,'move',{x:8,y:8});settle(g);assert.equal(v.moveLeft,2);});
check('Seleção em grupo não sobrepõe unidades nem ultrapassa orçamento',()=>{const g=field(),a=g.add('blue','infantry',3,4),b=g.add('blue','infantry',3,5);assert.equal(g.command([a.id,a.id,b.id],'move',{x:8,y:5}),2);settle(g);assert.notEqual(a.x+','+a.y,b.x+','+b.y);assert.ok(Math.abs(a.x-3)+Math.abs(a.y-4)<=3);assert.ok(Math.abs(b.x-3)+Math.abs(b.y-5)<=3);});
check('Ataque usa uma ação, dano somente no impacto, sem reação automática',()=>{const g=field(),a=g.add('blue','infantry',5,5),b=g.add('red','tank',6,5);g.updateVision();assert.ok(g.order(a,'attack',{targetId:b.id}));advance(g,.1);assert.equal(b.hp,170);assert.equal(a.actionLeft,false);settle(g);assert.equal(b.hp,135);assert.equal(g.shotsFired,1);assert.equal(a.hp,100);assert.equal(g.order(a,'attack',{targetId:b.id}),false);advance(g,30);assert.equal(b.hp,135);});
check('Ataque aproxima usando movimento e permite recuar com o restante',()=>{const g=field(),a=g.add('blue','infantry',3,5),b=g.add('red','tank',6,5);g.updateVision();assert.ok(g.order(a,'attack',{targetId:b.id}));settle(g);assert.equal(a.x,5);assert.equal(a.moveLeft,1);assert.equal(a.actionLeft,false);g.order(a,'move',{x:4,y:5});settle(g);assert.equal(a.x,4);assert.equal(a.moveLeft,0);});
check('Aguardar consome movimento/ação e entrincheira; novo turno restaura pontos',()=>{const g=field(),a=g.add('blue','infantry',5,5);assert.ok(g.order(a,'stop'));assert.equal(a.moveLeft,0);assert.equal(a.actionLeft,false);assert.equal(a.entrenched,true);assert.equal(g.order(a,'move',{x:6,y:5}),false);cycle(g);assert.equal(a.moveLeft,3);assert.equal(a.actionLeft,true);});
check('Artilharia não move e atira no mesmo turno em nenhuma ordem',()=>{for(const first of ['move','attack']){const g=field(),a=g.add('blue','artillery',4,6),target=g.add('red','hq',6,6);g.updateVision();assert.ok(g.order(a,first,first==='move'?{x:3,y:6}:{targetId:target.id}));settle(g);assert.equal(g.order(a,first==='move'?'attack':'move',first==='move'?{targetId:target.id}:{x:3,y:6}),false);}});
check('Artilharia mantém área 3x3 incluindo diagonais e fogo amigo',()=>{const g=field(),a=g.add('blue','artillery',4,6),b=g.add('red','hq',6,6),ally=g.add('blue','hq',7,7),outside=g.add('red','hq',8,8);g.updateVision();g.order(a,'attack',{targetId:b.id});advance(g,.3);assert.equal(b.hp,300);assert.ok(g.projectiles.length);settle(g);assert.equal(b.hp,230);assert.equal(a.moveLeft,0);assert.ok(ally.hp<300);assert.equal(outside.hp,300);});
check('Metralhador dispara rajada de três tiros por uma ação',()=>{const g=field(),a=g.add('blue','machinegun',5,5),b=g.add('red','infantry',6,5);g.updateVision();g.order(a,'attack',{targetId:b.id});settle(g);assert.equal(g.shotsFired,3);assert.equal(b.hp,31);assert.equal(a.actionLeft,false);assert.equal(g.order(a,'attack',{targetId:b.id}),false);});
check('Antitanque preserva especialidade e dano contra veículos',()=>{const g=field(),a=g.add('blue','antitank',5,5),foot=g.add('red','infantry',6,5),tank=g.add('red','tank',7,5);g.updateVision();assert.equal(g.acquire(a),tank);assert.equal(g.acquire({...a,type:'machinegun'}),foot);g.order(a,'attack',{targetId:tank.id});settle(g);assert.equal(tank.hp,80);});
check('Reparo aplica 24 HP por ação e não continua sozinho',()=>{const g=field(),a=g.add('blue','engineer',5,5),b=g.add('blue','tank',6,5);b.hp=100;g.order(a,'repair',{targetId:b.id});settle(g);assert.equal(b.hp,124);advance(g,30);assert.equal(b.hp,124);assert.equal(g.order(a,'repair',{targetId:b.id}),false);cycle(g);b.hp=169;g.order(a,'repair',{targetId:b.id});settle(g);assert.equal(b.hp,170);});
check('Captura usa uma ação; construção cobra 60 uma vez e converte a infantaria',()=>{const g=field(),a=g.add('blue','infantry',5,5),p=g.add('neutral','post',7,5);g.updateVision();g.order(a,'capture',{targetId:p.id});settle(g);assert.equal(p.owner,'blue');assert.equal(a.x,6);assert.equal(a.actionLeft,false);assert.equal(a.moveLeft,2);const b=g.add('blue','infantry',10,10),credits=g.credits.blue;assert.ok(g.order(b,'build'));assert.equal(g.order(b,'build'),false);settle(g);assert.equal(g.credits.blue,credits-60);assert.equal(g.structureAt(10,10).type,'post');assert.equal(g.get(b.id),undefined);});
check('Mina explode em movimento; engenheiro desarma com uma ação',()=>{const g=field(),a=g.add('blue','tank',4,6);g.mines.push({x:5,y:6,known:{blue:false,red:false}});g.order(a,'move',{x:6,y:6});settle(g);assert.equal(a.hp,130);assert.equal(g.mines.length,0);const e=g.add('blue','engineer',8,8);g.mines.push({x:9,y:8,known:{blue:false,red:false}});g.updateVision();g.order(e,'demine',{x:9,y:8});settle(g);assert.equal(g.mines.length,0);assert.equal(e.actionLeft,false);});
check('Renda uma vez por início do turno, sem renda dupla na rodada inicial',()=>{const g=field();g.add('blue','post',5,8);g.difficulty='hard';assert.equal(g.endTurn(),true);assert.equal(g.credits.red,150);assert.equal(g.endTurn(),false);settle(g);assert.equal(g.credits.blue,173);assert.equal(g.round,2);advance(g,60);assert.equal(g.credits.blue,173);assert.ok(g.endTurn());assert.equal(g.credits.red,168);settle(g);assert.equal(g.credits.blue,196);});
check('Dificuldade ajusta renda inimiga: fácil 12, normal 15, difícil 18',()=>{const g=field();for(const [level,value]of [['easy',12],['normal',15],['hard',18]]){g.difficulty=level;assert.equal(g.income('red'),value);assert.equal(g.income('blue'),15);}});
check('Fila serial produz em 1/2/3 turnos e cobra uma vez',()=>{for(const [type,turns] of [['infantry',1],['antitank',2],['machinegun',2],['tank',3],['artillery',3]]){const g=field();g.credits.blue=500;assert.ok(g.enqueue('blue',type));assert.equal(g.credits.blue,500-TYPES[type].cost);g.enqueue('blue','recon');for(let i=0;i<turns-1;i++){cycle(g);assert.equal(g.hq('blue').queue.length,2);}cycle(g);assert.equal(g.hq('blue').queue.length,1);assert.equal(g.hq('blue').queue[0].progress,0);const u=g.units.find(u=>u.owner==='blue'&&u.type===type&&u.y!==12);assert.ok(u);assert.equal(u.moveLeft,TYPES[type].move);assert.equal(u.actionLeft,true);}});
check('Produção pronta espera próximo turno com saída livre, sem duplicar custo',()=>{const g=field();g.enqueue('blue','infantry');for(const p of g.spawnCells('blue','infantry'))if(!g.occupied(p.x,p.y))g.add('blue','tank',p.x,p.y);cycle(g);assert.equal(g.hq('blue').queue[0].progress,1);const u=g.units.find(u=>u.type==='tank');g.units=g.units.filter(v=>v!==u);advance(g,30);assert.equal(g.hq('blue').queue.length,1);cycle(g);assert.equal(g.hq('blue').queue.length,0);assert.equal(g.credits.blue,130);});
check('Névoa oculta inimigos mesmo em terreno explorado; ataque exige visão',()=>{const g=field(),a=g.add('blue','recon',2,5),enemy=g.add('red','tank',5,5);g.updateVision();assert.equal(g.isVisible('blue',enemy),true);a.x=0;a.y=13;g.updateVision();assert.equal(g.isVisible('blue',enemy),false);assert.equal(g.explored.blue[5*COLS+5],true);assert.equal(g.order(a,'attack',{targetId:enemy.id}),false);});
check('Reconhecimento aliado permite artilharia além de sua visão própria',()=>{const g=field(),a=g.add('blue','artillery',4,6),target=g.add('red','hq',9,6);g.updateVision();assert.equal(g.canFire(a,target),false);const scout=g.add('blue','recon',7,8);g.updateVision();assert.equal(g.canFire(a,target),true);scout.x=1;scout.y=12;g.updateVision();assert.equal(g.canFire(a,target),false);});
check('Aura, veterania e perda do comandante preservadas',()=>{const g=field(),a=g.add('blue','infantry',4,4),c=g.add('blue','commander',3,4),e=g.add('red','commander',5,4);assert.equal(g.attackPower(a),42);g.credits.red=101;g.hurt(e,999,a);assert.equal(g.credits.red,50);assert.equal(a.level,2);assert.equal(a.maxHp,110);c.x=10;assert.ok(Math.abs(g.attackPower(a)-38.5)<.01);});
check('IA só joga após Enter, impede ordens do jogador e devolve controle',()=>{const g=field();g.aiEnabled=true;const a=g.add('red','tank',14,2);g.add('blue','infantry',15,2);g.updateVision();advance(g,10);assert.equal(g.aiDecisions,0);assert.equal(g.order(a,'move',{x:13,y:2}),false);g.endTurn();assert.equal(g.command([g.units[0].id],'stop'),0);assert.equal(g.enqueue('blue','infantry'),false);assert.equal(g.endTurn(),false);settle(g);assert.ok(g.aiDecisions>0);assert.equal(g.turn,'blue');assert.equal(g.round,2);assert.equal(g.aiState,'defend');});
check('IA repara aliados feridos e retira veículos gravemente danificados',()=>{const g=field(),e=g.add('red','engineer',14,3),tank=g.add('red','tank',13,3);tank.hp=90;g.beginTurn('red');assert.ok(g.order(e,'repair',{targetId:tank.id}));settle(g);assert.equal(tank.hp,114);g.beginTurn('red');tank.hp=20;g.aiAct(tank);assert.equal(tank.order.type,'move');});
check('Mapas conectados e simétricos em 200 sementes',()=>{for(const map of ['river','desert','mountain','random'])for(let seed=1;seed<=50;seed++){const g=new Game(map,'normal',seed);g.units=[];const tank={type:'tank',owner:'blue',x:4,y:ROWS-2};assert.ok(g.findPath(tank,{x:COLS-5,y:1}),map+'/'+seed);for(const p of g.structures.filter(s=>s.type==='post'))assert.ok([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>g.findPath(tank,{x:p.x+dx,y:p.y+dy})),'Posto acessível '+map+'/'+seed);for(let k=0;k<COLS*ROWS;k++)assert.equal(g.terrain[k],g.terrain[COLS*ROWS-1-k]);}});
check('Gerador procedural respeita água, floresta, montanha e postos',()=>{const count=(g,t)=>g.terrain.filter(v=>v===t).length;for(let seed=1;seed<=20;seed++){const dry=new Game('random','normal',seed,'turns',{water:0,forest:0,mountain:0,posts:4});assert.equal(count(dry,'river')+count(dry,'bridge')+count(dry,'mountain')+count(dry,'forest'),0);assert.equal(dry.structures.filter(s=>s.type==='post').length,4);const wild=new Game('random','normal',seed,'turns',{water:1,forest:1,mountain:1,posts:12});assert.ok(count(wild,'river')>0&&count(wild,'forest')>count(dry,'forest')&&count(wild,'mountain')>0,'seed '+seed);assert.equal(wild.structures.filter(s=>s.type==='post').length,12);assert.deepEqual(new Game('random','normal',seed,'turns',{water:1,forest:1,mountain:1,posts:12}).terrain,wild.terrain);}});
check('Partidas em quatro mapas: 12 rodadas sem travar, sobreposição ou terreno inválido',()=>{for(const map of ['river','desert','mountain','random']){const g=new Game(map,'normal',71);for(let round=0;round<12&&!g.winner;round++){g.endTurn();settle(g);const positions=new Set();for(const u of g.units){assert.ok(Number.isFinite(g.cost(u,u.x,u.y)),map+'/'+u.type);assert.ok(u.hp>0&&u.hp<=u.maxHp);assert.ok(u.moveLeft>=0);const key=u.x+','+u.y;assert.ok(!positions.has(key),'Sobreposição '+map+'/'+key);positions.add(key);}}assert.ok(g.aiDecisions>0);assert.ok(g.round>2||g.winner);}});
console.log(checks+' verificações concluídas.');
}
// --- rts ---
{
function field(){const g=new Game('river','normal',17,'rts');g.terrain.fill('plain');g.units=[];g.structures=[];g.mines=[];g.aiEnabled=false;g.add('blue','hq',0,13);g.add('red','hq',17,0);g.add('blue','infantry',0,12);g.add('red','infantry',17,1);g.rng=()=>.2;g.updateVision();return g;}
function advance(g,seconds){for(let t=0;t<seconds-1e-8;t+=1/30){g.update(Math.min(1/30,seconds-t));const occupied=new Set();for(const u of g.units){assert.ok(Number.isFinite(u.x)&&Number.isFinite(u.y));const key=u.x+','+u.y;assert.ok(!occupied.has(key),'Tropas não devem sobrepor');occupied.add(key);}}}
function snapshot(g){return JSON.stringify({time:g.time,units:g.units,structures:g.structures,credits:g.credits,projectiles:g.projectiles,decisions:g.aiDecisions,shots:g.shotsFired});}
let checks=0;function check(name,fn){fn();checks++;console.log('OK '+name);}
check('RTS é opcional e não encerra turnos',()=>{assert.equal(new Game().mode,'turns');const g=field();assert.equal(g.mode,'rts');assert.equal(g.endTurn(),false);assert.equal(g.round,1);});
check('Tropas movem simultaneamente além do orçamento por turno',()=>{const g=field(),a=g.add('blue','infantry',3,5),b=g.add('blue','infantry',3,7);assert.ok(g.order(a,'move',{x:10,y:5}));assert.ok(g.order(b,'move',{x:10,y:7}));advance(g,.2);assert.ok(a.x>3&&b.x>3,'Ambas devem avançar no mesmo intervalo');advance(g,6);assert.equal(a.x,10);assert.equal(b.x,10);assert.equal(a.y,5);assert.equal(b.y,7);});
check('Velocidade por classe e custo do terreno controlam deslocamento',()=>{const plain=field(),forest=field(),road=field();const a=plain.add('blue','tank',3,5),b=forest.add('blue','tank',3,5),c=road.add('blue','tank',3,5);forest.terrain[5*COLS+4]='forest';road.terrain[5*COLS+4]='road';for(const [g,u] of [[plain,a],[forest,b],[road,c]]){g.order(u,'move',{x:6,y:5});advance(g,.1);}assert.ok(b.x<a.x&&a.x<c.x,'Floresta deve frear e estrada acelerar');assert.ok(Math.abs((a.x-3)-TYPES.tank.speed*.1)<1e-6);});
check('Combate automático repete tiros respeitando a cadência',()=>{const g=field(),a=g.add('blue','tank',4,6),target=g.add('red','hq',6,6);g.updateVision();advance(g,1);assert.equal(g.shotsFired,1);assert.equal(target.hp,240);advance(g,1);assert.equal(g.shotsFired,1);advance(g,1);assert.equal(g.shotsFired,2);assert.equal(target.hp,180);assert.equal(a.hp,a.maxHp);});
check('Reordenar em movimento preserva posição; parar conclui só o segmento atual',()=>{const g=field(),u=g.add('blue','infantry',3,5);assert.ok(g.order(u,'move',{x:10,y:5}));advance(g,.2);const before=[u.x,u.y];assert.ok(g.order(u,'move',{x:4,y:9}));assert.deepEqual([u.x,u.y],before,'Reordenar não pode teletransportar');advance(g,5);assert.equal(u.x,4);assert.equal(u.y,9);assert.ok(g.order(u,'move',{x:10,y:9}));advance(g,.2);const endpoint={...u.segment.to},position=[u.x,u.y];assert.ok(g.order(u,'stop'));assert.deepEqual([u.x,u.y],position);advance(g,2);assert.deepEqual([u.x,u.y],[endpoint.x,endpoint.y]);const stopped=[u.x,u.y];advance(g,2);assert.deepEqual([u.x,u.y],stopped);});
check('Ordens aceitas durante pausa aguardam update; delta zero congela a simulação',()=>{const g=field(),u=g.add('blue','infantry',3,5),target=g.add('red','hq',6,6);g.add('blue','tank',4,6);g.updateVision();advance(g,.1);assert.ok(g.projectiles.length);assert.ok(g.order(u,'move',{x:8,y:5}));assert.equal(u.x,3);const before=snapshot(g);for(let i=0;i<100;i++)g.update(0);assert.equal(snapshot(g),before);advance(g,.2);assert.ok(u.x>3);assert.ok(target.hp<target.maxHp);});
check('Renda e produção usam segundos, mantêm fila serial e cobrança única',()=>{const g=field();g.credits.blue=500;assert.equal(g.trainDuration('infantry'),10);assert.equal(g.trainDuration('tank'),30);assert.ok(g.enqueue('blue','infantry'));assert.ok(g.enqueue('blue','recon'));assert.equal(g.credits.blue,375);const count=g.units.length;advance(g,9.9);assert.equal(g.units.length,count);assert.equal(g.credits.blue,375);advance(g,.2);assert.equal(g.units.length,count+1);assert.equal(g.hq('blue').queue.length,1);assert.equal(g.credits.blue,390);advance(g,10);assert.equal(g.units.length,count+2);assert.equal(g.hq('blue').queue.length,0);assert.equal(g.credits.blue,405);});
check('Produção pronta aguarda espaço e sai sem nova cobrança',()=>{const g=field();assert.ok(g.enqueue('blue','infantry'));for(const p of g.spawnCells('blue','infantry'))if(!g.occupied(p.x,p.y))g.add('blue','tank',p.x,p.y);const count=g.units.length;advance(g,10.1);assert.equal(g.units.length,count);assert.equal(g.hq('blue').queue.length,1);const blocker=g.units.find(u=>u.type==='tank');g.units=g.units.filter(u=>u!==blocker);advance(g,.2);assert.equal(g.units.length,count);assert.equal(g.hq('blue').queue.length,0);assert.equal(g.credits.blue,115);});
check('Construção leva três segundos e cancelamento devolve a reserva uma vez',()=>{const g=field(),u=g.add('blue','infantry',8,8);assert.ok(g.order(u,'build'));assert.equal(g.credits.blue,90);advance(g,1);assert.equal(g.structureAt(8,8),undefined);assert.ok(g.order(u,'move',{x:10,y:8}));assert.equal(g.credits.blue,150);assert.ok(g.order(u,'stop'));assert.equal(g.credits.blue,150);assert.ok(g.order(u,'build'));advance(g,2.9);assert.ok(g.get(u.id));assert.equal(g.structureAt(8,8),undefined);advance(g,.2);assert.equal(g.get(u.id),undefined);assert.equal(g.structureAt(8,8).type,'post');assert.equal(g.credits.blue,90);});
check('Captura e reparo avançam com tempo de simulação',()=>{const g=field(),u=g.add('blue','infantry',5,5),post=g.add('neutral','post',6,5),engineer=g.add('blue','engineer',8,8),tank=g.add('blue','tank',9,8);tank.hp=100;g.updateVision();assert.ok(g.order(u,'capture',{targetId:post.id}));assert.ok(g.order(engineer,'repair',{targetId:tank.id}));advance(g,1.1);assert.equal(post.owner,'neutral');assert.equal(tank.hp,124);advance(g,1.1);assert.equal(post.owner,'blue');assert.equal(tank.hp,148);advance(g,1.1);assert.equal(tank.hp,tank.maxHp);});
check('IA decide e movimenta tropas sem Encerrar turno',()=>{const g=field();g.aiEnabled=true;const before=g.units.filter(u=>u.owner==='red').map(u=>[u.id,u.x,u.y]);advance(g,5);assert.ok(g.aiDecisions>0);assert.notDeepEqual(g.units.filter(u=>u.owner==='red').map(u=>[u.id,u.x,u.y]),before);assert.equal(g.turn,'blue');});
check('Casas reservadas evitam colisão e ordem bloqueada retoma quando libera',()=>{const g=field(),a=g.add('blue','infantry',3,5),b=g.add('blue','infantry',5,5);assert.ok(g.order(a,'move',{x:4,y:5}));assert.ok(g.order(b,'move',{x:4,y:5}));advance(g,1);assert.equal(a.x,4);assert.equal(b.x,5);assert.ok(g.order(a,'move',{x:4,y:7}));advance(g,3);assert.deepEqual([a.x,a.y],[4,7]);assert.deepEqual([b.x,b.y],[4,5]);});
check('Desarme leva um segundo; minas ainda explodem durante deslocamento',()=>{const g=field(),e=g.add('blue','engineer',8,8);g.mines.push({x:9,y:8,known:{blue:true,red:false}});assert.ok(g.order(e,'demine',{x:9,y:8}));advance(g,.9);assert.equal(g.mines.length,1);advance(g,.2);assert.equal(g.mines.length,0);const tank=g.add('blue','tank',4,6);g.mines.push({x:5,y:6,known:{blue:false,red:false}});assert.ok(g.order(tank,'move',{x:6,y:6}));advance(g,2);assert.equal(tank.hp,130);assert.equal(g.mines.length,0);});
check('Quatro mapas RTS executam IA e grupos sem colisões ou terreno inválido',()=>{for(const map of ['river','desert','mountain','random']){const g=new Game(map,'normal',71,'rts');g.command(g.units.filter(u=>u.owner==='blue').map(u=>u.id),'move',{x:7,y:9});advance(g,60);assert.ok(g.aiDecisions>0,map);assert.ok(g.time>0);for(const u of g.units){assert.ok(u.hp>0&&u.hp<=u.maxHp);const p=u.segment?.to||{x:Math.round(u.x),y:Math.round(u.y)};assert.ok(Number.isFinite(g.cost(u,p.x,p.y)),map+'/'+u.type);}}});
console.log(checks+' verificações RTS concluídas.');
}
// --- tanks ---
{
const tanks=['lightTank','tank','heavyTank'];
function field(mode){const g=new Game('desert','normal',17,mode);g.units=[];g.structures=[];g.mines=[];g.terrain.fill('plain');g.aiEnabled=false;g.add('blue','hq',0,13);g.add('red','hq',17,0);g.add('blue','infantry',0,12);g.add('red','infantry',17,1);g.rng=()=>.2;return g;}
function advance(g,seconds){for(let t=0;t<seconds-1e-8;t+=1/30)g.update(1/30);}
function settle(g){let ticks=0;while(g.busy&&ticks++<10000)g.update(1/30);assert.ok(ticks<10000);}
for(const mode of ['turns','rts'])for(const type of tanks){
 const g=field(mode),u=g.add('blue',type,4,6);assert.ok(u,'Classe '+type+' deve existir');
 assert.equal(TYPES[type].vehicle,true);assert.equal(g.cost(u,5,6),1);g.terrain[6*COLS+5]='forest';assert.equal(g.cost(u,5,6),2);g.terrain[6*COLS+5]='mountain';assert.equal(g.cost(u,5,6),Infinity);g.terrain[6*COLS+5]='river';assert.equal(g.cost(u,5,6),Infinity);g.terrain[6*COLS+5]='road';assert.equal(g.cost(u,5,6),.5);
 g.terrain.fill('plain');g.updateVision();assert.ok(g.order(u,'move',{x:12,y:6}));if(mode==='turns'){settle(g);assert.equal(u.x,4+TYPES[type].move);}else{advance(g,.1);assert.ok(Math.abs(u.x-4-TYPES[type].speed*.1)<1e-7);}
 const p=field(mode);p.credits.blue=1000;assert.ok(p.enqueue('blue',type));assert.equal(p.credits.blue,1000-TYPES[type].cost);const duration=p.trainDuration(type);p.production('blue',duration-.1);assert.equal(p.units.length,2);p.production('blue',.1);assert.equal(p.units[2].type,type);assert.equal(p.hq('blue').queue.length,0);
 const fight=field(mode),a=fight.add('blue','recon',4,6),b=fight.add('red',type,6,6);fight.updateVision();assert.ok(fight.order(a,'attack',{targetId:b.id}));if(mode==='turns')settle(fight);else advance(fight,.7);assert.ok(b.maxHp-b.hp===Math.round(32*.4),'Batedor reduz dano contra '+type);
 const at=field(mode),rocket=at.add('blue','antitank',4,6),target=at.add('red',type,6,6);at.updateVision();assert.ok(at.order(rocket,'attack',{targetId:target.id}));if(mode==='turns')settle(at);else advance(at,.7);assert.equal(target.maxHp-target.hp,90,'Antitanque preserva bônus contra '+type);
 const repair=field(mode),e=repair.add('blue','engineer',4,6),t=repair.add('blue',type,5,6);t.hp=t.maxHp-30;repair.updateVision();assert.ok(repair.order(e,'repair',{targetId:t.id}));if(mode==='turns')settle(repair);else advance(repair,1.1);assert.equal(t.hp,t.maxHp-6);
 console.log('OK '+mode+'/'+type+': terreno, movimento, produção, batedor, antitanque e reparo');
}
for(const mode of ['turns','rts']){
 const g=new Game('river','normal',71,mode);for(const owner of ['blue','red'])assert.deepEqual(Array.from(g.units.filter(u=>u.owner===owner&&TYPES[u.type].tank),u=>u.type),['tank']);
 const ai=field(mode);ai.aiEnabled=true;ai.turn='red';ai.credits.red=10000;for(const [i,type]of ['infantry','infantry','engineer','recon','machinegun','antitank','artillery','artillery','tank'].entries())ai.add('red',type,10+i%3,4+Math.floor(i/3));
 const bought=[];for(let i=0;i<3;i++){ai.aiBuy();bought.push(ai.hq('red').queue[0]?.type);ai.production('red',100);}
 for(const type of tanks)assert.ok(bought.includes(type),'IA deve recrutar '+type+': '+bought);
 console.log('OK '+mode+': médio inicial e três classes recrutadas pela IA');
}
for(const [type,hp,damage,cost,train,interval,reward]of [['lightTank',110,35,100,2,2,35],['tank',170,60,150,3,2.5,50],['heavyTank',280,80,240,4,3.5,80]]){
 const g=field('rts'),u=g.add('blue',type,4,6),target=g.add('red','hq',6,6);g.updateVision();advance(g,.3);assert.equal(u.maxHp,hp);assert.equal(target.hp,300-damage);assert.equal(g.shotsFired,1);advance(g,interval-.4);assert.equal(g.shotsFired,1);advance(g,.3);assert.equal(g.shotsFired,2);
 for(const mode of ['turns','rts']){const p=field(mode);p.credits.blue=1000;p.enqueue('blue',type);assert.equal(p.credits.blue,1000-cost);assert.equal(p.trainDuration(type),train*(mode==='rts'?10:1));for(const cell of p.spawnCells('blue',type))if(!p.occupied(cell.x,cell.y))p.add('blue','infantry',cell.x,cell.y);p.production('blue',100);assert.equal(p.hq('blue').queue.length,1);const blocker=p.units[2];p.units=p.units.filter(v=>v!==blocker);p.production('blue',mode==='rts'?.1:1);assert.equal(p.hq('blue').queue.length,0);assert.equal(p.units.at(-1).type,type);assert.equal(p.credits.blue,1000-cost);}
 const kill=field('turns'),a=kill.add('blue',type,4,6),b=kill.add('red',type,6,6);kill.credits.blue=0;kill.hurt(b,999,a);assert.equal(kill.credits.blue,reward);assert.equal(a.level,2);assert.equal(a.maxHp,Math.round(hp*1.1));
 console.log('OK '+type+': atributos aprovados, cadência, produção bloqueada, recompensa e veterania');
}

}
