'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..'),out=path.join(root,'test-output','identity'),url=pathToFileURL(path.join(root,'public','index.html')).href;
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'}),errors=[],network=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.context().setOffline(true);await page.goto(url);await page.evaluate(()=>terrainReady);
 assert.equal(await page.title(),'rtsvibe — Fronteiras');assert.equal(await page.locator('#titleName').textContent(),'rtsvibe');assert.equal(await page.locator('header #nationHeaderFlag').getAttribute('aria-label'),'Bandeira da nação Azul');assert.equal(await page.locator('#nationHeaderName').textContent(),'Azul');assert.equal(await page.locator('#titleBg').count(),1);assert.equal(await page.locator('#titleScreen .conversation').count(),0);assert.equal(await page.locator('#titleBg').evaluate(e=>getComputedStyle(e).animationName),'titleDrift');assert.ok((await page.locator('#titleName').evaluate(e=>getComputedStyle(e).fontFamily)).includes('Georgia'));
 assert.equal(await page.locator('#titleTheme').inputValue(),'system');assert.equal(await page.evaluate(()=>document.documentElement.dataset.menuTheme),'light');
 const system=await page.locator('#titleScreen').evaluate(e=>{const c=getComputedStyle(e);return{font:c.fontFamily,size:c.fontSize,bg:c.backgroundColor};});assert.ok(!system.font.includes('Georgia'));assert.equal(system.size,'16px');assert.equal(system.bg,'rgb(244, 245, 239)');
 await page.locator('#titleTheme').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#titleTheme').inputValue(),'light');assert.equal(await page.locator('#titleTheme').evaluate(e=>e===document.activeElement),true);await page.locator('#titlePlay').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#titleCampaign').evaluate(e=>e===document.activeElement),true);
 await page.locator('#titleTheme').selectOption('dark');assert.equal(await page.evaluate(()=>localStorage.getItem('rtsvibe.theme.v1')),'dark');await page.reload();await page.evaluate(()=>terrainReady);assert.equal(await page.locator('#titleTheme').inputValue(),'dark');assert.equal(await page.evaluate(()=>document.documentElement.dataset.menuTheme),'dark');
 await page.emulateMedia({colorScheme:'light'});assert.equal(await page.evaluate(()=>document.documentElement.dataset.menuTheme),'dark');await page.locator('#titleTheme').selectOption('system');assert.equal(await page.evaluate(()=>document.documentElement.dataset.menuTheme),'light');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.menuTheme==='dark');
 await page.locator('#titleSettings').click();assert.equal(await page.locator('#setTheme').inputValue(),'system');await page.locator('#setTheme').selectOption('light');await page.locator('#settingsBack').click();assert.equal(await page.locator('#titleTheme').inputValue(),'light');await page.locator('#titleSettings').click();await page.locator('#settingsReset').click();assert.equal(await page.locator('#setTheme').inputValue(),'system');await page.locator('#settingsBack').click();
 const focus=async(theme,color)=>{await page.locator('#titleTheme').selectOption(theme);await page.locator('#titlePlay').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await page.waitForFunction(color=>{const e=document.getElementById('titlePlay');return e.matches(':focus-visible')&&getComputedStyle(e).outlineColor===color&&getComputedStyle(e).outlineWidth==='3px';},color);};await focus('light','rgb(45, 29, 26)');await focus('dark','rgb(247, 216, 52)');
 const luminance=c=>c.match(/[\d.]+/g).slice(0,3).map(n=>{n=Number(n)/255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;}).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0),contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
 for(const theme of ['light','dark']){await page.evaluate(theme=>setMenuTheme(theme),theme);await page.waitForFunction(theme=>getComputedStyle(document.getElementById('titlePlay')).backgroundColor===(theme==='light'?'rgb(247, 216, 52)':'rgb(235, 106, 64)'),theme);const colors=await page.evaluate(()=>{const c=e=>{const s=getComputedStyle(e);return[s.color,s.backgroundColor];};return[c($('titlePlay')),[getComputedStyle(document.querySelector('.title-sub')).color,getComputedStyle($('titleScreen')).backgroundColor]];});for(const [fg,bg] of colors)assert.ok(contrast(fg,bg)>=4.5,`${theme}: ${fg}/${bg}`);}
 await page.keyboard.press('Enter');assert.equal(await page.locator('#setup').evaluate(e=>e.open),true);await page.locator('#cancelSetup').click();
 console.log('OK marca, fonte, sistema/claro/escuro, persistência, restauração e teclado.');
 // A interface da partida acompanha o tema; o Canvas e a simulação permanecem iguais.
 await page.evaluate(()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation('river','normal',19,'rts');paused=true;pointer=null;renderer.draw(0);});const snapshot=()=>page.evaluate(()=>{renderer.draw(0);return{state:JSON.stringify([game.units,game.projectiles,game.credits,game.time,game.terrain]),canvas:$('battlefield').toDataURL()};});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const before=await snapshot();
 for(const theme of ['light','dark']){await page.evaluate(theme=>setMenuTheme(theme),theme);assert.deepEqual(await snapshot(),before);const colors=await page.evaluate(()=>[document.body,$('move'),$('commandBar')].map(e=>getComputedStyle(e).backgroundColor));assert.equal(colors[0],theme==='light'?'rgb(244, 245, 239)':'rgb(45, 29, 26)');assert.equal(colors[1],theme==='light'?'rgb(255, 255, 255)':'rgb(51, 43, 39)');assert.equal(colors[2],colors[1]);}
 await page.locator('#menuButton').click();await page.locator('#titleSettings').click();await page.locator('#setTheme').selectOption('light');await page.locator('#settingsBack').click();await page.locator('#titleResume').click();assert.equal(await page.evaluate(()=>paused),true);assert.deepEqual(await snapshot(),before);
 await page.evaluate(()=>{profile.stats.wins=2;saveProfile();settings.grid=true;saveSettings();});await page.reload();await page.evaluate(()=>terrainReady);assert.equal(await page.evaluate(()=>profile.stats.wins),2);assert.equal(await page.evaluate(()=>settings.grid),true);assert.ok(!Object.hasOwn(await page.evaluate(()=>bundle().settings),'theme'));
 await page.locator('#titleProfile').click();await page.getByRole('tab',{name:'Conta e save'}).click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportSave').click()]);assert.equal(download.suggestedFilename(),'rtsvibe-save.json');const old=JSON.parse(fs.readFileSync(await download.path(),'utf8'));old.profile.stats.wins=3;await page.locator('#importSave').setInputFiles({name:'wargrid-save.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});await page.waitForFunction(()=>profile.stats.wins===3);await page.locator('#closeProfile').click();
 await page.evaluate(()=>{profile.history=['win','loss'].map((result,i)=>({id:'contrast'+i,date:Date.now(),map:'river',difficulty:'normal',mode:'turns',result,round:10,kills:{},lost:{}}));});await page.locator('#titleProfile').click();await page.getByRole('tab',{name:'Histórico',exact:true}).click();
 for(const theme of ['light','dark']){
  await page.evaluate(theme=>setMenuTheme(theme),theme);const colors=await page.locator('#historyBody').evaluate(e=>[...e.querySelectorAll('td:nth-child(5)')].map(n=>[getComputedStyle(n).color,getComputedStyle($('profile')).backgroundColor]));for(const [fg,bg] of colors)assert.ok(contrast(fg,bg)>=4.5,`histórico ${theme}: ${fg}/${bg}`);
  const tab=page.getByRole('tab',{name:'Histórico',exact:true});await tab.hover();await page.waitForFunction(()=>!$('profile').getAnimations({subtree:true}).some(a=>a instanceof CSSTransition&&a.playState==='running'));const [fg,bg]=await tab.evaluate(e=>[getComputedStyle(e).color,getComputedStyle(e).backgroundColor]);assert.ok(contrast(fg,bg)>=4.5,`aba ativa com hover ${theme}: ${fg}/${bg}`);
 }
 await page.getByRole('tab',{name:'Conquistas',exact:true}).click();await page.locator('#closeProfile').click();
 console.log('OK campo e pausa preservados, tema separado do progresso, exportação nova e importação antiga.');
 // Mesmos fluxos nos dois temas, em computador, celular e tela baixa. Capturas de menus reais.
 fs.mkdirSync(out,{recursive:true});
 const capture=async(name,device,theme)=>{const d=page.locator('dialog[open]').last();await d.evaluate(e=>e.scrollTop=0);await page.waitForFunction(()=>[...document.querySelectorAll('dialog[open]')].every(d=>!d.getAnimations({subtree:true}).some(a=>a instanceof CSSTransition&&a.playState==='running')));const bad=await d.evaluate(e=>{const rect=e.getBoundingClientRect();return{overflow:e.scrollWidth>e.clientWidth+1,left:rect.left,right:rect.right,controls:[...e.querySelectorAll('button,select,input:not([type=checkbox]):not([type=file]),.file-button')].filter(n=>n.getClientRects().length).map(n=>{const r=n.getBoundingClientRect(),c=getComputedStyle(n);return{id:n.id,w:r.width,h:r.height,font:c.fontFamily,size:c.fontSize};})};});assert.equal(bad.overflow,false,name+'/'+device);assert.ok(bad.left>=-1&&bad.right<=await page.evaluate(()=>innerWidth)+1);for(const c of bad.controls){assert.ok(c.w>=43&&c.h>=43,JSON.stringify({name,device,c}));assert.ok(!c.font.includes('Georgia'));assert.equal(c.size,name==='inicio'&&c.id!=='titleTheme'?'18px':'16px');}await page.screenshot({path:path.join(out,`${name}-${device}-${theme}.png`)});};
 for(const device of ['desktop','mobile','short'])for(const theme of ['light','dark']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:device==='mobile'?{width:390,height:844}:{width:568,height:320});await page.evaluate(theme=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();setMenuTheme(theme);openTitle();},theme);await capture('inicio',device,theme);
  await page.locator('#titleSettings').click();await capture('configuracoes',device,theme);await page.locator('#settingsBack').click();
  await page.locator('#titlePlay').click();await capture('operacao',device,theme);await page.locator('#cancelSetup').click();
  await page.locator('#titleProfile').click();await capture('perfil',device,theme);await page.getByRole('tab',{name:'Conta e save'}).click();await capture('conta-offline',device,theme);await page.locator('#closeProfile').click();
  await page.locator('#titleHelp').click();await capture('manual',device,theme);await page.locator('#closeHelp').click();
  await page.locator('#titleCampaign').click();await capture('campanha',device,theme);await page.locator('#closeCampaign').click();
  await page.evaluate(()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();$('resultText').textContent='Vitória. Operação concluída.';openMenu('result');});await capture('resultado',device,theme);await page.locator('#review').click();
 }
 for(const device of ['desktop','mobile'])for(const theme of ['light','dark'])for(const battleMode of ['turns','rts']){await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});await page.evaluate(({theme,battleMode})=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();setMenuTheme(theme);newOperation('river','normal',19,battleMode);paused=true;selection=new Set([game.hq('blue').id]);updateUI();renderer.draw(0);},{theme,battleMode});assert.equal(await page.locator('#commandBar').isVisible(),true);const panel=await page.locator('#commandBar').evaluate(e=>getComputedStyle(e).backgroundColor);assert.equal(panel,theme==='light'?'rgb(255, 255, 255)':'rgb(51, 43, 39)');await page.screenshot({path:path.join(out,`partida-${battleMode}-${device}-${theme}.png`)});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>openTitle());assert.equal(await page.locator('#titlePlay').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');assert.equal(await page.locator('#titleBg').evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('OK oito menus, dois temas, três tamanhos, toque, rolagem, movimento reduzido e file:// offline.');
 // Sem armazenamento: escolha de tema continua válida durante a sessão e acompanha Sistema.
 const blocked=await browser.newPage({colorScheme:'light'});await blocked.addInitScript(()=>{Storage.prototype.getItem=Storage.prototype.setItem=()=>{throw Error('blocked');};});await blocked.goto(url);await blocked.evaluate(()=>terrainReady);await blocked.locator('#titleTheme').selectOption('dark');assert.equal(await blocked.evaluate(()=>document.documentElement.dataset.menuTheme),'dark');await blocked.locator('#titleTheme').selectOption('system');await blocked.emulateMedia({colorScheme:'dark'});await blocked.waitForFunction(()=>document.documentElement.dataset.menuTheme==='dark');await blocked.close();
 console.log('OK preferência em sessão com armazenamento bloqueado.');
 // Login/cadastro reais da interface sobre SDK e serviço em memória, sem conta ou rede externa.
 const authContext=await browser.newContext(),authPage=await authContext.newPage(),authErrors=[],unexpected=[];
 authPage.on('pageerror',e=>authErrors.push(e.message));
 const sdk=`let user=null,row=null;function enter(kind,p){(window.__authCalls||=[]).push(kind);user={id:'test-user',email:p.email};return{data:{user}};}export function createClient(){return{auth:{getSession:async()=>({data:{user}}),signIn:{email:async p=>enter('signin',p)},signUp:{email:async p=>enter('signup',p)},signOut:async()=>{user=null;}},from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:row?{data:row}:null}),upsert:async v=>{row=JSON.parse(JSON.stringify(v.data));return{error:null};}})}}`;
 await authContext.route('**/*',async route=>{const u=new URL(route.request().url());if(u.href==='https://cdn.jsdelivr.net/npm/@neondatabase/neon-js/+esm')return route.fulfill({body:sdk,contentType:'text/javascript',headers:{'Access-Control-Allow-Origin':'*'}});if(u.origin!=='http://rtsvibe.test'){unexpected.push(u.href);return route.abort();}if(u.pathname==='/js/neon-config.js')return route.fulfill({body:"const NEON_AUTH_URL='https://auth.rtsvibe.test';const NEON_DATA_API_URL='https://data.rtsvibe.test';",contentType:'text/javascript'});const file=path.join(root,'public',u.pathname==='/'?'index.html':u.pathname);if(!fs.existsSync(file))return route.fulfill({status:404});return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});});
 await authPage.goto('http://rtsvibe.test/');await authPage.waitForFunction(()=>cloud.client&&!cloud.busy);await authPage.locator('#titleProfile').click();await authPage.getByRole('tab',{name:'Conta e save'}).click();
 for(const device of ['desktop','mobile','short'])for(const theme of ['light','dark']){
  await authPage.setViewportSize(device==='desktop'?{width:1440,height:1000}:device==='mobile'?{width:390,height:844}:{width:568,height:320});await authPage.evaluate(theme=>{setMenuTheme(theme);$('profile').scrollTop=0;},theme);
  await authPage.waitForFunction(()=>!$('profile').getAnimations({subtree:true}).some(a=>a instanceof CSSTransition&&a.playState==='running'));
  assert.equal(await authPage.locator('#accountForm').isVisible(),true);assert.equal(await authPage.locator('.account-layout .conversation').isVisible(),device==='desktop');const layout=await authPage.locator('#accountForm').evaluate(e=>({width:e.getBoundingClientRect().width,fields:[...e.querySelectorAll('input')].map(n=>n.getBoundingClientRect().height),overflow:$('profile').scrollWidth>$('profile').clientWidth+1}));assert.ok(layout.width<=440);assert.equal(layout.overflow,false);assert.ok(layout.fields.every(h=>h>=48));await authPage.screenshot({path:path.join(out,`conta-${device}-${theme}.png`)});
 }
 await authPage.locator('#accountEmail').fill('comandante@example.test');await authPage.locator('#accountPassword').fill('teste-12345');await authPage.locator('#accountSignUp').click();await authPage.waitForFunction(()=>cloud.user&&cloud.at&&!cloud.busy);assert.equal(await authPage.locator('#accountPassword').inputValue(),'');assert.equal(await authPage.locator('#accountSignedIn').isVisible(),true);assert.equal(await authPage.evaluate(()=>localStorage.getItem('rtsvibe.theme.v1')),'dark');await authPage.locator('#accountSignOut').click();await authPage.waitForFunction(()=>!cloud.user);await authPage.locator('#accountPassword').fill('teste-12345');await authPage.locator('#accountSignIn').click();await authPage.waitForFunction(()=>cloud.user&&cloud.at&&!cloud.busy);assert.deepEqual(await authPage.evaluate(()=>window.__authCalls),['signup','signin']);assert.equal(await authPage.evaluate(()=>Object.hasOwn(bundle().settings,'theme')),false);assert.deepEqual(authErrors,[]);assert.deepEqual(unexpected,[]);await authContext.close();console.log('OK login/cadastro e sincronização simulados, conta responsiva nos dois temas e nenhuma rede externa.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
