'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright-core');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const page=await b.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(__dirname,'..','public','index.html')).href);await page.evaluate(()=>terrainReady);
 for(const mode of ['turns','rts']){
  const terrain=await page.evaluate(mode=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation('random','normal',71,mode,{posts:2});paused=true;game.aiEnabled=false;settings.graphics='performance';game.units=[];game.structures=[];game.memory.blue.clear();game.mines=[];setSelection([]);cam.zoom=.35;centerCamera(64,48);renderer.rebuild();game.visible.blue.fill(false);game.sky.blue.fill(false);renderer.draw(0);renderer.drawMini();const hidden=renderer.canvas.toDataURL(),mini=$('minimap').toDataURL();game.visible.blue.fill(true);renderer.draw(0);renderer.drawMini();return{clear:hidden===renderer.canvas.toDataURL(),mini:mini===$('minimap').toDataURL()};},mode);
  assert.ok(!terrain.clear&&!terrain.mini,'Campo e minimapa devem escurecer fora do reconhecimento');
  const neutral=await page.evaluate(mode=>{newOperation('random','normal',71,mode,{posts:2});paused=true;game.aiEnabled=false;const p=game.structures.find(s=>s.owner==='neutral'&&!game.isVisible('blue',s)),k=KEY(p.x,p.y);centerCamera(p.x,p.y);const calls=[],entity=renderer.entity;renderer.entity=function(s,m){calls.push({id:s.id,owner:s.owner,memory:!!m});return entity.call(this,s,m);};let marker;try{renderer.draw(0);marker=calls.find(s=>s.id===p.id&&s.memory);}finally{renderer.entity=entity;}
   renderer.drawMini();const t=miniTransform($('minimap')),pixel=()=>Array.from(renderer.mini.getImageData(Math.floor(t.ox+(p.x+.5)*t.s),Math.floor(t.oy+(p.y+.5)*t.s),1,1).data).join(',');const before=pixel(),owner=game.memory.blue.get(k).owner;p.owner='red';game.updateVision();renderer.drawMini();const retained=before===pixel()&&game.memory.blue.get(k).owner===owner;game.hurt(p,999,null);game.updateVision();const destroyedStillKnown=game.memory.blue.has(k);game.add('blue','recon',p.x,p.y);game.updateVision();return{marker:marker?.owner==='neutral',retained,destroyedStillKnown,cleared:!game.memory.blue.has(k),pixel:before,color:TEAM.neutral};},mode);
  assert.ok(neutral.marker&&neutral.retained&&neutral.destroyedStillKnown&&neutral.cleared,JSON.stringify(neutral));assert.ok(Number(neutral.pixel.split(',')[0])<224,'Objetivo lembrado deve ficar sob a camada escura');
  const missiles=await page.evaluate(mode=>{newOperation('random','normal',71,mode,{posts:2});paused=true;game.aiEnabled=false;game.units=[];game.structures=[];game.memory.blue.clear();game.projectiles=[];game.mines=[];game.terrain.fill('plain');game.add('blue','hq',1,94);game.add('red','hq',126,1);game.add('blue','infantry',2,94);game.add('red','infantry',125,1);const a=game.add('red','antiAirVehicle',60,50),h=game.add('blue','helicopter',35,50);h.altitude='high';h.flares=0;a.cooldown=100;game.updateVision();game.shoot(a,h);a.cooldown=100;game.update(.1);const p=game.projectiles[0];setSelection([]);centerCamera(60,50);renderer.rebuild();renderer.consume();renderer.draw(0);const withMissile=renderer.canvas.toDataURL();game.projectiles=[];renderer.particles=[];renderer.draw(0);const bare=renderer.canvas.toDataURL();game.projectiles=[p];p.weapon='gun';renderer.draw(0);const gunHidden=bare===renderer.canvas.toDataURL();game.projectiles=[];game.events=[];game.event('blast',{x:60,y:50},{visible:true,publicMissile:true,air:true,contactId:a.id});renderer.consume();renderer.draw(0);return{shown:withMissile!==bare,gunHidden,blast:bare!==renderer.canvas.toDataURL(),sourceHidden:!game.isVisible('blue',a),groundCache:renderer.terrainView.width===renderer.canvas.width};},mode);
  assert.ok(missiles.shown&&missiles.gunHidden&&missiles.blast&&missiles.sourceHidden&&missiles.groundCache,JSON.stringify(missiles));console.log('OK '+mode+': mapa conhecido escuro, neutros lembrados, misseis publicos sem revelar unidades');
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{cam.zoom=.35;centerCamera(60,50);renderer.draw(0);updateUI();});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('OK mapa conhecido em tela pequena e offline');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
