'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync('public/js/engine.js','utf8')+'\nthis.api={Game,KEY,TYPES};',ctx);const {Game,KEY}=ctx.api;
function field(mode){const g=new Game('random','normal',71,mode,{posts:2});g.units=[];g.structures=[];g.memory.blue.clear();g.memory.red.clear();g.terrain.fill('plain');g.mines=[];g.aiEnabled=false;g.add('blue','hq',1,94);g.add('red','hq',126,1);g.add('blue','infantry',2,94);g.add('red','infantry',125,1);g.updateVision();return g;}
for(const mode of ['turns','rts']){
 const fresh=new Game('random','normal',71,mode,{posts:2});for(const owner of ['blue','red']){assert.ok(fresh.explored[owner].every(Boolean),'Todo terreno conhecido');assert.ok(fresh.mines.every(m=>!m.known[owner]),'Terreno conhecido nao revela minas');assert.ok(fresh.units.filter(u=>u.owner!==owner).every(u=>!fresh.isVisible(owner,u)),'Terreno conhecido nao revela tropas inimigas');for(const s of fresh.structures.filter(s=>s.owner==='neutral'))assert.equal(fresh.memory[owner].get(KEY(s.x,s.y)).owner,'neutral');}
 for(const owner of ['blue','red']){
  const g=field(mode),foe=owner==='blue'?'red':'blue',a=g.add(owner,'antiAirVehicle',20,40),h=g.add(foe,'helicopter',50,40);h.altitude='high';g.updateVision();
  for(const terrain of ['plain','hill','mountain']){g.terrain[KEY(20,40)]=terrain;assert.equal(g.range(a,h),30);assert.ok(g.canFire(a,h));h.x=51;g.updateVision();assert.ok(g.radarContact(owner,h));assert.equal(g.canFire(a,h),false);h.x=50;}
  for(const type of owner==='blue'?['fighterBlue','multiroleBlue']:['fighterRed','multiroleRed']){const p=g.add(owner,type,20,20),emitter=g.add(foe,'antiAirVehicle',45,20);g.setWeapon(p,'antiRadiation');assert.equal(g.weaponRange(p,'antiRadiation'),25);assert.ok(g.canIdentify(p,emitter));assert.ok(g.canFire(p,emitter));emitter.x=46;assert.equal(g.canIdentify(p,emitter),false);assert.equal(g.canFire(p,emitter),false);}
  const neutral=g.add('neutral','post',80,70);g.updateVision();assert.equal(g.visible.blue[KEY(neutral.x,neutral.y)],false);assert.equal(g.visible.red[KEY(neutral.x,neutral.y)],false);const post=g.add(owner,'post',60,60),target=g.add(foe,'infantry',68,60);g.updateVision();assert.equal(g.sight(post),8);assert.ok(g.isVisible(owner,target));target.x=69;g.updateVision();assert.equal(g.isVisible(owner,target),false);
  target.x=68;g.terrain[KEY(68,60)]='forest';g.updateVision();assert.equal(g.isVisible(owner,target),false);target.x=62;g.terrain[KEY(62,60)]='forest';g.updateVision();assert.ok(g.isVisible(owner,target));
  g.terrain[KEY(60,60)]='hill';assert.equal(g.sight(post),10);g.terrain[KEY(60,60)]='plain';post.owner=foe;g.updateVision();assert.equal(g.isVisible(owner,target),false);g.terrain[KEY(68,60)]='plain';const witness=g.add(owner,'infantry',68,60);g.updateVision();assert.ok(g.isVisible(foe,witness));g.hurt(post,999,null);g.updateVision();assert.equal(g.isVisible(foe,witness),false);
 }
 const g=field(mode),p=g.add('red','stealthDrone',60,50),target=g.add('red','infantry',62,50);g.projectiles.push({weapon:'stealthMissile',type:p.type,owner:'red',attackerId:p.id,targetId:target.id,x:60,y:50,sx:60,sy:50,tx:62,ty:50,air:true,elapsed:0,duration:1,trail:[],power:20,hit:true});g.events=[];g.update(.1);assert.ok(g.events.some(e=>e.kind==='smoke'&&e.visible&&e.publicMissile));assert.equal(p.spotted.blue,false);g.impact({...g.projectiles[0],hit:true});assert.ok(g.events.some(e=>e.kind==='blast'&&e.visible&&e.publicMissile));assert.ok(!g.events.some(e=>e.kind==='text'&&e.visible));
 console.log('OK '+mode+': mapa, neutros, limites, postos, cobertura e misseis sem revelar dano ou furtivo');
}
