'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync('public/js/engine.js','utf8')+'\nObject.assign(this,{Game,TYPES,KEY,AIR,PLANE,DIST,MISSILE,armyCost,armyOverBudget,cleanStartingArmy,STARTING_DEFAULT});',ctx);
const {Game,TYPES,KEY,AIR,PLANE,DIST,MISSILE}=ctx,cases=[],test=(name,fn)=>cases.push([name,fn]);
function field(mode='rts'){const g=new Game('river','normal',123,mode,{posts:2});g.terrain.fill('plain');g.units=[];g.structures=[];g.mines=[];g.actions=[];g.animation=null;g.projectiles=[];g.memory.blue.clear();g.memory.red.clear();g.aiEnabled=false;g.add('blue','hq',1,94);g.add('red','hq',126,1);g.add('blue','infantry',2,94);g.add('red','infantry',125,1);g.rng=()=>.5;g.updateVision();return g;}
function advance(g,s){for(let n=0;n<Math.ceil(s*30);n++)g.update(1/30);}
function settle(g){let n=0;while(g.busy&&n++<20000)g.update(1/30);assert.ok(n<20000,'ordem deve liberar planejamento');}
test('cinco classes capturam postos nas duas equipes e modos; pistas apenas infantaria',()=>{for(const mode of ['rts','turns'])for(const owner of ['blue','red'])for(const type of ['infantry','missileInfantry','machinegun','antitank','commander']){const g=field(mode);g.turn=owner;const u=g.add(owner,type,20,20),p=g.add('neutral','post',20,20);p.queue=[{type:'infantry',progress:0}];g.updateVision();assert.ok(g.order(u,'capture',{targetId:p.id}),type);if(mode==='rts')advance(g,2.1);else settle(g);assert.equal(p.owner,owner);assert.equal(p.queue.length,0);const a=g.add('neutral','airportDirt',21,20);u.actionLeft=true;g.turn=owner;g.updateVision();assert.equal(g.order(u,'capture',{targetId:a.id}),type==='infantry');}});
test('captura distante usa memoria, persiste sem observador e confirma destruicao apenas ao ver',()=>{const g=field(),u=g.add('blue','infantry',20,20),p=g.add('neutral','post',40,20);g.memory.blue.set(KEY(40,20),{id:p.id,type:'post',x:40,y:20,owner:'neutral'});assert.ok(g.order(u,'capture',{targetId:p.id}));advance(g,1);assert.equal(u.order.type,'capture');const scout=g.add('blue','reconDrone',40,20);g.updateVision();advance(g,.1);g.units=g.units.filter(t=>t!==scout);g.updateVision();assert.equal(u.order.type,'capture');g.structures=g.structures.filter(t=>t!==p);advance(g,1);assert.equal(u.order.type,'capture');advance(g,20);assert.equal(u.captureIntent,null);assert.equal(u.order.type,'stop');assert.ok(g.logs.some(l=>/destru|existe/i.test(typeof l==='string'?l:l.text)));});
test('captura continua entre turnos e so gasta acao ao capturar; parar cancela',()=>{const g=field('turns'),u=g.add('blue','infantry',20,20),p=g.add('neutral','post',29,20);g.memory.blue.set(KEY(29,20),{id:p.id,type:'post',x:29,y:20,owner:'neutral'});assert.ok(g.order(u,'capture',{targetId:p.id}));settle(g);assert.equal(u.actionLeft,true);assert.equal(u.pending,false);assert.ok(u.captureIntent);g.beginTurn('blue');assert.equal(u.order.type,'capture');const x=u.x;assert.ok(g.endTurn());settle(g);assert.ok(u.x>x);g.beginTurn('blue');g.endTurn();settle(g);assert.equal(p.owner,'blue');assert.equal(u.actionLeft,false);g.beginTurn('blue');const p2=g.add('neutral','post',40,20);g.memory.blue.set(KEY(40,20),{id:p2.id,type:'post',x:40,y:20,owner:'neutral'});assert.ok(g.order(u,'capture',{targetId:p2.id}));settle(g);assert.ok(g.order(u,'stop'));assert.equal(u.captureIntent,null);});
test('bloqueio temporario nao apaga captura',()=>{const g=field(),u=g.add('blue','infantry',20,20),p=g.add('neutral','post',24,20);for(const [x,y]of [[21,20],[19,20],[20,19],[20,21]])g.add('blue','tank',x,y);g.updateVision();assert.ok(g.order(u,'capture',{targetId:p.id}));advance(g,1);assert.ok(u.captureIntent);g.units=g.units.filter(t=>t.type!=='tank');advance(g,8);assert.equal(p.owner,'blue');});
test('jetGun carga, precos, compatibilidade, precisao e recarga independente',()=>{const g=field(),u=g.add('blue','fighterBlue',20,20),e=g.add('red','infantry',24,20),light=g.add('red','lightTank',24,21),tank=g.add('red','tank',24,22);g.updateVision();assert.equal(u.ammo.jetGun,80);assert.equal(TYPES.fighterBlue.cost,610);assert.equal(TYPES.fighterRed.cost,590);assert.equal(TYPES.multiroleBlue.cost,750);assert.equal(TYPES.multiroleRed.cost,920);assert.equal(TYPES.bomberRed.cost,884);assert.equal(TYPES.bomberBlue.ammo.jetGun,undefined);assert.equal(ctx.armyCost(ctx.STARTING_DEFAULT),1145);assert.ok(g.planeWeaponFits(u,'jetGun',e));assert.ok(g.planeWeaponFits(u,'jetGun',light));assert.equal(g.planeWeaponFits(u,'jetGun',tank),false);assert.equal(MISSILE('jetGun'),false);assert.ok(Math.abs(g.accuracy(u,e,'jetGun')-.65)<1e-6);u.cooldown=3;g.shoot(u,e,'jetGun');assert.equal(u.ammo.jetGun,79);assert.equal(u.cooldown,3);const p=g.projectiles.at(-1);assert.equal(p.weapon,'jetGun');assert.equal(p.flareProtected,false);p.critical=false;g.impact(p);assert.equal(e.hp,94);});
test('rajada parcial, dano leve, flares intactos e rearmamento somente gasto',()=>{const g=field(),u=g.add('blue','fighterBlue',20,20),e=g.add('red','fighterRed',23,20);e.flightState='patrol';e.flightJob=null;u.facing=Math.PI/2;u.ammo.jetGun=2;g.updateVision();g.shoot(u,e,'jetGun');const p=g.projectiles.at(-1);assert.equal(e.flares,6);assert.ok(Math.abs(p.accuracy-(.85-.2*3/4)*(1-g.planeEvasion(e)/2))<1e-6);const base=g.add('blue','airportAsphalt',20,20);u.flightState='grounded';u.airportId=base.id;const before=g.credits.blue;assert.ok(g.servicePlane(u));assert.equal(g.credits.blue,before-79);g.progressPlaneService('blue',10);assert.equal(u.ammo.jetGun,80);});
test('perseguicao continua RTS, uma passagem por turno, cancelamento e perda de alvo',()=>{for(const mode of ['rts','turns']){const g=field(mode),u=g.add('blue','fighterBlue',20,20),e=g.add('red','helicopter',27,20);e.hp=e.maxHp=10000;e.flares=0;u.facing=Math.PI/2;g.add('blue','reconDrone',27,20);g.updateVision();assert.ok(g.order(u,'attack',{targetId:e.id,weapon:'jetAam',salvo:1}));if(mode==='rts'){advance(g,15);assert.ok(u.ammo.jetAam<3,'nova passagem');assert.ok(u.pursuitIntent||u.flightJob?.type==='return');}else{settle(g);assert.equal(u.ammo.jetAam,3);assert.ok(u.pursuitIntent);assert.equal(u.pending,false);g.beginTurn('blue');g.endTurn();settle(g);assert.equal(u.ammo.jetAam,2);}if(mode==='turns')g.beginTurn('blue');assert.ok(g.order(u,'stop'));assert.equal(u.pursuitIntent,null);}});
test('curvas de combate limitadas, velocidade constante e bordas sem salto',()=>{for(const type of ['fighterBlue','fighterRed','multiroleBlue','multiroleRed','bomberRed']){const g=field(),u=g.add(TYPES[type].team,type,1,1);u.facing=-Math.PI/2;for(let n=0;n<120;n++){const x=u.x,y=u.y,a=u.facing;g.flyCombat(u,{x:0,y:0},1/30);const turn=Math.abs(Math.atan2(Math.sin(u.facing-a),Math.cos(u.facing-a)));assert.ok(turn<=g.planeTurnRate(u)/30+1e-8);assert.ok(Math.hypot(u.x-x,u.y-y)<=TYPES[type].speed/30+1e-8);assert.ok(u.x>=0&&u.y>=0&&u.x<=127&&u.y<=95);}}});
test('Auto combina misseis e uma rajada; manual conserva a outra arma',()=>{for(const weapon of ['auto','jetGun','jetAam']){const g=field('turns'),u=g.add('blue','fighterBlue',20,20),e=g.add('red','helicopter',27,20);e.hp=e.maxHp=10000;e.flares=0;u.facing=Math.PI/2;g.add('blue','reconDrone',27,20);g.updateVision();assert.ok(g.order(u,'attack',{targetId:e.id,weapon,salvo:2}));settle(g);assert.equal(u.ammo.jetAam,weapon==='jetGun'?4:2);assert.equal(u.ammo.jetGun,weapon==='jetAam'?80:76);}});
test('reacao por turno dura no maximo dois segundos e nao gasta proxima acao',()=>{const g=field('turns'),u=g.add('blue','fighterBlue',20,20),e=g.add('red','fighterRed',23,20);u.facing=Math.PI/2;e.facing=-Math.PI/2;e.hp=e.maxHp=10000;u.hp=u.maxHp=10000;u.ammo.jetAam=0;g.updateVision();assert.ok(g.order(u,'attack',{targetId:e.id,weapon:'jetGun'}));advance(g,3);assert.ok(e.airReactionUsed);assert.ok(e.ammo.jetGun>=76);assert.equal(e.actionLeft,true);const position=[e.x,e.y];advance(g,2);assert.deepEqual([e.x,e.y],position);g.beginTurn('red');assert.equal(e.actionLeft,true);});
test('retorno explicito nao e substituido por contra-ataque RTS',()=>{const g=field(),u=g.add('blue','fighterBlue',40,40),e=g.add('red','fighterRed',43,40),base=g.add('blue','airportAsphalt',20,20);u.hp=u.maxHp=10000;e.hp=e.maxHp=10000;g.updateVision();assert.ok(g.order(u,'return',{targetId:base.id}));assert.ok(g.order(e,'attack',{targetId:u.id}));advance(g,.5);assert.equal(u.flightJob.type,'return');assert.equal(u.pursuitIntent,null);});
test('perda de alvo nao acompanha posicao oculta nem escolhe outro inimigo',()=>{const g=field(),u=g.add('blue','multiroleBlue',20,20),e=g.add('red','helicopter',24,20);u.facing=Math.PI/2;e.hp=10000;g.updateVision();assert.ok(g.order(u,'attack',{targetId:e.id}));advance(g,.1);e.x=100;e.y=80;g.updateVision();advance(g,.1);assert.equal(u.pursuitIntent,null);assert.equal(u.flightState,'patrol');});
test('rajada interrompida fora do cone e municao parcial encerram sem tiros extras',()=>{const g=field(),u=g.add('blue','fighterBlue',20,20),e=g.add('red','infantry',23,20);u.facing=Math.PI/2;g.updateVision();assert.ok(g.startGunBurst(u,e));assert.equal(u.ammo.jetGun,79);e.y=26;g.updateVision();for(let n=0;n<30;n++)g.advanceGunBurst(u,1/30);assert.equal(u.gunBurst,null);assert.equal(u.ammo.jetGun,79);e.y=20;g.updateVision();u.ammo.jetGun=3;assert.equal(g.startGunBurst(u,e),false,'intervalo de 2 s entre rajadas');u.gunCooldown=0;assert.ok(g.startGunBurst(u,e));for(let n=0;n<30;n++)g.advanceGunBurst(u,1/30);assert.equal(u.ammo.jetGun,0);assert.equal(u.gunBurst,null);assert.equal(g.projectiles.filter(p=>p.weapon==='jetGun').length,4);});
test('defesa automatica e investida simultaneas disparam uma rajada por passagem',()=>{const g=field(),u=g.add('blue','fighterBlue',40,40),e=g.add('red','fighterRed',43,40);u.facing=Math.PI/2;e.facing=-Math.PI/2;for(const p of [u,e]){p.hp=p.maxHp=100000;p.ammo.jetAam=0;p.ammo.antiRadiation=0;}g.updateVision();const counts=new Map(),start=g.startGunBurst;g.startGunBurst=function(p,t){const job=p.flightJob,ok=start.call(this,p,t);if(ok&&job?.type==='strike')counts.set(job,(counts.get(job)||0)+1);return ok;};assert.ok(g.order(u,'attack',{targetId:e.id,weapon:'jetGun'}));assert.ok(g.order(e,'attack',{targetId:u.id,weapon:'jetGun'}));advance(g,12);assert.ok(counts.size>=2,'houve passagens com rajada');assert.ok([...counts.values()].every(n=>n===1),JSON.stringify([...counts.values()]));});
test('rajada defensiva por turnos termina com a janela de dois segundos',()=>{const g=field('turns'),u=g.add('blue','fighterBlue',40,40),e=g.add('red','fighterRed',43,40);e.facing=-Math.PI/2;g.updateVision();e.airReactionUsed=true;e.airReaction={targetId:u.id,left:.1,burst:false};advance(g,1);assert.equal(e.ammo.jetGun,79);assert.equal(e.gunBurst,null);assert.equal(e.airReaction.left,0);});
test('IA recua durante perseguicao e sem pista volta a patrulhar',()=>{for(const airport of [true,false]){const g=field(),e=g.add('red','fighterRed',60,40),b=g.add('blue','fighterBlue',64,40);if(airport)g.add('red','airportAsphalt',100,10);b.hp=b.maxHp=100000;e.facing=Math.PI/2;g.updateVision();assert.ok(g.order(e,'attack',{targetId:b.id}));assert.ok(e.pursuitIntent);e.hp=Math.floor(e.maxHp*.3);g.aiEnabled=true;g.aiClock=0;g.updateRTS(1/30);assert.equal(e.pursuitIntent,null);assert.equal(e.flightJob.type,airport?'return':'transfer');}});
test('sem municao e sem aeroporto a perseguicao termina em patrulha',()=>{const g=field(),u=g.add('blue','fighterBlue',40,40),e=g.add('red','helicopter',44,40);g.updateVision();u.ammo={jetAam:0,antiRadiation:0,jetGun:0};u.pursuitIntent={targetId:e.id,weapon:'auto',salvo:1};assert.equal(g.resumePursuit(u),true);assert.equal(u.pursuitIntent,null);assert.equal(u.flightState,'patrol');assert.equal(u.flightJob,null);});
test('bloqueio surgido na rota por turnos espera, recalcula e mantem a captura',()=>{const g=field('turns'),u=g.add('blue','infantry',20,20),p=g.add('neutral','post',29,20);g.memory.blue.set(KEY(29,20),{id:p.id,type:'post',x:29,y:20,owner:'neutral'});assert.ok(g.order(u,'capture',{targetId:p.id}));g.add('blue','tank',22,20);settle(g);assert.deepEqual([u.x,u.y],[21,20]);assert.ok(u.captureIntent);assert.equal(u.actionLeft,true);for(let i=0;i<5&&p.owner!=='blue';i++){assert.ok(g.endTurn());settle(g);g.beginTurn('blue');}assert.equal(p.owner,'blue');assert.equal(u.captureIntent,null);});
test('troca oculta de dono nao revela nada e a captura continua ate observar',()=>{const g=field(),u=g.add('blue','infantry',20,20),p=g.add('neutral','post',40,20);g.memory.blue.set(KEY(40,20),{id:p.id,type:'post',x:40,y:20,owner:'neutral'});assert.ok(g.order(u,'capture',{targetId:p.id}));advance(g,1);const logs=g.logs.length;p.owner='red';advance(g,1);assert.equal(g.memory.blue.get(KEY(40,20)).owner,'neutral');assert.equal(g.logs.length,logs);assert.equal(u.order.type,'capture');advance(g,20);assert.equal(p.owner,'blue');});
test('evasao durante retorno e bombardeio preserva as missoes',()=>{const g=field(),base=g.add('blue','airportAsphalt',20,20),u=g.add('blue','fighterBlue',60,40),r=g.add('red','fighterRed',90,40),calls=[],fly=g.flyCombat;g.flyCombat=function(p,goal,dt){calls.push(p.id);return fly.call(this,p,goal,dt);};assert.ok(g.order(u,'return',{targetId:base.id}));g.projectiles=[{targetId:u.id,weapon:'jetAam',attackerId:r.id,x:u.x+1,y:u.y}];g.stepPlane(u,1/30);assert.ok(calls.includes(u.id));assert.equal(u.flightJob.type,'return');g.projectiles=[];let n=0;while(AIR(u)&&n++<3000)g.update(1/30);assert.equal(u.airportId,base.id);
 const b=g.add('red','bomberRed',100,60);assert.ok(g.order(b,'bombRun',{start:{x:80,y:60},end:{x:72,y:60}}));g.projectiles=[{targetId:b.id,weapon:'jetAam',attackerId:u.id,x:b.x-1,y:b.y}];calls.length=0;g.stepPlane(b,1/30);assert.ok(calls.includes(b.id));assert.equal(b.flightJob.type,'bombRun');g.projectiles=[];n=0;while((b.ammo.bombCommon||b.ammo.bombFragment)&&n++<3000)g.update(1/30);assert.equal(b.ammo.bombCommon+b.ammo.bombFragment,0);});
test('borda: combate desliza sem perder velocidade nem girar acima do limite',()=>{for(const type of ['fighterBlue','bomberRed']){const g=field(),u=g.add(TYPES[type].team,type,0,30);u.x=.5;u.facing=-Math.PI/2-.3;for(let n=0;n<300;n++){const x=u.x,y=u.y,a=u.facing;g.flyCombat(u,{x:10,y:30},1/30);assert.ok(Math.abs(Math.hypot(u.x-x,u.y-y)-TYPES[type].speed/30)<1e-6);assert.ok(Math.abs(Math.atan2(Math.sin(u.facing-a),Math.cos(u.facing-a)))<=g.planeTurnRate(u)/30+1e-8);}}});
test('formacao acima de 1.200 pontos e restaurada; copia isola a batalha',()=>{const old={fighterBlue:1,infantry:12};assert.equal(ctx.armyOverBudget(old),true);assert.equal(ctx.armyOverBudget(ctx.STARTING_DEFAULT),false);assert.equal(ctx.armyCost(ctx.cleanStartingArmy(old)),1145);const army={infantry:2},g=new Game('river','normal',5,'turns',{posts:2},{},{blue:army});army.infantry=20;assert.equal(g.initialArmies.blue.infantry,2);});
test('postos neutros aparecem com frequencia nos cantos e variam por semente',()=>{let corner=0,total=0,layouts=new Set();for(let seed=1;seed<=40;seed++){const g=new Game('random','normal',seed,'rts',{posts:8}),posts=[...g.units,...g.structures].filter(u=>u.type==='post');layouts.add(posts.map(p=>p.x+','+p.y).sort().join(';'));for(const p of posts){total++;if(Math.min(Math.hypot(p.x,p.y),Math.hypot(127-p.x,95-p.y))<=14)corner++;}}assert.ok(layouts.size>=35,'layouts variados');assert.ok(corner/total>.15,'cantos favorecidos: '+corner+'/'+total);});
test('rota RTS ate alvo aereo distante testa poucas casas e nao trava o quadro',()=>{const g=field('rts');g.terrain[KEY(0,0)]='road';const u=g.add('blue','antiAirVehicle',5,90);let calls=0;const f=g.findPath;g.findPath=function(...a){calls++;return f.apply(this,a);};const route=g.pathToRange(u,{x:100.5,y:10},9);assert.ok(route&&route.length>0,'rota encontrada');assert.ok(calls<=13,'buscas A*: '+calls);});
let ran=0;for(const [name,fn]of cases){if(process.argv[2]&&!name.includes(process.argv[2]))continue;fn();console.log('OK '+name);ran++;}console.log(ran+' verificacoes de operacoes.');
