'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..'),out=path.join(root,'test-output','radar-panel');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(root,'public','index.html')).href);await page.evaluate(()=>terrainReady);assert.equal(await page.locator('#radarPanel').count(),1,'Painel circular deve existir no HTML');assert.equal(await page.locator('#radarPanel').isVisible(),false);
 const fixture=async(mode='rts',map='river')=>page.evaluate(({mode,map})=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation(map,'normal',93,mode);game.aiEnabled=false;paused=true;game.units=[];game.structures=[];game.projectiles=[];game.add('blue','hq',1,26);game.add('red','hq',34,1);game.add('blue','infantry',2,26);game.add('red','infantry',34,2);const a=game.add('blue','antiAirVehicle',7,20),b=game.add('blue','antiAirVehicle',16,14),contacts=[[16,2],[30,14],[16,26],[2,14]].map(([x,y])=>{const h=game.add('red','helicopter',x,y);h.altitude='high';return h.id;});const low=game.add('red','helicopter',16,16),hidden=game.add('red','helicopter',32,26),ground=game.add('red','tank',30,14);for(const u of game.units)u.cooldown=100;game.updateVision();renderer.rebuild();cam.zoom=1;centerCamera(13,17);setSelection([b.id]);renderer.draw(0);return{a:a.id,b:b.id,contacts,low:low.id,hidden:hidden.id,ground:ground.id};},{mode,map});
 const advance=async seconds=>page.evaluate(seconds=>{for(let t=0;t<seconds-1e-8;t+=STEP){const dt=Math.min(STEP,seconds-t);game.update(dt);renderer.consume();renderer.draw(dt);}updateUI();},seconds);
 for(const mode of ['turns','rts']){
  const ids=await fixture(mode);assert.equal(await page.locator('#radarPanel').isVisible(),true);assert.match(await page.locator('#radarCollapse').textContent(),/Radar · 5 contatos/);assert.match(await page.locator('#radarReference').textContent(),new RegExp('#'+ids.b));assert.equal(await page.locator('#radarCollapse').getAttribute('aria-expanded'),'true');assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.getBoundingClientRect().width),176);
  const drawn=await page.evaluate(()=>{const c=$('radarDisplay').getContext('2d'),arcs=[],squares=[],labels=[],arc=c.arc,rect=c.strokeRect,text=c.fillText;c.arc=function(x,y,r,start,end,...rest){arcs.push({x,y,r,start,end});arc.call(this,x,y,r,start,end,...rest);};c.strokeRect=function(x,y,w,h){if(this.strokeStyle==='#68ef8d')squares.push({x,y,w,h});rect.call(this,x,y,w,h);};c.fillText=function(t,...rest){labels.push(t);text.call(this,t,...rest);};try{renderer.drawRadar();}finally{c.arc=arc;c.strokeRect=rect;c.fillText=text;}return{arcs,squares,labels};});assert.ok(drawn.arcs.filter(a=>Math.abs(a.end-a.start-Math.PI*2)<1e-6).length>=4);assert.equal(drawn.squares.length,5);for(const label of ['0°','90°','180°','270°'])assert.ok(drawn.labels.includes(label));const center=88;assert.ok(drawn.squares[0].y<center&&Math.abs(drawn.squares[0].x+drawn.squares[0].w/2-center)<1);assert.ok(drawn.squares[1].x>center);assert.ok(drawn.squares[2].y>center);assert.ok(drawn.squares[3].x<center);
  // Referência estável: menor id selecionado, mesmo desligado, e fallback para o menor radar ativo.
  await page.evaluate(ids=>{game.setRadar(game.get(ids.a),false);setSelection([ids.b,ids.a]);renderer.draw(0);},ids);assert.match(await page.locator('#radarReference').textContent(),new RegExp('#'+ids.a));await page.evaluate(()=>{setSelection([]);renderer.draw(0);});assert.match(await page.locator('#radarReference').textContent(),new RegExp('#'+ids.b));await page.evaluate(ids=>{game.setRadar(game.get(ids.a),true);game.hurt(game.get(ids.b),999,null);renderer.draw(0);},ids);assert.match(await page.locator('#radarReference').textContent(),new RegExp('#'+ids.a));await page.evaluate(ids=>{game.setRadar(game.get(ids.a),false);renderer.draw(0);},ids);assert.equal(await page.locator('#radarPanel').isVisible(),false);await page.evaluate(ids=>{game.setRadar(game.get(ids.a),true);renderer.draw(0);},ids);assert.equal(await page.locator('#radarPanel').isVisible(),true);
  // Desenhar e recolher não alteram unidades, visão, terreno, ordens ou sequência de combate.
  const snapshot=await page.evaluate(()=>JSON.stringify([game.units,game.projectiles,game.terrain,game.explored,game.visible,game.sky,game.credits]));await page.locator('#radarCollapse').click();assert.equal(await page.locator('#radarBody').isVisible(),false);assert.equal(await page.locator('#radarCollapse').getAttribute('aria-expanded'),'false');await page.locator('#radarCollapse').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#radarBody').isVisible(),true);assert.equal(await page.evaluate(()=>JSON.stringify([game.units,game.projectiles,game.terrain,game.explored,game.visible,game.sky,game.credits])),snapshot);
  const still=await page.locator('#radarDisplay').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.toDataURL()),still);await advance(1);assert.notEqual(await page.locator('#radarDisplay').evaluate(c=>c.toDataURL()),still);await advance(3);assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.toDataURL()),still);console.log('OK '+mode+': contatos imediatos nas quatro direções, referência, radares, colapso acessível, pausa e volta em 4 s.');
 }
 let ids=await fixture();const border=await page.evaluate(ids=>{const source=game.get(ids.b),target=game.get(ids.contacts[0]);source.x=source.y=0;target.x=COLS-1;target.y=ROWS-1;const c=$('radarDisplay').getContext('2d'),rect=c.strokeRect,points=[];c.strokeRect=function(x,y,w,h){if(this.strokeStyle==='#68ef8d')points.push({x,y,w,h});rect.call(this,x,y,w,h);};try{renderer.drawRadar();}finally{c.strokeRect=rect;}const p=points[0],r=$('radarDisplay').clientWidth/2-2,mid=r+2;return Math.max(...[[p.x,p.y],[p.x+p.w,p.y],[p.x,p.y+p.h],[p.x+p.w,p.y+p.h]].map(([x,y])=>Math.hypot(x-mid,y-mid)))<=r;},ids);assert.equal(border,true,'Contato na diagonal inteira deve caber com seu quadrado completo');
 ids=await fixture();const randomCalls=await page.evaluate(()=>{const rng=game.rng;let calls=0;game.rng=()=>{calls++;return rng();};try{renderer.drawRadar();$('radarCollapse').click();$('radarCollapse').click();return calls;}finally{game.rng=rng;}});assert.equal(randomCalls,0,'Radar não consome a sequência de combate');
 const privacy=await page.evaluate(ids=>{const k=KEY(30,14),source=game.get(ids.b),before=$('radarDisplay').toDataURL();source.x+=1;renderer.drawRadar();const moved=before!==$('radarDisplay').toDataURL();game.get(ids.contacts[1]).altitude='low';game.updateVision();renderer.drawRadar();return{moved,count:radarView().contacts.length,hidden:radarView().contacts.some(u=>u.id===ids.hidden||u.id===ids.ground),explored:game.explored.blue[k],visible:game.visible.blue[k]};},ids);assert.deepEqual(privacy,{moved:true,count:4,hidden:false,explored:true,visible:false});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>reducedMotion);const staticFrame=await page.locator('#radarDisplay').evaluate(c=>c.toDataURL());await advance(1);assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.toDataURL()),staticFrame);await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>!reducedMotion);console.log('OK posição lógica móvel, perda de contato, névoa e movimento reduzido.');
 fs.mkdirSync(out,{recursive:true});
 for(const device of ['desktop','mobile','short'])for(const map of ['river','desert','mountain','random']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:device==='mobile'?{width:390,height:844}:{width:568,height:320});ids=await fixture('rts',map);await page.waitForTimeout(120);assert.equal(await page.locator('#radarCollapse').getAttribute('aria-expanded'),device==='short'?'false':'true');const layout=await page.evaluate(()=>{const ids=['radarPanel','commandBar','radarControls'],rects=ids.map(id=>{const r=$(id).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});return{overflow:document.documentElement.scrollWidth>innerWidth,rects,map:renderer.canvas.clientHeight};});assert.equal(layout.overflow,false);assert.ok(layout.map>80);for(const r of layout.rects){assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=await page.evaluate(()=>innerWidth)+1&&r.y+r.h<=await page.evaluate(()=>innerHeight)+1,JSON.stringify({device,layout}));}const [r,c]=layout.rects;assert.ok(r.x+r.w<=c.x+1||c.x+c.w<=r.x+1||r.y+r.h<=c.y+1||c.y+c.h<=r.y+1,'Painel e comandos não podem se sobrepor');await page.screenshot({path:path.join(out,`${map}-${device}.png`)});
  if(device==='mobile'){assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.getBoundingClientRect().width),112);await page.locator('#radarCollapse').click();await page.screenshot({path:path.join(out,`${map}-mobile-collapsed.png`)});}
  if(device==='short'){await page.locator('#radarCollapse').click();assert.equal(await page.locator('#radarBody').isVisible(),true);const boxes=await page.evaluate(()=>['radarPanel','commandBar','battlefield'].map(id=>{const r=$(id).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}));const [p,c,f]=boxes;for(const b of [p,c])assert.ok(b.y>=f.y-1&&b.y+b.h<=f.y+f.h+1,'Radar aberto e comandos devem caber no campo baixo');assert.ok(p.x+p.w<=c.x+1||c.x+c.w<=p.x+1,'Radar aberto não cobre comandos');await page.screenshot({path:path.join(out,`${map}-short-expanded.png`)});await page.locator('#infoToggle').click();const details=await page.evaluate(()=>{const d=$('details').getBoundingClientRect(),c=$('commandBar').getBoundingClientRect();return d.bottom>c.top&&d.top<c.bottom;});assert.ok(details,'Detalhes devem estar na área rolável de comandos');await page.locator('#infoToggle').click();}
 }
 console.log('OK quatro mapas: radar expandido, compacto e recolhido; computador, celular e tela baixa.');
 // A faixa deve caber pela altura real do campo, inclusive janela larga baixa e grupos com muitos comandos.
 for(const viewport of [{width:1280,height:300},{width:320,height:568},{width:390,height:667}]){
  await page.setViewportSize(viewport);ids=await fixture();if(viewport.width<600){await page.evaluate(ids=>{const h=game.add('blue','helicopter',17,14),e=game.add('blue','engineer',17,15);setSelection([ids.b,h.id,e.id]);},ids);await page.keyboard.press('m');}
  if(await page.locator('#radarCollapse').getAttribute('aria-expanded')==='false')await page.locator('#radarCollapse').click();
  const bounds=await page.evaluate(()=>['radarPanel','commandBar','battlefield'].map(id=>{const r=$(id).getBoundingClientRect();return{top:r.top,bottom:r.bottom};}));const [p,c,f]=bounds;assert.ok(p.top>=f.top&&p.bottom<=f.bottom,'Radar inteiro deve caber no campo '+JSON.stringify(viewport));assert.ok(c.top>=f.top&&c.bottom<=f.bottom,'Comandos devem caber no campo '+JSON.stringify(viewport));
  await page.locator('#infoToggle').click();await page.locator('#unitRole').scrollIntoViewIfNeeded();const readable=await page.evaluate(()=>{const d=$('unitRole').getBoundingClientRect(),f=$('battlefield').getBoundingClientRect(),c=$('commandBar').getBoundingClientRect(),scrolling=getComputedStyle($('commandBar')).overflowY==='auto';return d.top>=f.top&&d.bottom<=f.bottom&&(!scrolling||d.top>=c.top&&d.bottom<=c.bottom);});assert.ok(readable,'Detalhes acessíveis sem recorte '+JSON.stringify(viewport));await page.screenshot({path:path.join(out,`details-${viewport.width}-${viewport.height}.png`)});await page.locator('#infoToggle').click();
 }
 console.log('OK faixa e detalhes em janela larga baixa e grupo misto no celular baixo.');
 // Pausa em menus/aba, controle de velocidade e gravação do radar real.
 await page.setViewportSize({width:1440,height:1000});ids=await fixture();await page.evaluate(()=>speed=.5);const before=await page.evaluate(()=>game.time);await page.keyboard.press('p');await page.waitForTimeout(650);const delta=await page.evaluate(t=>game.time-t,before);assert.ok(delta>.2&&delta<.5);await page.keyboard.press('p');await page.locator('#menuButton').click();const menuFrame=await page.locator('#radarDisplay').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);assert.equal(await page.locator('#radarDisplay').evaluate(c=>c.toDataURL()),menuFrame);await page.locator('#titleResume').click();assert.equal(await page.evaluate(()=>paused),true);
 await page.evaluate(()=>{speed=1;window.chunks=[];window.recorder=new MediaRecorder($('radarDisplay').captureStream(30),{mimeType:'video/webm;codecs=vp9'});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();});await page.keyboard.press('p');await page.waitForTimeout(4300);await page.keyboard.press('p');const video=await page.evaluate(()=>new Promise(resolve=>{recorder.onstop=()=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(new Blob(chunks,{type:'video/webm'}));};recorder.stop();}));const bytes=Buffer.from(video,'base64');assert.ok(bytes.length>10000);assert.equal(bytes.subarray(0,4).toString('hex'),'1a45dfa3');fs.writeFileSync(path.join(out,'radar-circular.webm'),bytes);
 const decoded=await page.evaluate(video=>new Promise((resolve,reject)=>{const v=document.createElement('video');v.muted=true;v.onloadeddata=()=>{v.currentTime=.3;};v.onseeked=()=>{v.requestVideoFrameCallback(()=>{const c=document.createElement('canvas');c.width=c.height=100;const x=c.getContext('2d');x.drawImage(v,0,0,100,100);const d=x.getImageData(0,0,100,100).data,colors=new Set();for(let i=0;i<d.length;i+=4)colors.add(d[i]+','+d[i+1]+','+d[i+2]);v.pause();resolve({w:v.videoWidth,h:v.videoHeight,colors:colors.size});});v.play().catch(reject);};v.onerror=()=>reject(Error('Falha ao decodificar radar WebM'));v.src='data:video/webm;base64,'+video;}),video);assert.ok(decoded.w>=176&&decoded.h>=176&&decoded.colors>20,JSON.stringify(decoded));
 await page.evaluate(()=>{paused=false;Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await page.evaluate(()=>paused),true);assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('OK velocidade, menus/aba, gravação decodificada e operação offline sem erro JS.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
