'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync('public/js/engine.js','utf8')+'\nthis.api={Game,KEY,DIST};',ctx);const {Game,KEY,DIST}=ctx.api;
function field(mode){const g=new Game('river','normal',19,mode);g.terrain.fill('plain');g.units=[];g.structures=[];g.aiEnabled=false;g.add('blue','hq',0,27);g.add('red','hq',35,0);g.add('blue','infantry',1,27);g.add('red','infantry',34,0);g.rng=()=>.2;return g;}
function advance(g,s){for(let t=0;t<s-1e-8;t+=1/30)g.update(Math.min(1/30,s-t));}
let checks=0;function check(name,fn){fn();checks++;console.log('OK '+name);}
for(const mode of ['turns','rts']){
 check(mode+': alcance infinito, visão aliada e alvo aéreo exclusivamente',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),h=g.add('red','helicopter',30,3),land=g.add('red','tank',30,3);g.add('blue','recon',28,3);h.cooldown=100;g.updateVision();assert.equal(g.range(a,h),Infinity);assert.equal(g.range(a,land),0);assert.ok(g.canFire(a,h));const cell=[a.x,a.y];assert.ok(g.order(a,'attack',{targetId:h.id}));assert.equal(a.path.length,0);advance(g,.1);assert.deepEqual([a.x,a.y],cell);const missiles=g.projectiles.filter(p=>p.attackerId===a.id);assert.equal(missiles.length,1);assert.equal(missiles[0].duration,DIST(a,h)/6);assert.equal(g.sight(a),6);assert.equal(g.order(a,'attack',{targetId:land.id}),false);});
 check(mode+': radar por identidade, controle gratuito, múltiplos veículos e morte',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),b=g.add('blue','antiAirVehicle',3,25),h=g.add('red','helicopterAir',30,3),low=g.add('red','helicopter',31,3),land=g.add('red','tank',30,3),base=g.add('red','post',30,4);h.altitude='high';g.updateVision();const k=KEY(h.x,h.y);assert.equal(a.radarOn,true);assert.ok(g.radarContact('blue',h));assert.ok(g.isVisible('blue',h));assert.equal(g.isVisible('blue',low),false);assert.equal(g.isVisible('blue',land),false);assert.equal(g.isVisible('blue',base),false);assert.equal(g.sky.blue[k],false);assert.equal(g.explored.blue[k],false);assert.ok(g.effectVisible(h.x,h.y,true,h.id));assert.equal(g.effectVisible(a.x+12,a.y-12,true,h.id),false);
  const before=[a.actionLeft,a.moveLeft,g.credits.blue,a.cooldown,a.pending];assert.ok(g.setRadar(a,false));assert.deepEqual([a.actionLeft,a.moveLeft,g.credits.blue,a.cooldown,a.pending],before);assert.equal(g.radarContact('blue',h),true);g.hurt(b,999,null);assert.equal(g.radarContact('blue',h),false);assert.equal(g.isVisible('blue',h),false);assert.equal(g.setRadar(low,true),false);g.setRadar(a,true);assert.ok(g.isVisible('blue',h));h.altitude='low';g.updateVision();assert.equal(g.isVisible('blue',h),false);
  const red=g.add('red','antiAirVehicle',34,2),blue=g.add('blue','helicopter',1,25);blue.altitude='high';g.updateVision();assert.ok(g.radarContact('red',blue));assert.equal(red.radarOn,true);
 });
 check(mode+': altitude anterior até conclusão, radar em movimento e delta zero',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),h=g.add('red','helicopter',30,3);g.turn='red';g.aiWait=100;a.cooldown=h.cooldown=100;g.order(h,'altitude',{altitude:'high'});advance(g,.9);assert.equal(g.radarContact('blue',h),false);advance(g,.1);assert.equal(g.radarContact('blue',h),true);h.actionLeft=true;g.order(h,'altitude',{altitude:'low'});advance(g,.9);assert.ok(g.radarContact('blue',h));advance(g,.1);assert.equal(g.radarContact('blue',h),false);h.altitude='high';g.updateVision();g.turn='blue';g.order(a,'move',{x:5,y:25});advance(g,.1);assert.ok(a.segment);assert.ok(g.radarContact('blue',h));const state=JSON.stringify([a,h,g.projectiles,g.time]);g.update(0);assert.equal(JSON.stringify([a,h,g.projectiles,g.time]),state);});
 check(mode+': míssil distante guiado causa dano no impacto e mantém duração de lançamento',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),h=g.add('red','helicopter',30,3);h.altitude='high';h.flares=0;g.updateVision();g.shoot(a,h);a.cooldown=h.cooldown=100;const p=g.projectiles[0],duration=p.duration;advance(g,.5);assert.equal(h.hp,120);h.x=31;advance(g,.1);assert.equal(p.tx,31);assert.equal(p.duration,duration);advance(g,duration-.6);assert.equal(g.projectiles.length,0);assert.equal(h.hp,50);});
 check(mode+': destruir o lançador preserva outro radar; destruir o último cancela guiagem',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),b=g.add('blue','antiAirVehicle',3,25),h=g.add('red','helicopter',30,3);h.altitude='high';h.flares=0;b.cooldown=h.cooldown=100;g.updateVision();g.shoot(a,h);const p=g.projectiles[0];g.hurt(a,999,null);advance(g,.1);assert.ok(!p.lostGuidance);g.hurt(b,999,null);assert.equal(g.radarContacts.blue.size,0);advance(g,.1);assert.equal(p.lostGuidance,true);advance(g,p.duration);assert.equal(h.hp,120);});
 check(mode+': perda definitiva, último ponto e nenhum dano após contato retornar',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),h=g.add('red','helicopter',30,3);h.altitude='high';h.flares=0;a.cooldown=h.cooldown=100;g.updateVision();g.shoot(a,h);const p=g.projectiles[0];advance(g,.2);const last=[p.tx,p.ty,p.targetLevel];g.setRadar(a,false);const frozen=JSON.stringify(p);g.update(0);assert.equal(JSON.stringify(p),frozen);h.x=31;h.y=4;advance(g,.1);assert.equal(p.lostGuidance,true);assert.deepEqual([p.tx,p.ty,p.targetLevel],last);g.setRadar(a,true);advance(g,.1);assert.equal(p.lostGuidance,true);assert.deepEqual([p.tx,p.ty,p.targetLevel],last);a.cooldown=h.cooldown=100;advance(g,p.duration);assert.equal(h.hp,120);assert.ok(g.events.some(e=>e.kind==='blast'&&e.lostGuidance));});
 check(mode+': outros observadores preservam guiagem; flares e demais armas preservados',()=>{const g=field(mode),a=g.add('blue','antiAirVehicle',2,25),h=g.add('red','helicopter',30,3);h.altitude='high';h.flares=0;g.add('blue','recon',29,3);g.updateVision();g.shoot(a,h);const p=g.projectiles[0];g.setRadar(a,false);h.altitude='low';g.updateVision();advance(g,.1);assert.ok(!p.lostGuidance);h.x=31;advance(g,.1);assert.equal(p.tx,31);
  const f=field(mode),aa=f.add('blue','antiAirVehicle',2,25),air=f.add('red','helicopterAir',30,3);air.altitude='high';f.rng=()=>.6;f.updateVision();f.shoot(aa,air);const shot=f.projectiles[0];assert.equal(shot.deflected,true);assert.equal(air.flares,2);f.setRadar(aa,false);advance(f,.1);assert.equal(shot.lostGuidance,true);assert.equal(shot.deflected,true);aa.cooldown=air.cooldown=100;advance(f,shot.duration);assert.equal(air.hp,120);
  const u=g.add('blue','helicopterAir',25,3);g.shoot(u,h);assert.equal(g.projectiles.at(-1).duration,1);assert.equal(g.range(u,h),6);
 });
}
check('IA ataca contato distante sem deslocar e mínimos de voo mantidos',()=>{const g=field('rts'),aa=g.add('red','antiAirVehicle',33,3),h=g.add('blue','helicopter',2,25);h.altitude='high';g.updateVision();assert.equal(g.aiAcquire(aa),h);g.aiAct(aa);assert.equal(aa.order.type,'attack');assert.equal(aa.path.length,0);g.stepRTS(aa,.1);assert.equal(g.projectiles.length,1);h.x=33;h.y=4;h.flares=0;g.shoot(aa,h);assert.equal(g.projectiles.at(-1).duration,.45);});
console.log(checks+' verificações de radar concluídas.');
