'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const root=path.join(__dirname,'..'),out=path.join(root,'test-output','radar');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(root,'public','index.html')).href);await page.evaluate(()=>terrainReady);
 const fixture=async(mode='rts',map='river')=>page.evaluate(({mode,map})=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newOperation(map,'normal',91,mode);game.aiEnabled=false;paused=true;settings.graphics='balanced';game.units=[];game.structures=[];game.projectiles=[];game.add('blue','hq',1,26);game.add('red','hq',34,1);game.add('blue','infantry',2,26);game.add('red','infantry',34,2);const a=game.add('blue','antiAirVehicle',7,20),b=game.add('blue','antiAirVehicle',8,20),h=game.add('red','helicopterAir',17,14),land=game.add('red','tank',17,14),low=game.add('red','helicopter',18,14);h.altitude='high';h.flares=0;for(const u of game.units)u.cooldown=100;a.cooldown=0;game.rng=()=>.2;game.updateVision();renderer.rebuild();cam.zoom=1;centerCamera(13,17);setSelection([a.id]);updateUI();renderer.draw(0);return{a:a.id,b:b.id,h:h.id,land:land.id,low:low.id};},{mode,map});
 const advance=async s=>page.evaluate(s=>{for(let t=0;t<s-1e-8;t+=STEP){const dt=Math.min(STEP,s-t);game.update(dt);renderer.consume();renderer.draw(dt);}updateUI();},s);
 const click=async(id,button='left')=>{const p=await page.evaluate(id=>{const u=game.get(id),pose=flightPose(u),r=renderer.canvas.getBoundingClientRect();return{x:r.left+((pose.x+.5)*CELL-cam.x)*cam.zoom,y:r.top+((pose.y+.5)*CELL-cam.y)*cam.zoom};},id);await page.mouse.click(p.x,p.y,{button});};
 for(const mode of ['turns','rts']){
  const ids=await fixture(mode);assert.equal(await page.locator('#radarToggle').textContent(),'Radar: ligado');assert.equal(await page.locator('#radarCount').textContent(),'Contatos da equipe: 1 · fumaça 2/2');await page.locator('#infoToggle').click();assert.match(await page.locator('#unitInfo').textContent(),/Alcance 0–30 · somente aeronaves/);
  const fog=await page.evaluate(ids=>{const h=game.get(ids.h),k=KEY(h.x,h.y);return{visible:game.isVisible('blue',h),low:game.isVisible('blue',game.get(ids.low)),land:game.isVisible('blue',game.get(ids.land)),sky:game.sky.blue[k],explored:game.explored.blue[k]};},ids);assert.deepEqual(fog,{visible:true,low:false,land:false,sky:false,explored:true});
  // Pixels verdes realmente desenhados na posição elevada e no minimapa, sem selecionar a antiaérea.
  const marker=await page.evaluate(ids=>{setSelection([]);const h=game.get(ids.h),pose=flightPose(h),rects=[],c=renderer.ctx,stroke=c.strokeRect;c.strokeRect=function(x,y,w,h){if(this.strokeStyle==='#68ef8d')rects.push({x,y,w,h});stroke.call(this,x,y,w,h);};try{renderer.draw(0);}finally{c.strokeRect=stroke;}renderer.drawMini();const mt=miniTransform(renderer.mini.canvas),d=renderer.mini.getImageData(Math.floor(mt.ox+(h.x+.5)*mt.s-5),Math.floor(mt.oy+(h.y+.5)*mt.s-5),10,10).data;let green=0;for(let i=0;i<d.length;i+=4)if(d[i+1]>180&&d[i+1]>d[i]*1.3)green++;return{rects,y:(pose.y+.5)*CELL,green};},ids);assert.equal(marker.rects.length,1);assert.ok(Math.abs(marker.rects[0].y+marker.rects[0].h/2-marker.y)<1e-7);assert.ok(marker.green>4);
  await click(ids.h);assert.equal(await page.evaluate(()=>[...selection][0]),ids.h);await page.locator('#infoToggle').click();assert.match(await page.locator('#unitInfo').textContent(),/Em voo sobre/);await page.evaluate(ids=>setSelection([ids.a]),ids);await click(ids.h,'right');assert.equal(await page.evaluate(ids=>game.get(ids.a).order.targetId,ids),ids.h);await advance(.1);assert.ok(await page.evaluate(()=>game.projectiles.some(p=>p.weapon==='antiAirVehicle'&&p.duration>1.2)));const state=await page.evaluate(()=>JSON.stringify([game.time,game.projectiles,game.units]));await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>JSON.stringify([game.time,game.projectiles,game.units])),state);
  // Estado misto e controle de grupo não alteram outras classes; grátis mesmo com disparo ativo.
  await page.evaluate(ids=>{game.setRadar(game.get(ids.b),false);setSelection([ids.a,ids.b,game.units.find(u=>u.type==='infantry'&&u.owner==='blue').id]);},ids);assert.equal(await page.locator('#radarToggle').getAttribute('aria-pressed'),'mixed');const before=await page.evaluate(ids=>ids.a&&JSON.stringify([game.credits,game.units.map(u=>[u.id,u.actionLeft,u.moveLeft,u.cooldown])]),ids);await page.locator('#radarToggle').click();assert.ok(await page.evaluate(ids=>[ids.a,ids.b].every(id=>game.get(id).radarOn),ids));await page.locator('#radarToggle').click();assert.equal(await page.locator('#radarCount').textContent(),'Contatos da equipe: 0 · fumaça 2/2, 2/2');assert.equal(await page.evaluate(()=>JSON.stringify([game.credits,game.units.map(u=>[u.id,u.actionLeft,u.moveLeft,u.cooldown])])),before);assert.ok(await page.evaluate(()=>game.projectiles.every(p=>!p.lostGuidance)));
  await advance(.1);assert.ok(await page.evaluate(()=>game.projectiles.some(p=>p.lostGuidance)));await page.locator('#radarToggle').click();await advance(3);assert.equal(await page.evaluate(ids=>{const u=game.get(ids.h);return u.hp/u.maxHp;},ids),1);assert.ok(await page.evaluate(()=>game.projectiles.length===0));console.log('OK '+mode+': interface, grupo/misto, radar gratuito na pausa, seleção/ataque remoto, perda definitiva sem dano.');
 }
 // Origem oculta e trecho distante ficam invisíveis; somente efeitos próximos do contato detectado aparecem.
 let ids=await fixture();const effects=await page.evaluate(ids=>{const a=game.get(ids.a),h=game.get(ids.h);game.shoot(a,h);const p=game.projectiles[0];game.events=[];game.visible.blue.fill(false);game.sky.blue.fill(false);renderer.particles=[];const sample=(x,y)=>{p.x=x;p.y=y;renderer.draw(0);const withMissile=renderer.canvas.toDataURL();game.projectiles=[];renderer.draw(0);const bare=renderer.canvas.toDataURL();game.projectiles=[p];return withMissile!==bare;};const near=sample(h.x-1,h.y),hidden=sample(12,17);game.event('smoke',{x:h.x,y:h.y,owner:'red'},{air:true,contactId:h.id,flightLevel:1,visible:game.effectVisible(h.x,h.y,true,h.id)});renderer.consume();renderer.draw(0);const withSmoke=renderer.canvas.toDataURL();renderer.particles=[];renderer.draw(0);const smoke=withSmoke!==renderer.canvas.toDataURL();const far=game.add('red','antiAirVehicle',25,14);game.event('shot',far,{weapon:'antitank'});const origin=game.events.at(-1).visible;return{near,hidden,smoke,origin};},ids);assert.deepEqual(effects,{near:true,hidden:true,smoke:true,origin:false});console.log('OK contato por identidade sem explorar terreno, marcador elevado, minimapa e efeitos sem vazamento da névoa.');
 ids=await fixture();const outgoing=await page.evaluate(ids=>{const h=game.get(ids.h);h.type='helicopterGround';const target=game.add('blue','artillery',12,14);game.updateVision();game.shoot(h,target);const p=game.projectiles[0];game.events=[];p.x=h.x-1;p.y=h.y;renderer.draw(0);const drawn=renderer.canvas.toDataURL();game.projectiles=[];renderer.draw(0);const missile=drawn!==renderer.canvas.toDataURL();game.projectiles=[p];game.update(STEP);renderer.consume();renderer.draw(0);const smokeImage=renderer.canvas.toDataURL();renderer.particles=[];renderer.draw(0);return{weapon:p.weapon,local:game.sky.blue[KEY(h.x,h.y)],missile,smoke:smokeImage!==renderer.canvas.toDataURL()};},ids);assert.deepEqual(outgoing,{weapon:'agm',local:false,missile:true,smoke:true});console.log('OK míssil e fumaça também visíveis perto do helicóptero alto que os lançou.');
 for(const device of ['desktop','mobile'])for(const map of ['river','desert','mountain','random']){
  await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});ids=await fixture('rts',map);await page.evaluate(ids=>{if(innerWidth<600)centerCamera(16,15);game.setRadar(game.get(ids.b),false);},ids);await page.waitForTimeout(100);const layout=await page.evaluate(()=>{const r=$('radarControls').getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>innerWidth,right:r.right,bottom:r.bottom,height:renderer.canvas.clientHeight};});assert.equal(layout.overflow,false);assert.ok(layout.right<=await page.evaluate(()=>innerWidth)&&layout.height>80);await page.screenshot({path:path.join(out,`${map}-${device}-radar.png`)});
 }
 console.log('OK quatro mapas em computador e viewport móvel, sem cortar os controles.');
 // Gravação da detecção/disparo/perda de contato com o relógio e renderização reais.
 await page.setViewportSize({width:1440,height:1000});ids=await fixture();await page.evaluate(ids=>{game.setRadar(game.get(ids.b),false);const a=game.get(ids.a);a.x=1;a.y=28;game.updateVision();},ids);await page.waitForTimeout(100);await page.evaluate(()=>{renderer.draw(0);window.recorded=[];window.recorder=new MediaRecorder(renderer.canvas.captureStream(30),{mimeType:'video/webm;codecs=vp9'});recorder.ondataavailable=e=>recorded.push(e.data);recorder.start();});await page.waitForTimeout(400);await click(ids.h,'right');await page.keyboard.press('p');await page.waitForFunction(()=>game.projectiles.length>0);await page.waitForTimeout(650);await page.evaluate(ids=>{game.order(game.get(ids.h),'altitude',{altitude:'low'});},ids);await page.waitForFunction(()=>game.projectiles.some(p=>p.lostGuidance));await page.waitForFunction(()=>game.projectiles.length===0);await page.waitForTimeout(300);
 assert.equal(await page.evaluate(ids=>{const u=game.get(ids.h);return u.hp/u.maxHp;},ids),1);const video=await page.evaluate(()=>new Promise(resolve=>{recorder.onstop=()=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(recorded,{type:'video/webm'}));};recorder.stop();paused=true;}));const bytes=Buffer.from(video,'base64');assert.ok(bytes.length>10000);assert.equal(bytes.subarray(0,4).toString('hex'),'1a45dfa3');fs.writeFileSync(path.join(out,'radar-disparo-perda.webm'),bytes);
 const decoded=await page.evaluate(video=>new Promise((resolve,reject)=>{const v=document.createElement('video');v.onloadeddata=()=>{v.currentTime=.3;};v.onseeked=()=>{const c=document.createElement('canvas');c.width=120;c.height=80;const q=c.getContext('2d');q.drawImage(v,0,0,120,80);const d=q.getImageData(0,0,120,80).data,colors=new Set();for(let i=0;i<d.length;i+=4)colors.add(d[i]+','+d[i+1]+','+d[i+2]);resolve({width:v.videoWidth,height:v.videoHeight,colors:colors.size});};v.onerror=()=>reject(Error('WebM não decodifica'));v.src='data:video/webm;base64,'+video;}),video);assert.ok(decoded.width>100&&decoded.height>100&&decoded.colors>20);
 // Velocidade controlada pela interface; projétil e radar continuam disponíveis com arte ausente.
 ids=await fixture();await page.evaluate(()=>speed=.5);await click(ids.h,'right');await page.keyboard.press('p');const t=await page.evaluate(()=>game.time);await page.waitForTimeout(600);const elapsed=await page.evaluate(()=>game.time);assert.ok(elapsed-t>.15&&elapsed-t<.45);await page.keyboard.press('p');await page.evaluate(()=>{antiAirAtlas.src='data:image/png;base64,AA==';});await page.waitForFunction(()=>antiAirAtlas.complete&&!antiAirAtlas.naturalWidth);await page.evaluate(()=>{sprites.clear();renderer.draw(0);});await page.screenshot({path:path.join(out,'fallback-radar.png')});assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('OK WebM decodificada, velocidade, fallback e file:// sem rede ou erros JS.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
