// Cenários de terreno no Canvas real, sem rede; não altera o motor.
const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.setOffline(true);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'..','public','index.html')).href);await page.evaluate(()=>terrainReady);
assert.equal(await page.locator('#grid').count(),1,'Botão Grade deve existir');assert.equal(await page.locator('#grid').getAttribute('aria-pressed'),'false');
await page.locator('#titlePlay').click();await page.locator('#seed').fill('83');await page.locator('#mapSelect').selectOption('random');await page.getByRole('button',{name:'Iniciar operação'}).click();await page.evaluate(()=>{paused=true;updateUI();});
const before=await page.evaluate(()=>renderer.ground.toDataURL());await page.locator('#grid').click();assert.equal(await page.locator('#grid').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>renderer.ground.toDataURL()),before,'Grade não modifica o cache do chão');await page.reload();await page.evaluate(()=>terrainReady);assert.equal(await page.locator('#grid').getAttribute('aria-pressed'),'true');await page.locator('#titlePlay').click();await page.getByRole('button',{name:'Iniciar operação'}).click();await page.locator('#battlefield').focus();await page.keyboard.press('g');assert.equal(await page.locator('#grid').getAttribute('aria-pressed'),'false');console.log('OK grade opcional acessível, persistente e independente do chão');
const composition=await page.evaluate(()=>{const g=new Game('random','normal',83),expected=new Game('random','normal',83),state=v=>JSON.stringify({terrain:v.terrain,units:v.all(),mines:v.mines,credits:v.credits,queue:v.hq('blue').queue});const initial=state(g),canvas=document.createElement('canvas');canvas.width=COLS*CELL;canvas.height=ROWS*CELL;renderTerrain(canvas.getContext('2d'),g);const first=canvas.toDataURL();renderTerrain(canvas.getContext('2d'),g);const second=canvas.toDataURL();drawPreview(document.querySelector('#preview'),g);const unchanged=initial===state(g)&&g.rng()===expected.rng();const other=new Game('desert','normal',17);drawPreview(document.querySelector('#preview'),other);return{deterministic:first===second,unchanged,explicitMap:document.querySelector('#preview').toDataURL()!==first};});assert.ok(composition.deterministic);assert.ok(composition.unchanged);assert.ok(composition.explicitMap);console.log('OK composição determinística com mapa explícito, sem consumir RNG da partida');
const layers=await page.evaluate(()=>{const result={};for(const name of ['forest','forest-desert','mountain','mountain-desert']){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.drawImage(terrainImages[name],0,0);const p=ctx.getImageData(0,0,128,128).data;let transparent=0;for(let i=3;i<p.length;i+=4)if(p[i]<250)transparent++;result[name]=transparent;}return result;});for(const [name,transparent] of Object.entries(layers))assert.ok(transparent>128,name+' precisa de transparência real');
const tiles=await page.evaluate(()=>{const g=new Game('river','normal',17);g.terrain.fill('plain');g.terrain[KEY(8,6)]=g.terrain[KEY(9,6)]='river';const c=document.createElement('canvas');c.width=112;c.height=56;const ctx=c.getContext('2d');ctx.drawImage(terrainTile(g,8,6),0,0);ctx.drawImage(terrainTile(g,9,6),56,0);const pixel=x=>Array.from(ctx.getImageData(x,28,1,1).data),a=pixel(55),b=pixel(56);const jump=Math.max(...a.slice(0,3).map((v,i)=>Math.abs(v-b[i])));let holes=0;for(const alpha of ctx.getImageData(0,0,112,56).data.filter((_,i)=>i%4===3))if(alpha!==255)holes++;g.terrain[KEY(8,6)]='forest';g.terrain[KEY(9,6)]='plain';const plain=terrainTile(g,9,6),flat=new Game('river','normal',17);flat.terrain.fill('plain');const same=plain.toDataURL()===terrainTile(flat,9,6).toDataURL();return{jump,holes,same};});assert.ok(tiles.jump<32,'Água adjacente não deve ter emenda de margem');assert.equal(tiles.holes,0);assert.ok(tiles.same,'Decoração da floresta não invade célula de planície');console.log('OK camadas transparentes, água contínua e células vizinhas preservadas');
for(const fallback of [false,true]){if(fallback)await page.evaluate(()=>{for(const name of Object.keys(terrainImages))terrainImages[name]=new Image();clearTerrainCaches();});for(const type of ['forest','mountain','river','road','bridge','hill','field','hedge']){const secrecy=await page.evaluate(type=>{newOperation('river','normal',19);paused=true;game.terrain.fill('plain');game.terrain[KEY(10,10)]=type;game.units=[];game.structures=[];game.memory.blue.clear();selection.clear();game.explored.blue.fill(false);game.visible.blue.fill(false);game.explored.blue[KEY(10,10)]=game.visible.blue[KEY(10,10)]=true;cam.zoom=1;centerCamera(10,10);hover=null;renderer.paintGround();renderer.draw(0);const first=renderer.canvas.toDataURL();game.terrain[KEY(11,10)]=type;game.terrain[KEY(11,9)]=type;renderer.paintGround();renderer.draw(0);return first===renderer.canvas.toDataURL();},type);assert.ok(secrecy,(fallback?'fallback/':'')+type+': transições não podem revelar terreno desconhecido');}console.log('OK oito tipos de terreno não revelam vizinhos sob a névoa'+(fallback?' sem imagens':''));}
await context.close();const denied=await browser.newContext();await denied.addInitScript(()=>{Storage.prototype.getItem=Storage.prototype.setItem=()=>{throw new Error('Storage blocked');};});const p=await denied.newPage(),deniedErrors=[];p.on('pageerror',e=>deniedErrors.push(e.message));await p.goto(pathToFileURL(path.join(__dirname,'..','public','index.html')).href);await p.evaluate(()=>terrainReady);assert.equal(await p.locator('#grid').getAttribute('aria-pressed'),'false');assert.deepEqual(deniedErrors,[]);assert.deepEqual(errors,[]);console.log('OK armazenamento bloqueado não interrompe o jogo');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
